//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIAlertController.h>

@class MISSING_TYPE;

@interface _TtC10CoreAuthUIP33_AABE3714D9C58676A24E916892CB721E27BiometryAlertViewController : UIAlertController
{
    MISSING_TYPE *biometryType;	// 8 = 0x8
}

- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0040000000037720
- (_Bool)_canShowWhileLocked;	// IMP=0x0010000000037710
- (void)viewDidLoad;	// IMP=0x00100000000376e0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000037590

@end

