//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class BNBannerSource, NSMutableArray;

@interface PresentationViewController : UIViewController
{
    _Bool _isActive;	// 8 = 0x8
    NSMutableArray *_dismissCompletionHandlers;	// 16 = 0x10
    BNBannerSource *_bannerSource;	// 24 = 0x18
}

+ (_Bool)isSpecialUiActive;	// IMP=0x002000000001a812
+ (_Bool)isSpecialUiAvailable;	// IMP=0x001000000001a7fe
- (void).cxx_destruct;	// IMP=0x002000000001a841
@property(readonly, nonatomic) BNBannerSource *bannerSource; // @synthesize bannerSource=_bannerSource;
- (void)shake;	// IMP=0x001000000001a82a
@property(readonly, nonatomic) _Bool isActive;
- (void)revokePresentableWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000001a7ec
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000001a759
- (void)presentOnParentViewController:(id)arg1 animated:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000001a5c6
- (void)viewDidLoad;	// IMP=0x001000000001a574

@end

