//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CNContact, MISSING_TYPE, NSNumber, NSSet, NSString, NSUUID;

@interface _TtC16DaemoniOSLibrary21ShareSheetAirDropNode : NSObject
{
    MISSING_TYPE *nodeIdentifier;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *contactIdentifier;	// 0 = 0x0
    MISSING_TYPE *displayName;	// 5966936 = 0x5b0c58
    MISSING_TYPE *realName;	// 22759 = 0x58e7
    MISSING_TYPE *model;	// 5966936 = 0x5b0c58
    MISSING_TYPE *formattedHandles;	// 0 = 0x0
    MISSING_TYPE *suggestionIndex;	// 0 = 0x0
    MISSING_TYPE *transportBundleID;	// 0 = 0x0
    MISSING_TYPE *isClassroom;	// 2004049759 = 0x77735f5f
    MISSING_TYPE *isDisabled;	// 1717924447 = 0x6665725f
    MISSING_TYPE *isSuggestion;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *selectionReason;	// 0 = 0x0
    MISSING_TYPE *displayIcon;	// 5989696 = 0x5b6540
    MISSING_TYPE *endpointUUID;	// 16293 = 0x3fa5
    MISSING_TYPE *contact;	// 5989696 = 0x5b6540
}

- (void).cxx_destruct;	// IMP=0x004000000047ad50
- (id)init;	// IMP=0x001000000047ace0
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, retain) CNContact *contact; // @synthesize contact;
@property(nonatomic, copy) NSUUID *endpointUUID;
- (id)displayNameForLocale:(id)arg1;	// IMP=0x001000000047a830
@property(nonatomic, retain) struct CGImage *displayIcon; // @synthesize displayIcon;
@property(nonatomic) long long selectionReason; // @synthesize selectionReason;
@property(nonatomic) _Bool suggestion; // @synthesize suggestion=isSuggestion;
- (_Bool)isSuggestion;	// IMP=0x001000000047a770
@property(nonatomic) _Bool disabled; // @synthesize disabled=isDisabled;
- (_Bool)isDisabled;	// IMP=0x001000000047a740
@property(nonatomic) _Bool classroom; // @synthesize classroom=isClassroom;
- (_Bool)isClassroom;	// IMP=0x001000000047a710
@property(nonatomic, copy) NSString *transportBundleID;
@property(nonatomic, retain) NSNumber *suggestionIndex; // @synthesize suggestionIndex;
- (id);	// IMP=0x001000000047a620
@property(nonatomic, copy) NSSet *formattedHandles;
@property(nonatomic, copy) NSString *model;
@property(nonatomic, copy) NSString *realName;
@property(nonatomic, copy) NSString *displayName;
@property(nonatomic, copy) NSString *contactIdentifier;
@property(nonatomic, copy) NSUUID *nodeIdentifier;

@end

