//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC16DaemoniOSLibrary20SDTempPairingService : _TtCs12_SwiftObject
{
    MISSING_TYPE *subService;	// 0 = 0x0
    MISSING_TYPE *queue;	// 16 = 0x10
    MISSING_TYPE *receiverStateUpdates;	// 0 = 0x0
    MISSING_TYPE *senderStateUpdates;	// 0 = 0x0
    MISSING_TYPE *receiverStateUpdateSequence;	// 0 = 0x0
    MISSING_TYPE *senderStateUpdateSequence;	// 0 = 0x0
    MISSING_TYPE *server;	// 0 = 0x0
    MISSING_TYPE *client;	// 0 = 0x0
}

- (void)handleRapportIdentitiesChanged;	// IMP=0x0040000000330a50

@end

