//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtCC16DaemoniOSLibrary25SDAirDropSendStateMachine10BaseRunner : NSObject
{
    MISSING_TYPE *endpoints;	// 8 = 0x8
    MISSING_TYPE *deviceStatus;	// 16 = 0x10
    MISSING_TYPE *sendRequest;	// 0 = 0x0
    MISSING_TYPE *currentTransfer;	// 2147484672 = 0x80000400
    MISSING_TYPE *subject;	// 0 = 0x0
    MISSING_TYPE *yield;	// 1953718111 = 0x74735f5f
    MISSING_TYPE *queue;	// 0 = 0x0
    MISSING_TYPE *log;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *urls;	// 0 = 0x0
    MISSING_TYPE *hapticsManager;	// 5087634 = 0x4da192
    MISSING_TYPE *mediaConversionDestinations;	// 11640 = 0x2d78
    MISSING_TYPE *osTransaction;	// 0 = 0x0
    MISSING_TYPE *powerAssertion;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x00400000002b2700
- (id)init;	// IMP=0x00100000002b26a0

@end

