//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIActivity.h>

@class NSMutableArray, NSString;

@interface SDAirDropActivity : UIActivity
{
    NSString *_sendingAppBundleID;	// 8 = 0x8
    NSMutableArray *_activeSecurityContexts;	// 16 = 0x10
}

+ (long long)activityCategory;	// IMP=0x00200000000e43f7
- (void).cxx_destruct;	// IMP=0x00200000000e49ae
@property(retain, nonatomic) NSMutableArray *activeSecurityContexts; // @synthesize activeSecurityContexts=_activeSecurityContexts;
@property(retain, nonatomic) NSString *sendingAppBundleID; // @synthesize sendingAppBundleID=_sendingAppBundleID;
- (void)dealloc;	// IMP=0x00100000000e4926
- (void)stopAccessingSecurityScopedResources;	// IMP=0x00100000000e47d6
- (void)startAccessingSecurityScopedResourcesInContext:(id)arg1;	// IMP=0x00100000000e476e
- (void)prepareWithActivityItemData:(id)arg1;	// IMP=0x00100000000e4629
- (_Bool)_allowsAutoCancelOnDismiss;	// IMP=0x00100000000e4621
- (struct CGSize)_thumbnailSize;	// IMP=0x00100000000e4402
- (id)activityType;	// IMP=0x00100000000e43e3
- (_Bool)ss_shouldDismissHostsPresentationBeforePerforming;	// IMP=0x00100000000e43db
- (_Bool)ss_shouldExecuteInShareSheet;	// IMP=0x00100000000e43d3
- (id)init;	// IMP=0x00100000000e4366

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

