//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface SDAutoUnlockDecryptionFailed : PBCodable
{
    unsigned int _errorCode;	// 8 = 0x8
    unsigned int _version;	// 12 = 0xc
    CDStruct_8b9b3261 _has;	// 16 = 0x10
}

@property(nonatomic) unsigned int errorCode; // @synthesize errorCode=_errorCode;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000041397
- (unsigned long long)hash;	// IMP=0x0010000000041353
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000412a0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000041223
- (void)copyTo:(id)arg1;	// IMP=0x00100000000411c9
- (void)writeTo:(id)arg1;	// IMP=0x0010000000041156
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000041149
- (id)dictionaryRepresentation;	// IMP=0x0010000000040e09
- (id)description;	// IMP=0x0010000000040d5a
@property(nonatomic) _Bool hasErrorCode;
@property(nonatomic) _Bool hasVersion;

@end

