//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface SDShareSheetAirDropTransferUpdate : NSObject
{
    MISSING_TYPE *sessionID;	// 8 = 0x8
    MISSING_TYPE *realName;	// 24 = 0x18
    MISSING_TYPE *state;	// 40 = 0x28
    MISSING_TYPE *progress;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x004000000047a340
- (id)init;	// IMP=0x001000000047a310
- (id)initWithSessionID:(id)arg1 realName:(id)arg2;	// IMP=0x001000000047a270
@property(nonatomic) double progress; // @synthesize progress;
@property(nonatomic) long long state; // @synthesize state;
@property(nonatomic, readonly) NSString *realName;
@property(nonatomic, readonly) NSString *sessionID;

@end

