//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData, NSString;

@interface SDUnlockLongTermKeyResponse : PBCodable
{
    NSData *_longTermKey;	// 8 = 0x8
    NSString *_requestID;	// 16 = 0x10
    unsigned int _version;	// 24 = 0x18
    _Bool _keyFailed;	// 28 = 0x1c
    struct {
        unsigned int version:1;
        unsigned int keyFailed:1;
    } _has;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000001e054f
@property(nonatomic) _Bool keyFailed; // @synthesize keyFailed=_keyFailed;
@property(retain, nonatomic) NSData *longTermKey; // @synthesize longTermKey=_longTermKey;
@property(retain, nonatomic) NSString *requestID; // @synthesize requestID=_requestID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000001e043e
- (unsigned long long)hash;	// IMP=0x00100000001e0394
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001e0279
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000001e0198
- (void)copyTo:(id)arg1;	// IMP=0x00100000001e00f1
- (void)writeTo:(id)arg1;	// IMP=0x00100000001e0045
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000001e0038
- (id)dictionaryRepresentation;	// IMP=0x00100000001dfc47
- (id)description;	// IMP=0x00100000001dfb98
@property(nonatomic) _Bool hasKeyFailed;
@property(readonly, nonatomic) _Bool hasLongTermKey;
@property(readonly, nonatomic) _Bool hasRequestID;
@property(nonatomic) _Bool hasVersion;

@end

