//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface PDCKFetchRemoteChanges
{
    NSArray *_zoneIDs;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000010175f
- (void)serverDeletedRecordWithID:(id)arg1 type:(id)arg2;	// IMP=0x00100000001013a3
- (_Bool)processPendingSyncUpdatesWithParentRecordIDs:(id)arg1;	// IMP=0x0010000000101082
- (_Bool)processPendingRecord:(id)arg1;	// IMP=0x0010000000101008
- (_Bool)processObject:(id)arg1 andUpdateSyncMetadataForRecord:(id)arg2;	// IMP=0x0010000000100d5f
- (id)objectForCKRecord:(id)arg1;	// IMP=0x0010000000100b9f
- (void)serverChangedRecord:(id)arg1;	// IMP=0x0010000000100370
- (void)fetchChangesInZonesWithZoneIDs:(id)arg1;	// IMP=0x00100000000ff793
- (id)zoneIDsToFetch;	// IMP=0x00100000000ff611
- (void)execute;	// IMP=0x00100000000ff551
- (_Bool)isExpiredSyncTokenError:(id)arg1;	// IMP=0x00100000000ff534

@end

