//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APSConnection, CKContainer, NSOperationQueue, NSString, PDDatabase, PDRetry, PDRing;
@protocol OS_dispatch_queue;

@interface PDOperationsManager : NSObject
{
    NSOperationQueue *_operationQueue;	// 8 = 0x8
    NSOperationQueue *_userInteractiveOperationQueue;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_taskQueue;	// 24 = 0x18
    CKContainer *_cloudContainer;	// 32 = 0x20
    APSConnection *_apsConnection;	// 40 = 0x28
    PDRetry *_bootstrap;	// 48 = 0x30
    PDRetry *_push;	// 56 = 0x38
    PDRetry *_fetch;	// 64 = 0x40
    PDRetry *_loadICloudUser;	// 72 = 0x48
    double _lastActiveTime;	// 80 = 0x50
    _Bool _isLoadingICloudUserID;	// 88 = 0x58
    _Bool _invalidated;	// 89 = 0x59
    PDDatabase *_database;	// 96 = 0x60
    PDRing *_ring;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x002000000013d340
@property(getter=isInvalidated) _Bool invalidated; // @synthesize invalidated=_invalidated;
@property(readonly, nonatomic) PDRing *ring; // @synthesize ring=_ring;
- (void)registerPeriodicTasksOnQueue:(id)arg1;	// IMP=0x001000000013ce63
- (_Bool)isEDUMAID;	// IMP=0x001000000013ce01
- (void)stopListeningToPushNotifications;	// IMP=0x001000000013b7fb
- (void)registerForLockStateChangedDarwinNotification;	// IMP=0x001000000013b660
- (void)registerPushTopics;	// IMP=0x001000000013b34e
- (id)apsConnection;	// IMP=0x001000000013b1a7
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;	// IMP=0x001000000013ab11
- (void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4;	// IMP=0x001000000013aa05
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;	// IMP=0x001000000013a93e
- (id)apsEnvironmentString;	// IMP=0x001000000013a1d2
- (void)loadICloudUserIDIfNeeded;	// IMP=0x0010000000139ac3
- (void)databaseDataChanged:(id)arg1;	// IMP=0x0010000000139a55
- (void)addInteractiveOperation:(id)arg1;	// IMP=0x0010000000139a3f
- (void)addOperation:(id)arg1;	// IMP=0x0010000000139a29
- (void)_addOperation:(id)arg1 onQueue:(id)arg2;	// IMP=0x001000000013979d
- (void)addPriorityOperation:(id)arg1;	// IMP=0x00100000001394c0
- (void)_populateDependencySet:(id)arg1 ofOperation:(id)arg2;	// IMP=0x0010000000139307
- (void)addReportErrorBlockToOperation:(id)arg1;	// IMP=0x0010000000139097
- (id)operationOnQueueWithName:(id)arg1 finishedOK:(_Bool)arg2;	// IMP=0x0010000000138d41
- (id)operationOnQueueWithName:(id)arg1;	// IMP=0x0010000000138d2d
- (id)issueUploadEventsWithDependency:(id)arg1;	// IMP=0x0010000000138b3e
- (id)issueFetchHandoutChangesWithDependency:(id)arg1;	// IMP=0x0010000000138a9c
- (id)issueASMSyncWithDependency:(id)arg1;	// IMP=0x00100000001389fa
- (id)issueASMFetchMissingWithDependency:(id)arg1;	// IMP=0x0010000000138958
- (id)issueFetchFromCKWithDependency:(id)arg1;	// IMP=0x0010000000138873
- (id)issueRegisterWithDependency:(id)arg1;	// IMP=0x00100000001387d1
- (id)issuePushClassChangesWithDependency:(id)arg1;	// IMP=0x001000000013872f
- (id)issueIngestWithDependency:(id)arg1;	// IMP=0x001000000013868d
- (id)issuePushToCKWithDependency:(id)arg1;	// IMP=0x00100000001385a7
- (id)issueCKBootstrapWithDependency:(id)arg1;	// IMP=0x00100000001384a3
- (void)afterBootstrapWithErrorCompletion:(CDUnknownBlockType)arg1 do:(CDUnknownBlockType)arg2;	// IMP=0x001000000013775c
- (void)afterBootstrapWithErrorCompletion:(CDUnknownBlockType)arg1 doBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000001375b3
- (void)addCompletion:(CDUnknownBlockType)arg1 toOperation:(id)arg2;	// IMP=0x0010000000136aa6
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000001368b5
- (void)dealloc;	// IMP=0x00100000001367e5
- (id)cloudContainer;	// IMP=0x00100000001367d7
- (void)registerCloudContainer;	// IMP=0x00100000001363b1
- (id)init;	// IMP=0x0010000000135ff9

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

