//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC7idcredd20PayloadProtectionKey
{
    MISSING_TYPE *key;	// 0 = 0x0
    MISSING_TYPE *publicKeyIdentifier;	// 25 = 0x19
}

@end

