//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreSpeechFoundation/CSEventMonitor.h>

@interface CSAlwaysOnProcessorStateMonitor : CSEventMonitor
{
    _Bool _isListeningEnabled;	// 8 = 0x8
    int _notifyToken;	// 12 = 0xc
}

+ (id)sharedInstance;	// IMP=0x00400000000dd344
- (_Bool)isEnabled;	// IMP=0x00200000000dcecf
- (void)_notifyObserver:(id)arg1 withEnabled:(_Bool)arg2;	// IMP=0x00100000000dce65
- (void)_didReceiveAOPListeningStateChange:(_Bool)arg1;	// IMP=0x00100000000dcd84
- (void)_stopMonitoring;	// IMP=0x00100000000dccd1
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x00000000000dcc0d
- (id)init;	// IMP=0x00100000000dcbc0

@end

