//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSAttSiriSpeechRecognitionNode, CSAttSiriTCUGenerator, CSConnectionListener, NSString;

@interface CSAttSiriBridgeMessageHandler : NSObject
{
    _Bool _supportTCU;	// 8 = 0x8
    CSAttSiriSpeechRecognitionNode *_speechRecognitionNode;	// 16 = 0x10
    CSAttSiriTCUGenerator *_tcuGenerator;	// 24 = 0x18
    CSConnectionListener *_localSRBridgeListener;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000014a286
@property(retain, nonatomic) CSConnectionListener *localSRBridgeListener; // @synthesize localSRBridgeListener=_localSRBridgeListener;
@property(nonatomic) _Bool supportTCU; // @synthesize supportTCU=_supportTCU;
@property(retain, nonatomic) CSAttSiriTCUGenerator *tcuGenerator; // @synthesize tcuGenerator=_tcuGenerator;
@property(retain, nonatomic) CSAttSiriSpeechRecognitionNode *speechRecognitionNode; // @synthesize speechRecognitionNode=_speechRecognitionNode;
- (void)assetUpdatedRequired;	// IMP=0x001000000014a161
- (void)attSiriNode:(id)arg1 didDetectStartpointAtTime:(double)arg2;	// IMP=0x001000000014a15b
- (void)attSiriNode:(id)arg1 didDetectEndpointEventAtTime:(double)arg2 eventType:(long long)arg3 withMetrics:(id)arg4 useEndpointerSignal:(_Bool)arg5;	// IMP=0x0010000000149ffc
- (void)attSiriNode:(id)arg1 didDetectHardEndpointAtTime:(double)arg2 withMetrics:(id)arg3 usesAutomaticEndPointing:(_Bool)arg4;	// IMP=0x0010000000149ff6
- (void)didGenerateContinuityEnd:(id)arg1;	// IMP=0x0010000000149ec4
- (void)didGenerateTRPDetector:(id)arg1;	// IMP=0x0010000000149d92
- (void)didGenerateTRPCandidatePackage:(id)arg1;	// IMP=0x0010000000149c60
- (void)didCompleteRecognitionTaskWithStatistics:(id)arg1 requestId:(id)arg2 endpointMode:(long long)arg3 error:(id)arg4;	// IMP=0x0010000000149aa9
- (void)didReceivePartialResultPackageWithRequestId:(id)arg1 language:(id)arg2 package:(id)arg3 metadata:(id)arg4;	// IMP=0x00100000001498aa
- (void)didReceivePartialResultWithRequestId:(id)arg1 language:(id)arg2 tokens:(id)arg3 metadata:(id)arg4;	// IMP=0x00100000001496ab
- (void)didReceivePartialResultWithRequestId:(id)arg1 language:(id)arg2 tokens:(id)arg3;	// IMP=0x001000000014950b
- (void)didReceiveFinalResultWithRequestId:(id)arg1 speechPackage:(id)arg2 metadata:(id)arg3 taskName:(id)arg4;	// IMP=0x001000000014932b
- (void)didReceiveFinalResultWithRequestId:(id)arg1 speechPackage:(id)arg2 taskName:(id)arg3;	// IMP=0x001000000014919c
- (void)didReceiveFinalResultCandidateWithRequestId:(id)arg1 speechPackage:(id)arg2;	// IMP=0x0010000000149032
- (void)didReceiveVoiceCommandCandidateWithRequestId:(id)arg1 speechPackage:(id)arg2 metadata:(id)arg3;	// IMP=0x0010000000148e9d
- (void)didReceiveResultCandidateWithRequestId:(id)arg1 rcId:(unsigned long long)arg2 speechPackage:(id)arg3 duration:(double)arg4 metadata:(id)arg5 taskName:(id)arg6;	// IMP=0x0010000000148cb9
- (void)didReceiveResultCandidateWithRequestId:(id)arg1 rcId:(unsigned long long)arg2 inputOrigin:(id)arg3 speechPackage:(id)arg4 duration:(double)arg5 taskName:(id)arg6;	// IMP=0x0010000000148a2e
- (oneway void)sendSpeechCorrectionInfo:(id)arg1 interactionIdentifier:(id)arg2;	// IMP=0x0010000000148944
- (oneway void)resetCacheAndCompileAllAssets;	// IMP=0x00100000001488ad
- (oneway void)resumeLocalRecognitionWithRequestId:(id)arg1 prefixText:(id)arg2 postfixText:(id)arg3 selectedText:(id)arg4;	// IMP=0x001000000014877c
- (oneway void)pauseLocalSpeechRecognitionForRequestId:(id)arg1;	// IMP=0x00100000001486be
- (oneway void)disableLocalSpeechRecognitionForRequestId:(id)arg1;	// IMP=0x0010000000148600
- (oneway void)stopSpeechRecognitionWithReason:(unsigned long long)arg1 requestId:(id)arg2;	// IMP=0x00100000001485ea
- (oneway void)startSpeechRecognitionResultsWithSettings:(id)arg1;	// IMP=0x00100000001485d4
- (oneway void)preheatLocalSpeechRecognitionWithLanguage:(id)arg1 source:(unsigned long long)arg2;	// IMP=0x00100000001484fc
- (oneway void)updateTCUState:(id)arg1;	// IMP=0x001000000014843e
- (id)initWithSpeechRecognitionNode:(id)arg1 tcuGenerator:(id)arg2 supportTCU:(_Bool)arg3;	// IMP=0x001000000014839b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

