//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreSpeechFoundation/CSEventMonitor.h>

@class NSObject;
@protocol OS_dispatch_queue;

@interface CSSiriInCallEnabledMonitor : CSEventMonitor
{
    int _notifyToken;	// 8 = 0x8
    _Bool _isEnabled;	// 12 = 0xc
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x004000000011b7f8
- (void).cxx_destruct;	// IMP=0x002000000011b6a6
- (void)_siriInCallEnabledDidChangeEnabledDidChange;	// IMP=0x001000000011b654
- (_Bool)_checkSiriInCallEnabled;	// IMP=0x001000000011b5c1
- (_Bool)isEnabled;	// IMP=0x001000000011b5b1
- (void)_notifyObserver:(id)arg1 withEnabled:(_Bool)arg2;	// IMP=0x001000000011b59f
- (void)_didReceiveSiriInCallChangedInQueue:(_Bool)arg1;	// IMP=0x001000000011b54d
- (void)_stopMonitoring;	// IMP=0x001000000011b4a2
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x001000000011b3cf
- (id)init;	// IMP=0x001000000011b32c

@end

