//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSPushHandler, NSMutableDictionary;

@interface IDSValidationQueue : NSObject
{
    _Bool _shouldUseAbsinthe;	// 8 = 0x8
    CDUnknownBlockType _validationMessageSendBlock;	// 16 = 0x10
    IDSPushHandler *_pushHandler;	// 24 = 0x18
    NSMutableDictionary *_validationInfoByMechanism;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000348f12
@property(retain, nonatomic) NSMutableDictionary *validationInfoByMechanism; // @synthesize validationInfoByMechanism=_validationInfoByMechanism;
@property(nonatomic) _Bool shouldUseAbsinthe; // @synthesize shouldUseAbsinthe=_shouldUseAbsinthe;
@property(retain, nonatomic) IDSPushHandler *pushHandler; // @synthesize pushHandler=_pushHandler;
@property(copy, nonatomic) CDUnknownBlockType validationMessageSendBlock; // @synthesize validationMessageSendBlock=_validationMessageSendBlock;
- (CDUnknownBlockType);	// IMP=0x0010000000348eb1
- (id)_validationInfoForSubsystem:(long long)arg1 createIfNil:(_Bool)arg2;	// IMP=0x0010000000348d8c
- (long long)_mechanismForSubsystem:(long long)arg1;	// IMP=0x0010000000348d84
- (void)_sendAbsintheValidationCertRequestIfNeededForSubsystem:(long long)arg1;	// IMP=0x0010000000348d7e
- (void)_sendBAAValidationRequestIfNeededForSubsystem:(long long)arg1;	// IMP=0x0010000000348d78
- (void)_sendValidationRequestForSubsystem:(long long)arg1;	// IMP=0x0010000000348d2b
- (void)__purgeCachedCertsForSubsystemMechanism:(long long)arg1;	// IMP=0x0010000000348d25
- (void)__cleanupValidationInfoForSubsystemMechanism:(long long)arg1;	// IMP=0x0010000000348d1f
- (void)__flushValidationQueueForSubsystemMechanism:(long long)arg1;	// IMP=0x0010000000348d19
- (void)__failValidationQueueWithErrorResponseCode:(long long)arg1 forSubsystemMechanism:(long long)arg2;	// IMP=0x0010000000348d13
- (void)__failValidationQueueForSubsystemMechanism:(long long)arg1;	// IMP=0x0010000000348cf9
- (void)__queueValidationMessage:(id)arg1 subsystem:(long long)arg2 sendBlock:(CDUnknownBlockType)arg3;	// IMP=0x0010000000348cf3
- (void)__removeFromQueue:(id)arg1 subsystem:(long long)arg2;	// IMP=0x0010000000348c25
- (_Bool)isBuildingContextForSubsystem:(long long)arg1;	// IMP=0x0010000000348bdf
- (void)buildValidationCredentialsIfNeededForSubsystem:(long long)arg1;	// IMP=0x0010000000348bd9
- (void)queueBuildingValidationDataIfNecessaryForMessage:(id)arg1 subsystem:(long long)arg2 withQueueCompletion:(CDUnknownBlockType)arg3 sendBlock:(CDUnknownBlockType)arg4;	// IMP=0x0010000000348a74
- (void)clearQueueForSubsystem:(long long)arg1;	// IMP=0x00100000003488dd
- (void)removeFromQueue:(id)arg1 subsystem:(long long)arg2;	// IMP=0x00100000003488cb
- (void)purgeCachedCertsForSubsystemMechanism:(long long)arg1;	// IMP=0x00100000003488b9
- (void)cleanupValidationInfoForSubsystemMechanism:(long long)arg1;	// IMP=0x00100000003488a7
- (id)initWithPushHandler:(id)arg1 validationMessageSendBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000003487e5
- (id)initWithValidationMessageSendBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000348764

@end

