//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSString, NSURL, UIColor, UIView, UIViewController;
@protocol SBUISystemApertureAccessoryView, SBUISystemApertureElement;

@interface _TtC10ClockAngel30AlarmApertureElementController
{
    MISSING_TYPE *observerId;	// 8 = 0x8
    MISSING_TYPE *sessionId;	// 24 = 0x18
    MISSING_TYPE *presentationBehaviors;	// 40 = 0x28
    MISSING_TYPE *activeConstraints;	// 48 = 0x30
    MISSING_TYPE *compressedSnoozeTrailingHost;	// 56 = 0x38
    MISSING_TYPE *compressedSnoozeLeadingHost;	// 64 = 0x40
    MISSING_TYPE *activeLayoutMode;	// 72 = 0x48
    MISSING_TYPE *contentRole;	// 80 = 0x50
    MISSING_TYPE *preferredLayoutMode;	// 88 = 0x58
    MISSING_TYPE *maximumLayoutMode;	// 96 = 0x60
    MISSING_TYPE *launchURL;	// 25 = 0x19
    MISSING_TYPE *associatedAppBundleIdentifier;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *timerObserverIdentifier;	// 0 = 0x0
    MISSING_TYPE *elementIdentifier;	// 0 = 0x0
    MISSING_TYPE *preventsInteractiveDismissal;	// 499712 = 0x7a000
    MISSING_TYPE *leadingView;	// 0 = 0x0
    MISSING_TYPE *trailingView;	// 499712 = 0x7a000
    MISSING_TYPE *minimalView;	// 5 = 0x5
    MISSING_TYPE *keyColor;	// 23 = 0x17
    MISSING_TYPE *alarmAlertLeadingHost;	// 1702125407 = 0x65745f5f
    MISSING_TYPE *alarmAlertTrailingHost;	// 0 = 0x0
    MISSING_TYPE *alarmSnoozeExpandedHostLeading;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *alarmSnoozeExpandedHostTrailing;	// 0 = 0x0
    MISSING_TYPE *horizontalPadding;	// 10784 = 0x2a20
    MISSING_TYPE *verticalPadding;	// 374420 = 0x5b694
    MISSING_TYPE *buttonSize;	// 10784 = 0x2a20
    MISSING_TYPE *expandedControlsHeight;	// 0 = 0x0
    MISSING_TYPE *voiceOverTimer;	// 2147484672 = 0x80000400
}

- (void).cxx_destruct;	// IMP=0x0040000000019650
- (id)init;	// IMP=0x001000000001e3b0
- (void)collapse;	// IMP=0x001000000001ce50
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x001000000001c6a0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000019ac0
- (void)dealloc;	// IMP=0x0010000000019630
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00100000000194c0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000018f80
- (void)viewDidLoad;	// IMP=0x0010000000018580
@property(nonatomic, readonly) UIColor *keyColor; // @synthesize keyColor;
@property(nonatomic, readonly) UIView<SBUISystemApertureAccessoryView> *minimalView; // @synthesize minimalView;
@property(nonatomic, readonly) UIView<SBUISystemApertureAccessoryView> *trailingView; // @synthesize trailingView;
@property(nonatomic, readonly) UIView<SBUISystemApertureAccessoryView> *leadingView; // @synthesize leadingView;
@property(nonatomic) _Bool preventsInteractiveDismissal; // @synthesize preventsInteractiveDismissal;
@property(nonatomic, copy) NSString *elementIdentifier;
@property(nonatomic, copy) NSString *associatedAppBundleIdentifier;
@property(nonatomic, copy) NSURL *launchURL;
@property(nonatomic, readonly) double preferredHeightForBottomSafeArea;
@property(nonatomic) long long maximumLayoutMode; // @synthesize maximumLayoutMode;
@property(nonatomic) long long preferredLayoutMode; // @synthesize preferredLayoutMode;
@property(nonatomic) long long contentRole; // @synthesize contentRole;
@property(nonatomic) long long activeLayoutMode; // @synthesize activeLayoutMode;
@property(nonatomic) unsigned long long presentationBehaviors; // @synthesize presentationBehaviors;
@property(nonatomic, readonly) UIViewController<SBUISystemApertureElement> *systemApertureElementViewController;

@end

