//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CreditAccountMergeSummary
{
}

+ (id)_propertySettersForCreditAccountMergeSummary;	// IMP=0x0040000000224081
+ (id)_propertyValuesForCreditAccountMergeSummary:(id)arg1;	// IMP=0x0010000000223f80
+ (id)_predicateForAccountSummaryPID:(id)arg1;	// IMP=0x0010000000223f5d
+ (_Bool)deleteCreditAccountMergeSummaryForCreditAccountSummaryPID:(id)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000223c57
+ (id)creditAccountMergeSummaryForCreditAccountSummaryPID:(id)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000223bfe
+ (id)anyInDatabase:(id)arg1 forCreditAccountSummaryPID:(id)arg2;	// IMP=0x0010000000223b72
+ (id)insertOrUpdateCreditAccountMergeSummary:(id)arg1 forCreditAccountSummaryPID:(id)arg2 inDatabase:(id)arg3;	// IMP=0x00100000002237f3
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x00100000002237c4
+ (id)databaseTable;	// IMP=0x00100000002237b7
- (id)creditAccountMergeSummary;	// IMP=0x0040000000223d5a
- (_Bool)deleteFromDatabase;	// IMP=0x0010000000223ca4
- (void)updateWithCreditAccountMergeSummary:(id)arg1;	// IMP=0x0010000000223a58
- (id)initWithCreditAccountMergeSummary:(id)arg1 forCreditAccountSummaryPID:(id)arg2 inDatabase:(id)arg3;	// IMP=0x00100000002238c4

@end

