//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CreditAccountStatement
{
}

+ (id)_propertySettersForCreditAccountStatement;	// IMP=0x0040000000193ef3
+ (id)_predicateForAccountIdentifiers:(id)arg1;	// IMP=0x0010000000193ed0
+ (id)_predicateForAccountIdentifier:(id)arg1;	// IMP=0x0010000000193ead
+ (id)_predicateForEventPID:(long long)arg1;	// IMP=0x0010000000193e3c
+ (id)_predicateForCreditAccountSummaryPID:(long long)arg1;	// IMP=0x0010000000193dcb
+ (id)_predicateForIdentifier:(id)arg1;	// IMP=0x0010000000193da8
+ (void)updateCreditAccountStatement:(id)arg1 forCreditAccountSummaryPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x001000000019343c
+ (void)deleteCreditAccountStatementsForAccount:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001933a3
+ (id)creditAccountStatementWithIdentifier:(id)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000193317
+ (id)creditAccountStatementsWithIdentifier:(id)arg1 withAccountIdentifiers:(id)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000193059
+ (id)creditAccountStatementsWithIdentifier:(id)arg1 withAccountIdentifier:(id)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000192fae
+ (id)insertCreditAccountStatement:(id)arg1 withAccountIdentifier:(id)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000192d43
+ (id)creditAccountStatementsForAccountIdentifier:(id)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000192b2c
+ (id)creditAccountStatementsWithEventPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000192915
+ (void)deleteCreditAccountStatementForEventPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001927a3
+ (id)insertCreditAccountStatement:(id)arg1 forEventPID:(long long)arg2 withAccountIdentifier:(id)arg3 inDatabase:(id)arg4;	// IMP=0x00100000001924df
+ (id)creditAccountStatementForCreditAccountSummaryPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000192435
+ (void)deleteCreditAccountStatementForCreditAccountSummaryPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x001000000019239c
+ (id)insertCreditAccountStatement:(id)arg1 forCreditAccountSummaryPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x001000000019231f
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x00100000001917c7
+ (id)databaseTable;	// IMP=0x00100000001917ba
- (id)closingDate;	// IMP=0x0040000000194b12
- (id)openingDate;	// IMP=0x0010000000194ac4
- (id)creditAccountStatement;	// IMP=0x0010000000194955
- (void)updateWithCreditAccountStatement:(id)arg1;	// IMP=0x001000000019352e
- (_Bool)deleteFromDatabase;	// IMP=0x001000000019283c
- (void)populateDictionary:(id)arg1 forStatement:(id)arg2;	// IMP=0x0010000000191b00
- (id)initWithCreditAccountStatement:(id)arg1 withAccountIdentifier:(id)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000191a23
- (id)initWithCreditAccountStatement:(id)arg1 forEventPID:(long long)arg2 withAccountIdentifier:(id)arg3 inDatabase:(id)arg4;	// IMP=0x0010000000191903
- (id)initWithCreditAccountStatement:(id)arg1 forCreditAccountSummaryPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000191810

@end

