//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PDPeerPaymentNeedsVerificationUserNotification
{
}

- (id)_peerPaymentApplicationMessageContentWithTitleText:(id)arg1 messageText:(id)arg2;	// IMP=0x0040000000286d42
- (id)_peerPaymentNeedsVerificationGroupDescriptor;	// IMP=0x0010000000286ce6
- (id)applicationMessageContent;	// IMP=0x0010000000286c5c
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x0010000000286b5f
- (unsigned long long)notificationType;	// IMP=0x0010000000286b54
- (id);	// IMP=0x0010000000286a8f

@end

