//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface PDRequestPassesResult : NSObject
{
    NSArray *_passesData;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000002e450c
@property(readonly, nonatomic) NSArray *passesData; // @synthesize passesData=_passesData;
- (id)initWithPassesData:(id)arg1;	// IMP=0x00100000002e4497

@end

