//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class PKPaymentPass, PKPaymentSafariCredential;

@interface PDSafariCredentialEligibilityCredentialPassPair : NSObject
{
    PKPaymentSafariCredential *_credential;	// 8 = 0x8
    PKPaymentPass *_paymentPass;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000073146
@property(retain, nonatomic) PKPaymentPass *paymentPass; // @synthesize paymentPass=_paymentPass;
@property(retain, nonatomic) PKPaymentSafariCredential *credential; // @synthesize credential=_credential;
- (id)initWithCredential:(id)arg1 paymentPass:(id)arg2;	// IMP=0x0010000000073077

@end

