//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSCountedSet, NSOperationQueue, NSSet, NSString, NSURL;
@protocol OS_dispatch_queue, PDUbiquityManagerDelegate;

@interface PDUbiquityManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_accessQueue;	// 16 = 0x10
    NSOperationQueue *_operationQueue;	// 24 = 0x18
    NSCountedSet *_filesModified;	// 32 = 0x20
    NSCountedSet *_filesToWrite;	// 40 = 0x28
    NSCountedSet *_filesToDelete;	// 48 = 0x30
    _Atomic _Bool _canStart;	// 56 = 0x38
    _Atomic int _ubiquityState;	// 60 = 0x3c
    _Atomic unsigned int _ubiquityStartToken;	// 64 = 0x40
    _Bool _addedToFilePresenter;	// 68 = 0x44
    id <PDUbiquityManagerDelegate> _delegate;	// 72 = 0x48
    NSURL *_ubiquitousURL;	// 80 = 0x50
}

+ (void);	// IMP=0x00200000001f0928
- (void).cxx_destruct;	// IMP=0x00200000001f78a7
@property(retain) NSURL *ubiquitousURL; // @synthesize ubiquitousURL=_ubiquitousURL;
@property(nonatomic) __weak id <PDUbiquityManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned long long)lastPresentedItemEventIdentifier;	// IMP=0x00100000001f7853
- (void)setLastPresentedItemEventIdentifier:(unsigned long long)arg1;	// IMP=0x00100000001f77fd
- (void)accommodatePresentedSubitemDeletionAtURL:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000001f76c8
- (void)presentedSubitemDidAppearAtURL:(id)arg1;	// IMP=0x00100000001f74de
- (void)presentedSubitemDidChangeAtURL:(id)arg1;	// IMP=0x00100000001f6e3c
- (void)presentedItemDidMoveToURL:(id)arg1;	// IMP=0x00100000001f6d6e
- (void)presentedItemDidGainVersion:(id)arg1;	// IMP=0x00100000001f6c4c
@property(readonly, retain) NSOperationQueue *presentedItemOperationQueue;
@property(readonly, copy) NSURL *presentedItemURL;
- (void)_queue_resolveURLIfNecessary:(id)arg1 fileCoordinator:(id)arg2;	// IMP=0x00100000001f65a2
- (void)_queue_resolveURLIfNecessary:(id)arg1;	// IMP=0x00100000001f6530
- (void)_queue_addedToFilePresenter;	// IMP=0x00100000001f60c8
- (void)_queue_removeFromFilePresenter;	// IMP=0x00100000001f6097
- (void)_queue_addToFilePresenter;	// IMP=0x00100000001f5ff6
- (void)_queue_copyCatalogToUbiquity:(id)arg1;	// IMP=0x00100000001f5de6
- (void)_queue_copyCatalogToLocalStore:(id)arg1;	// IMP=0x00100000001f5c70
- (void)_queue_handleCatalogUpdate;	// IMP=0x00100000001f5ae5
- (void)_queue_handlePassUpdate:(id)arg1;	// IMP=0x00100000001f526e
- (void)_queue_compareCatalogsAndTakeNewerVersion;	// IMP=0x00100000001f4e57
- (void)_queue_comparePassesAndTakeNewerVersion:(id)arg1;	// IMP=0x00100000001f46de
- (void)_queue_copyPassesFromLocalStoreToUbiquity:(id)arg1;	// IMP=0x00100000001f42e4
- (void)_queue_copyPassesFromUbiquityToLocalStore:(id)arg1;	// IMP=0x00100000001f3d81
- (id)_queue_passUniqueIDs;	// IMP=0x00100000001f376b
- (void)_queue_mergeUbiquityWithLocalStore;	// IMP=0x00100000001f34ba
- (void)_queue_startWithTokenFinishedWithFinalState:(int)arg1;	// IMP=0x00100000001f3340
- (_Bool)_queue_startNotYetUbiquitousWithDestinationURL:(id)arg1;	// IMP=0x00100000001f2ea7
- (void)_queue_startAlreadyUbiquitous;	// IMP=0x00100000001f293a
- (void)_attemptCoordinatedReadWithoutChangesAtURL:(id)arg1 withAccessor:(CDUnknownBlockType)arg2;	// IMP=0x00100000001f2685
- (id)_urlForCatalogRelativeToDirectoryURL:(id)arg1;	// IMP=0x00100000001f2667
- (id)_urlForCardWithUniqueID:(id)arg1 relativeToDirectoryURL:(id)arg2;	// IMP=0x00100000001f2601
- (void)_handleUbiquityIdentityChanged:(id)arg1;	// IMP=0x00100000001f2586
- (void)updateUbiquitousCatalog:(id)arg1;	// IMP=0x00100000001f2284
- (void)removeUbiquitousPassWithUniqueID:(id)arg1 completed:(_Bool)arg2;	// IMP=0x00100000001f1d5a
- (void)prepareToRemoveUbiquitousPassWithUniqueID:(id)arg1;	// IMP=0x00100000001f1cae
- (_Bool)passWillBeDeleted:(id)arg1;	// IMP=0x00100000001f1ba0
- (void)updateUbiquitousPass:(id)arg1;	// IMP=0x00100000001f1120
- (void)restart;	// IMP=0x00100000001f108a
- (void)_startWithToken:(unsigned int)arg1;	// IMP=0x00100000001f09bb
- (void)start;	// IMP=0x00100000001f0998
- (void)dealloc;	// IMP=0x00100000001f0884
- (id)initWithDelegate:(id)arg1;	// IMP=0x00100000001f06d2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSSet *observedPresentedItemUbiquityAttributes;
@property(readonly, copy) NSURL *primaryPresentedItemURL;
@property(readonly) Class superclass;

@end

