//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PushProvisioningSharingMetadata
{
}

+ (id)_propertySettersForProvisioningSharingMetadata;	// IMP=0x00400000001b27ff
+ (id)databaseTable;	// IMP=0x00100000001b27f2
+ (id)_predicateForProvisioningSharingStatus:(unsigned long long)arg1;	// IMP=0x00100000001b2781
+ (id)_predicateForProvisioningSharingIdentifier:(id)arg1;	// IMP=0x00100000001b275e
+ (void)deleteAllProvisioningTargetsInDatabase:(id)arg1;	// IMP=0x00100000001b2473
+ (void)deleteSharingMetadata:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001b2328
+ (id)insertOrUpdateSharingMetadata:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001b20e2
+ (id)pushProvisioningSharingMetadataForProvisioningSharingIdentifier:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001b2056
+ (id)pushProvisioningSharingMetadataForStatus:(unsigned long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001b1eac
+ (id)pushProvisioningSharingMetadataInDatabase:(id)arg1;	// IMP=0x00100000001b1d04
- (id)sharingMetaData;	// IMP=0x00400000001b2629
- (void)_updateProvisioningSharingMetadata:(id)arg1;	// IMP=0x00100000001b250d
- (id)initWithSharingMetadata:(id)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001b1b14

@end

