//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class WeekViewController;

@interface PhonePlusWeekViewHorizontalScrollTest
{
    WeekViewController *_controller;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000003393d
@property(readonly, nonatomic) WeekViewController *controller; // @synthesize controller=_controller;
- (id)scrollView;	// IMP=0x001000000003390f
- (void)_setupWeekView;	// IMP=0x0010000000033815
- (void)navigateToScrollView;	// IMP=0x001000000003365d
- (id)checkTestPreconditions;	// IMP=0x0010000000033640

@end

