//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ListViewController, RootNavigationController;

@interface SearchViewLaunchTest
{
    unsigned long long _iterations;	// 8 = 0x8
    _Bool _inputInvalid;	// 16 = 0x10
    RootNavigationController *_rootNavController;	// 24 = 0x18
    ListViewController *_listViewController;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000148365
- (void)_searchViewDidAppear;	// IMP=0x001000000014823f
- (void)runTest;	// IMP=0x0010000000147e6d
- (void)dealloc;	// IMP=0x0010000000147df8
- (id)initWithApplication:(id)arg1 model:(id)arg2 options:(id)arg3;	// IMP=0x0010000000147cbb

@end

