//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class APSConfiguration, APSCourierConnectionManager;
@protocol APSProtocolConnection;

@protocol APSCourierConnectionManagerDelegate <NSObject>
- (_Bool)courierConnectionManagerClientsHaveInteractivePushDuringSleepEnabled;
- (_Bool)courierConnectionManagerClientsWantsCriticalReliability;
- (_Bool)courierConnectionManagerClientsHaveEagerMessages;
- (_Bool)courierConnectionManagerClientsCanConnectRightNow;
- (_Bool)courierConnectionManagerClientsWillBeAbleToConnect;
- (void)courierConnectionManager:(APSCourierConnectionManager *)arg1 receivedServerBag:(APSConfiguration *)arg2;
- (void)courierConnectionManager:(APSCourierConnectionManager *)arg1 openedNewProtocolConnection:(id <APSProtocolConnection>)arg2;
@end

