//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SQLiteDatabase;
@protocol OS_dispatch_queue;

@interface Environment : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    SQLiteDatabase *_userDatabase;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x0040000000085c04
- (void).cxx_destruct;	// IMP=0x0020000000085ed4
@property(readonly) SQLiteDatabase *userDatabase;
- (id)init;	// IMP=0x0010000000085c59

@end

