//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface AKAuthorizationStoreMigrator
{
}

- (void)_createV3Database;	// IMP=0x002000000002478e
- (void)_createV2Database;	// IMP=0x0010000000024760
- (void)_createV1Database;	// IMP=0x001000000002474e
- (void)_upgradeToSchemaVersion4;	// IMP=0x00100000000245e1
- (void)_upgradeToSchemaVersion3;	// IMP=0x00100000000244a4
- (void)_upgradeToSchemaVersion2;	// IMP=0x001000000002433c
- (void)_buildSchemaVersion1;	// IMP=0x0010000000024230
- (void)migrateSchemaFromVersion:(unsigned long long)arg1;	// IMP=0x0010000000024112
- (unsigned long long)currentSchemaVersion;	// IMP=0x0010000000024107
- (id)storeName;	// IMP=0x00100000000240fa

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

