//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface AKSQLiteHelper : NSObject
{
}

+ (id)tableInfoForTable:(id)arg1 withExecutor:(id)arg2;	// IMP=0x00400000000934c3
+ (int)numberOfRowsForTable:(id)arg1 withExecutor:(id)arg2;	// IMP=0x0010000000093326
+ (id)dataFromColumn:(long long)arg1 inStatement:(struct sqlite3_stmt *)arg2;	// IMP=0x00100000000932c7
+ (id)doubleFromColumn:(long long)arg1 inStatement:(struct sqlite3_stmt *)arg2;	// IMP=0x001000000009329a
+ (id)integerFromColumn:(long long)arg1 inStatement:(struct sqlite3_stmt *)arg2;	// IMP=0x001000000009326b
+ (id)stringFromColumn:(long long)arg1 inStatement:(struct sqlite3_stmt *)arg2;	// IMP=0x001000000009322c

@end

