//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SADomainObjectCommit.h>

@class NSString;

@interface SADomainObjectCommit (ADMessagesTransformer)
- (id)_ad_replyCommandValue;	// IMP=0x0020000000117323
- (void)_ad_getMessagesRequestValueWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000011721d
- (_Bool)supportsADSADOCommand;	// IMP=0x00100000002e4a2e
- (id)expectedResponseClassName;	// IMP=0x00100000002e4a1a
- (id)domainFromSADObject;	// IMP=0x00100000002e49ca

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

