//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9Reminders23TTRIRemindersListRouter : _TtCs12_SwiftObject
{
    MISSING_TYPE *viewController;	// 16 = 0x10
    MISSING_TYPE *reminderDetailModuleInterface;	// 24 = 0x18
    MISSING_TYPE *hashtagAssociationModule;	// 40 = 0x28
    MISSING_TYPE *reminderDetailNavigationController;	// 56 = 0x38
    MISSING_TYPE *tipContentPopoverController;	// 64 = 0x40
    MISSING_TYPE *printingCancellable;	// 72 = 0x48
    MISSING_TYPE *activityAlertCapability;	// 80 = 0x50
}

- (void)popPresentedViewController;	// IMP=0x00200000000c5a20

@end

