//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "_$s15RemindersUICore25TTRListAppearanceGridViewCN.h"

@class MISSING_TYPE;

@interface _TtC9Reminders30TTRListAppearanceBadgeGridView : _$s15RemindersUICore25TTRListAppearanceGridViewCN
{
    MISSING_TYPE *delegate;	// 88 = 0x58
    MISSING_TYPE *indexOfSelectedItem;	// 104 = 0x68
}

- (void).cxx_destruct;	// IMP=0x00400000002f4bc0
- (void)didTap:(id)arg1;	// IMP=0x00100000002f4790
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000002f41b0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000002f40b0

@end

