//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface APPBTagTransformation : PBCodable
{
    NSMutableArray *_requiredTags;	// 8 = 0x8
    NSMutableArray *_resultTags;	// 16 = 0x10
}

+ (Class)resultTagsType;	// IMP=0x0020000000071aeb
+ (Class)requiredTagsType;	// IMP=0x0010000000071a19
+ (id)options;	// IMP=0x0010000000071908
- (void).cxx_destruct;	// IMP=0x00200000000727e2
@property(retain, nonatomic) NSMutableArray *resultTags; // @synthesize resultTags=_resultTags;
@property(retain, nonatomic) NSMutableArray *requiredTags; // @synthesize requiredTags=_requiredTags;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000007254e
- (unsigned long long)hash;	// IMP=0x0010000000072501
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000072449
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000072149
- (void)copyTo:(id)arg1;	// IMP=0x0010000000071ff3
- (void)writeTo:(id)arg1;	// IMP=0x0010000000071ddc
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000071dcf
- (id)dictionaryRepresentation;	// IMP=0x0010000000071bab
- (id)description;	// IMP=0x0010000000071afc
- (id)resultTagsAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000071ace
- (unsigned long long)resultTagsCount;	// IMP=0x0010000000071ab1
- (void)addResultTags:(id)arg1;	// IMP=0x0010000000071a47
- (void)clearResultTags;	// IMP=0x0010000000071a2a
- (id)requiredTagsAtIndex:(unsigned long long)arg1;	// IMP=0x00100000000719fc
- (unsigned long long)requiredTagsCount;	// IMP=0x00100000000719df
- (void)addRequiredTags:(id)arg1;	// IMP=0x0010000000071975
- (void)clearRequiredTags;	// IMP=0x0010000000071958

@end

