//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MetricsModuleClasses : NSObject
{
}

+ (void)setStorageClass:(Class)arg1;	// IMP=0x00200000000cff09
+ (Class)storageClass;	// IMP=0x00100000000cfeb6
+ (void)setServerDeliveryClass:(Class)arg1;	// IMP=0x00100000000cfd8c
+ (Class)serverDeliveryClass;	// IMP=0x00100000000cfd39
+ (void)setHttpDeliveryClass:(Class)arg1;	// IMP=0x00100000000cfc0f
+ (Class)httpDeliveryClass;	// IMP=0x00100000000cfbbc
+ (void)setRouteClass:(Class)arg1;	// IMP=0x00100000000cfa92
+ (Class)purposeClass;	// IMP=0x00100000000cfa3f
+ (void)setNotificationRegistrarClass:(Class)arg1;	// IMP=0x00100000000cf8b7
+ (Class)notificationRegistrarClass;	// IMP=0x00100000000cf864
+ (void)setBatchClass:(Class)arg1;	// IMP=0x00100000000cf73a
+ (Class)batchClass;	// IMP=0x00100000000cf6e7
+ (void)setMetricClass:(Class)arg1;	// IMP=0x00100000000cf5bd
+ (Class)metricClass;	// IMP=0x00100000000cf56a

@end

