//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSDCallProviderManager, CSDClientManager, NSString;
@protocol OS_dispatch_queue;

@interface CSDCallProviderManagerXPCServer : NSObject
{
    CSDClientManager *_clientManager;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    CSDCallProviderManager *_providerManager;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000007e189
@property(readonly, nonatomic) CSDCallProviderManager *providerManager; // @synthesize providerManager=_providerManager;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) CSDClientManager *clientManager; // @synthesize clientManager=_clientManager;
- (void)providersChangedForProviderManager:(id)arg1;	// IMP=0x001000000007dfb4
- (void)unregisterClient:(id)arg1;	// IMP=0x001000000007deab
- (void)registerClient:(id)arg1;	// IMP=0x001000000007dda2
- (oneway void)launchAppForDialRequest:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000007dc75
- (oneway void)donateUserIntentForProviderWithIdentifier:(id)arg1;	// IMP=0x001000000007db68
- (oneway void)providersByIdentifier:(CDUnknownBlockType)arg1;	// IMP=0x001000000007da42
- (id)pairedHostDeviceProvidersByIdentifierForClient:(id)arg1;	// IMP=0x001000000007d988
- (id)localProvidersByIdentifierForClient:(id)arg1;	// IMP=0x001000000007d8ce
- (id)providersByIdentifierForClient:(id)arg1;	// IMP=0x001000000007d814
- (void)invalidate;	// IMP=0x001000000007d762
- (id)initWithProviderManager:(id)arg1;	// IMP=0x001000000007d1e0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

