//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CSDFaceTimeIDSService
{
}

- (void)account:(id)arg1 aliasesChanged:(id)arg2;	// IMP=0x0040000000029295
- (void)faceTimeIMAccountCallerIDChanged:(id)arg1;	// IMP=0x0010000000029238
- (id)callerID;	// IMP=0x00100000000291e1
- (void)dealloc;	// IMP=0x001000000002916c
- (id)initWithName:(id)arg1;	// IMP=0x00100000000290bf

@end

