//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class CSDMessagingConversationActivity, MISSING_TYPE, NSString, TUConversationActivitySession;

@interface CSDMessagingConversationActivitySession : PBCodable
{
    double _creationDateEpochTime;	// 8 = 0x8
    CSDMessagingConversationActivity *_activity;	// 16 = 0x10
    NSString *_identifierUUIDString;	// 24 = 0x18
    struct {
        unsigned int creationDateEpochTime:1;
    } _has;	// 32 = 0x20
}

+ (id)activitySessionWithCSDConversationActivitySession:(id)arg1 fromConversation:(id)arg2;	// IMP=0x00100000001dc6d9
+ (id)activitySessionWithCSDConversationActivitySession:(id)arg1 fromConversation:(id)arg2 forStorage:(_Bool)arg3;	// IMP=0x00100000001dc537
+ (id)activitySessionWithTUConversationActivitySession:(id)arg1 fromConversation:(id)arg2;	// IMP=0x00100000001dc29e
+ (id)activitySessionWithTUConversationActivitySession:(id)arg1 fromConversation:(id)arg2 forStorage:(_Bool)arg3;	// IMP=0x00100000001dc1e5
- (void).cxx_destruct;	// IMP=0x00100000000d94ad
@property(nonatomic) double creationDateEpochTime; // @synthesize creationDateEpochTime=_creationDateEpochTime;
@property(retain, nonatomic) CSDMessagingConversationActivity *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) NSString *identifierUUIDString; // @synthesize identifierUUIDString=_identifierUUIDString;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000d93b4
- (unsigned long long)hash;	// IMP=0x00100000000d9264
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000d9178
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000d90b6
- (MISSING_TYPE *)copyTo: /* Error: Ran out of types for this method. */;	// IMP=0x00100000000d902f
- (void)writeTo:(id)arg1;	// IMP=0x00100000000d8faa
- (_Bool)readFrom:(id)arg1;	// IMP=0x00100000000d8f9d
- (id)dictionaryRepresentation;	// IMP=0x00100000000d8c52
- (id)description;	// IMP=0x00100000000d8ba3
@property(nonatomic) _Bool hasCreationDateEpochTime;
@property(readonly, nonatomic) _Bool hasActivity;
@property(readonly, nonatomic) _Bool hasIdentifierUUIDString;
- (id)createActivitySessionOnConversation:(id)arg1;	// IMP=0x00100000001dc766
@property(readonly, nonatomic) TUConversationActivitySession *tuConversationActivitySession;

@end

