//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface NFMFindLocallyCAReporter : NSObject
{
}

+ (void)recordPingMyFiredSuccessfully:(_Bool)arg1 wantedTorch:(_Bool)arg2 withDeliveryDuration:(double)arg3;	// IMP=0x004000000000358d
+ (void)sendEvent:(id)arg1 with:(id)arg2;	// IMP=0x00100000000034b6

@end

