//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ASCEmptyOfferMetadata
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x00400000000171e0
- (_Bool)isEmpty;	// IMP=0x004000000001723b
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000171f0
- (unsigned long long)hash;	// IMP=0x00100000000171e8
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000171b1
- (id)init;	// IMP=0x0010000000017182

@end

