//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, NSString;

@interface BCSVisualCodeAppClip
{
    NSString *_payloadString;	// 144 = 0x90
    unsigned long long _codeVersion;	// 152 = 0x98
    NSData *_rawDataPayload;	// 160 = 0xa0
}

- (void).cxx_destruct;	// IMP=0x0020000000010ee7
- (struct CGRect)boundingBox;	// IMP=0x0010000000010e05
- (id)rawPayload;	// IMP=0x0010000000010df0
- (long long)codeType;	// IMP=0x0010000000010de5
- (unsigned long long)codeVersion;	// IMP=0x0010000000010dd4
- (id)payloadString;	// IMP=0x0010000000010dbf
- (id)initWithRawPayload:(id)arg1 version:(unsigned long long)arg2;	// IMP=0x0010000000010d20
- (id)initWithPayloadString:(id)arg1 version:(unsigned long long)arg2;	// IMP=0x0010000000010c81

@end

