//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC12PreviewShellP33_73072BBD51AADBBF8F40B684FE9C377E19ProcessExitObserver : NSObject
{
    MISSING_TYPE *process;	// 8 = 0x8
    MISSING_TYPE *didExitHandler;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0040000000006930
- (id)init;	// IMP=0x00100000000068f0
- (void)processDidExit:(id)arg1;	// IMP=0x00100000000068a0

@end

