//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@interface PUProtoGetPasscodeState : PBCodable
{
}

- (void)mergeFrom:(id)arg1;	// IMP=0x004000000000a138
- (unsigned long long)hash;	// IMP=0x001000000000a130
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000a0ed
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000a0b4
- (void)copyTo:(id)arg1;	// IMP=0x001000000000a0ae
- (void)writeTo:(id)arg1;	// IMP=0x001000000000a0a8
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000a09b
- (id)dictionaryRepresentation;	// IMP=0x0010000000009f87
- (id)description;	// IMP=0x0010000000009ed8

@end

