//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIApplication.h>

@interface _MapsApplication : UIApplication
{
}

- (id)_extendLaunchTest;	// IMP=0x0010000000190eb0
- (void)failedTest:(id)arg1;	// IMP=0x0010000000c65f9b
- (void)finishedTest:(id)arg1 extraResults:(id)arg2;	// IMP=0x0010000000c65ed5

@end

