//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC4Maps19SearchFindMySession : NSObject
{
    MISSING_TYPE *session;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00400000000fa580
- (id)init;	// IMP=0x00100000000fa530

@end

