//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionView.h>

@interface CarCollectionView : UICollectionView
{
}

- (id)accessoryViewAtEdge:(long long)arg1;	// IMP=0x0040000000815005
- (void)setAccessoryView:(id)arg1 atEdge:(long long)arg2;	// IMP=0x0010000000814f9b

@end

