//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AudioPreferences, CarChromeNavigationCameraStyleManager, CarCompressionTestCardViewController, CarETACardViewController, CarGuidanceCardViewController, CarMapTrackingController, CarTrafficAlertCardViewController, CarWaypointsOverviewCardViewController, ChromeViewController, GCDTimer, GEOComposedRoute, GuidanceObserver, NSArray, NSMutableSet, NSString, _TtC4Maps28NavigationWaypointController;

@interface CarNavigationModeController : NSObject
{
    long long _navigationGuidanceSignStyle;	// 8 = 0x8
    _Bool _forceShareButtonHidden;	// 16 = 0x10
    _Bool _hasShownInitialShareETADisclosure;	// 17 = 0x11
    NSMutableSet *_invalidatedAlertIds;	// 24 = 0x18
    _Bool _observingAudioKeys;	// 32 = 0x20
    _Bool _hasUserManuallyReducedAudio;	// 33 = 0x21
    _Bool _isTogglingETACard;	// 34 = 0x22
    _Bool _showingJunctionView;	// 35 = 0x23
    ChromeViewController *_chromeViewController;	// 40 = 0x28
    long long _cameraStyle;	// 48 = 0x30
    long long _navigationModeState;	// 56 = 0x38
    CarGuidanceCardViewController *_guidanceCardController;	// 64 = 0x40
    CarETACardViewController *_etaCardController;	// 72 = 0x48
    CarWaypointsOverviewCardViewController *_waypointsOverviewCardController;	// 80 = 0x50
    CarTrafficAlertCardViewController *_trafficAlertCardController;	// 88 = 0x58
    CarCompressionTestCardViewController *_compressionTestCardController;	// 96 = 0x60
    GEOComposedRoute *_currentRoute;	// 104 = 0x68
    AudioPreferences *_audioPreferences;	// 112 = 0x70
    CarChromeNavigationCameraStyleManager *_cameraStyleManager;	// 120 = 0x78
    GCDTimer *_shareEtaDisclosureAutoDismissTimer;	// 128 = 0x80
}

- (void).cxx_destruct;	// IMP=0x00200000001f851e
@property(retain, nonatomic) GCDTimer *shareEtaDisclosureAutoDismissTimer; // @synthesize shareEtaDisclosureAutoDismissTimer=_shareEtaDisclosureAutoDismissTimer;
@property(retain, nonatomic) CarChromeNavigationCameraStyleManager *cameraStyleManager; // @synthesize cameraStyleManager=_cameraStyleManager;
@property(retain, nonatomic) AudioPreferences *audioPreferences; // @synthesize audioPreferences=_audioPreferences;
@property(nonatomic, getter=isShowingJunctionView) _Bool showingJunctionView; // @synthesize showingJunctionView=_showingJunctionView;
@property(nonatomic) _Bool isTogglingETACard; // @synthesize isTogglingETACard=_isTogglingETACard;
@property(retain, nonatomic) GEOComposedRoute *currentRoute; // @synthesize currentRoute=_currentRoute;
@property(retain, nonatomic) CarCompressionTestCardViewController *compressionTestCardController; // @synthesize compressionTestCardController=_compressionTestCardController;
@property(retain, nonatomic) CarTrafficAlertCardViewController *trafficAlertCardController; // @synthesize trafficAlertCardController=_trafficAlertCardController;
@property(retain, nonatomic) CarWaypointsOverviewCardViewController *waypointsOverviewCardController; // @synthesize waypointsOverviewCardController=_waypointsOverviewCardController;
@property(retain, nonatomic) CarETACardViewController *etaCardController; // @synthesize etaCardController=_etaCardController;
@property(retain, nonatomic) CarGuidanceCardViewController *guidanceCardController; // @synthesize guidanceCardController=_guidanceCardController;
@property(nonatomic) long long navigationModeState; // @synthesize navigationModeState=_navigationModeState;
@property(nonatomic) long long cameraStyle; // @synthesize cameraStyle=_cameraStyle;
@property(nonatomic) __weak ChromeViewController *chromeViewController; // @synthesize chromeViewController=_chromeViewController;
- (void)_maneuverBannerViewEVStationsNotification:(id)arg1;	// IMP=0x00100000001f836f
- (void)carShareETAInfoViewDidInteractWithShareETASuggestionNotification:(id)arg1;	// IMP=0x00100000001f835d
- (void)carShareETAInfoViewDidChangeShareETASuggestionVisibilityNotification:(id)arg1;	// IMP=0x00100000001f82d1
@property(readonly, nonatomic) int currentUsageTarget;
- (void)carChromeNavigationCameraStyleManager:(id)arg1 didChangeCameraStyle:(long long)arg2;	// IMP=0x00100000001f82ac
- (void)chromeNavigationDisplay:(id)arg1 userDidTapMap:(id)arg2 atPoint:(struct CGPoint)arg3;	// IMP=0x00100000001f8265
- (void)chromeNavigationDisplay:(id)arg1 configurationDidChange:(id)arg2;	// IMP=0x00100000001f8219
@property(readonly, nonatomic) NSArray *carFocusOrderSequences;
@property(readonly, nonatomic) NSArray *preferredCarFocusEnvironments;
- (void)compressionTestCardRequestsDismiss:(id)arg1;	// IMP=0x00100000001f7e3a
- (void)compressionTestCard:(id)arg1 reloadWithSpacerHeight:(double)arg2 priority:(float)arg3;	// IMP=0x00100000001f7d49
- (void)_loadCompressionTestCardWithHeight:(double)arg1 priority:(float)arg2;	// IMP=0x00100000001f7c08
- (void)sharedTripService:(id)arg1 didUpdateSharingIdentity:(id)arg2;	// IMP=0x00100000001f7bf1
- (void)sharedTripService:(id)arg1 sharingDidInvalidateWithError:(id)arg2;	// IMP=0x00100000001f7bda
- (void)sharedTripService:(id)arg1 didUpdateReceivers:(id)arg2;	// IMP=0x00100000001f7ad6
- (void)sharedTripServiceDidUpdateSendingAvailability:(id)arg1;	// IMP=0x00100000001f7abf
- (void)trafficAlertCardViewControllerDismiss:(id)arg1;	// IMP=0x00100000001f78c5
- (void)navigationService:(id)arg1 didInvalidateTrafficIncidentAlert:(id)arg2;	// IMP=0x00100000001f77ae
- (void)navigationService:(id)arg1 didUpdateTrafficIncidentAlert:(id)arg2;	// IMP=0x00100000001f760d
- (void)navigationService:(id)arg1 didReceiveTrafficIncidentAlert:(id)arg2 responseCallback:(CDUnknownBlockType)arg3;	// IMP=0x00100000001f74ed
- (void)navigationService:(id)arg1 didUpdateMatchedLocation:(id)arg2;	// IMP=0x00100000001f74b0
- (void)navigationService:(id)arg1 hideJunctionViewForId:(id)arg2;	// IMP=0x00100000001f7477
- (void);	// IMP=0x00100000001f743b
- (void)navigationService:(id)arg1 didChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;	// IMP=0x00100000001f73c3
- (void)navigationService:(id)arg1 didChangeVoiceGuidanceLevel:(unsigned long long)arg2;	// IMP=0x00100000001f7386
- (void)navigationService:(id)arg1 didEnableGuidancePrompts:(_Bool)arg2;	// IMP=0x00100000001f732f
- (void)navigationService:(id)arg1 isApproachingEndOfLeg:(unsigned long long)arg2;	// IMP=0x00100000001f72f2
- (void)navigationService:(id)arg1 didEnterPreArrivalStateForWaypoint:(id)arg2 endOfLegIndex:(unsigned long long)arg3;	// IMP=0x00100000001f72b5
- (void)navigationService:(id)arg1 didResumeNavigatingFromWaypoint:(id)arg2 endOfLegIndex:(unsigned long long)arg3 reason:(unsigned long long)arg4;	// IMP=0x00100000001f7266
- (void)navigationService:(id)arg1 didUpdateTargetLegIndex:(unsigned long long)arg2;	// IMP=0x00100000001f7229
- (void)navigationService:(id)arg1 didUpdateArrivalInfo:(id)arg2;	// IMP=0x00100000001f71dc
- (void)navigationService:(id)arg1 didReroute:(id)arg2 rerouteReason:(unsigned long long)arg3;	// IMP=0x00100000001f71a9
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;	// IMP=0x00100000001f71a3
- (void)mapView:(id)arg1 didBecomePitched:(_Bool)arg2;	// IMP=0x00100000001f719d
- (void)_toggleETACardAnimated:(_Bool)arg1;	// IMP=0x00100000001f6925
- (void)_setupGuidanceDisplays:(_Bool)arg1;	// IMP=0x00100000001f6773
- (_Bool)_shouldShowShareButton;	// IMP=0x00100000001f66b6
- (void)_updateShareETADisclosureAutoDismissTimer;	// IMP=0x00100000001f64f3
- (void)_updateShareButtonContentAndVisibility:(_Bool)arg1;	// IMP=0x00100000001f649f
- (void)waypointsOverviewController:(id)arg1 didSelectWaypoint:(id)arg2 atIndex:(unsigned long long)arg3;	// IMP=0x00100000001f6370
- (void)waypointsOverviewControllerDidSelectAddWaypoint:(id)arg1;	// IMP=0x00100000001f6294
@property(readonly, nonatomic) NSString *arrivalSubtitle;
@property(readonly, nonatomic) NSString *arrivalTitle;
- (void)_sendOtherEVStationsRequest;	// IMP=0x00100000001f5a00
- (void)etaCardSign:(id)arg1 didSelectAction:(unsigned long long)arg2;	// IMP=0x00100000001f5384
- (id)contactSharingSuggestion;	// IMP=0x00100000001f52ef
- (id)sharingButtonTitle;	// IMP=0x00100000001f5081
- (id)upcomingWaypoints;	// IMP=0x00100000001f5031
- (_Bool)isSharingTrip;	// IMP=0x00100000001f4fb8
- (void)_captureUserToggledCameraStyle;	// IMP=0x00100000001f4f43
- (void)_captureCurrentNavigationModeState;	// IMP=0x00100000001f4ea9
- (void)_toggleCameraStyle;	// IMP=0x00100000001f4e51
- (void)refreshCameraTypeAnimated:(_Bool)arg1;	// IMP=0x00100000001f4d34
- (void)endNavigation;	// IMP=0x00100000001f4d1b
- (void)_ppt_notityETATrayUpdateCompleted;	// IMP=0x00100000001f4cf5
- (void)setTrayExpanded:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00100000001f4b8b
- (void)setCameraStyle:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x00100000001f4b1c
- (void)navigationWaypointController:(id)arg1 didUpdateDisplayedWaypoints:(id)arg2;	// IMP=0x00100000001f4a05
- (void)guidanceCardController:(id)arg1 didChangeGuidanceSignStyle:(long long)arg2 userInitiated:(_Bool)arg3;	// IMP=0x00100000001f4139
- (unsigned long long)_upcomingGuidanceLevelForGuidanceSignStyle:(long long)arg1 currentGuidanceLevel:(unsigned long long)arg2;	// IMP=0x00100000001f4115
- (void)audioControlView:(id)arg1 didSelectAudioType:(unsigned long long)arg2;	// IMP=0x00100000001f3fa1
- (unsigned long long)audioSettingsCurrentState;	// IMP=0x00100000001f3e65
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000001f39e8
- (void)toggleCameraPressed;	// IMP=0x00100000001f39d6
- (void)hideAutohidingContentWithAnimation:(id)arg1;	// IMP=0x00100000001f3948
- (void)configureNavigationDisplay:(id)arg1;	// IMP=0x00100000001f38d8
- (void)carCardViewCloseButtonTapped:(id)arg1;	// IMP=0x00100000001f3788
- (void)resignTopContextInChromeViewController:(id)arg1 withAnimation:(id)arg2;	// IMP=0x00100000001f34b6
- (void)becomeTopContextInChromeViewController:(id)arg1 withAnimation:(id)arg2;	// IMP=0x00100000001f2db5
- (id)personalizedItemSources;	// IMP=0x00100000001f2c04
- (void)configureCard:(id)arg1 forKey:(id)arg2;	// IMP=0x00100000001f2240
- (id)desiredCards;	// IMP=0x00100000001f204f
- (void)configureFocusContainerGuideController:(id)arg1;	// IMP=0x00100000001f2035
- (_Bool)supportsAlternateRouteSelection;	// IMP=0x00100000001f1af1
- (_Bool)shouldSuppressAutohideRecognizerForTouch:(id)arg1;	// IMP=0x00100000001f18ad
@property(readonly, nonatomic) long long accessoriesHidingBehavior;
@property(readonly, nonatomic) long long autohideBehavior;
@property(readonly, nonatomic) _Bool shouldMapControlsModifyMapInsets;
@property(readonly, nonatomic) _Bool shouldAccessoriesModifyMapInsets;
- (_Bool)wantsNavigationDisplay;	// IMP=0x00100000001f1841
- (_Bool)showsNavigationBar;	// IMP=0x00100000001f1839
@property(readonly, nonatomic) _Bool allowMapZoomAndRecentering;
@property(readonly, nonatomic) _Bool showsSpeedLimit;
@property(readonly, nonatomic) _Bool allowKnobNudgeMapPanning;
@property(readonly, nonatomic) _Bool showsHeadingIndicator;
@property(readonly, nonatomic) CDStruct_917cde60 mapControlsConfiguration;
@property(readonly, nonatomic) _Bool showsMapView;
@property(readonly, nonatomic) _TtC4Maps28NavigationWaypointController *waypointController;
@property(readonly, nonatomic) GuidanceObserver *guidanceObserver;
- (id)mapView;	// IMP=0x00100000001f1546
- (id)init;	// IMP=0x00100000001f12c2
- (void)dealloc;	// IMP=0x00100000001f11d8

// Remaining properties
@property(readonly, nonatomic) double autohideIdlenessInterval;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool invalidAfterDisconnect;
@property(readonly, nonatomic) _Bool shouldAllowKnobFocusMovement;
@property(readonly, nonatomic) _Bool shouldTimeoutAfterDisconnect;
@property(readonly, nonatomic) _Bool shouldTimeoutDuringNavigation;
@property(readonly) Class superclass;
@property(readonly, nonatomic) CarMapTrackingController *trackingController;
@property(readonly, nonatomic) id visuallySelectedItem;
@property(readonly, nonatomic) _Bool wantsMapInsetsToRespectSafeAreaInsets;
@property(readonly, nonatomic) _Bool zoomInButtonPressed;
@property(readonly, nonatomic) _Bool zoomOutButtonPressed;

@end

