//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreLocation/CLLocationManager.h>

@interface CLLocationManager (navdExtras)
+ (id)inUseAssertionForNavd;	// IMP=0x0010000000a93d3f
+ (id)navdLocationBundleSource;	// IMP=0x0010000000a93d32
@end

