//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CuratedCollectionFooterActionItem, MUCirclePlatterView, UILabel;

@interface CuratedCollectionFooterActionTableViewCell
{
    CuratedCollectionFooterActionItem *_actionItem;	// 8 = 0x8
    UILabel *_actionTitleLabel;	// 16 = 0x10
    MUCirclePlatterView *_platterView;	// 24 = 0x18
}

+ (id)reuseIdentifier;	// IMP=0x0040000000242cf0
- (void).cxx_destruct;	// IMP=0x0020000000243779
@property(retain, nonatomic) MUCirclePlatterView *platterView; // @synthesize platterView=_platterView;
@property(retain, nonatomic) UILabel *actionTitleLabel; // @synthesize actionTitleLabel=_actionTitleLabel;
@property(retain, nonatomic) CuratedCollectionFooterActionItem *actionItem; // @synthesize actionItem=_actionItem;
- (void)prepareForReuse;	// IMP=0x0010000000243581
- (void)initializeSubviews;	// IMP=0x0010000000242dc8
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0010000000242d02

@end

