//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MapKit/MKAnnotationView.h>

@class CALayer, DebugDirectionAnnotation;

@interface DebugDirectionAnnotationView : MKAnnotationView
{
    DebugDirectionAnnotation *_annotation;	// 8 = 0x8
    CALayer *_directionView;	// 16 = 0x10
    CALayer *_fovLeftDirectionView;	// 24 = 0x18
    CALayer *_fovRightDirectionView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000bfd44c
@property(retain, nonatomic) DebugDirectionAnnotation *annotation; // @synthesize annotation=_annotation;
- (void)_updateTransform;	// IMP=0x0010000000bfcfe9
- (void)_setMapRotationRadians:(double)arg1;	// IMP=0x0010000000bfcfa8
- (void)_setMapPitchRadians:(double)arg1;	// IMP=0x0010000000bfcf67
- (id)initWithAnnotation:(id)arg1 debugAnnotation:(id)arg2 reuseIdentifier:(id)arg3;	// IMP=0x0010000000bfc41b

@end

