//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DirectionsLargeStyleStepView
{
}

+ (unsigned long long)signViewIconSize;	// IMP=0x00400000007c8b83
+ (CDStruct_a1deb1f2)arrowMetrics;	// IMP=0x00100000007c8b4d
+ (Class)_labelListViewClassForRoute:(id)arg1 step:(id)arg2;	// IMP=0x00100000007c8b3c
+ (double)heightForWidth:(double)arg1 route:(id)arg2 step:(id)arg3 idiom:(long long)arg4;	// IMP=0x00100000007c89fb
+ (double)_textWidthForWidth:(double)arg1 metrics:(CDStruct_afa449f9)arg2;	// IMP=0x00100000007c89dd
+ (CDStruct_afa449f9)cellMetricsForIdiom:(long long)arg1;	// IMP=0x00100000007c8966

@end

