//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface FloatingControlsOverlayDelegateProxy
{
}

+ (id)protocols;	// IMP=0x0020000000438b79
- (id)delegatesForSelector:(SEL)arg1 protocol:(id)arg2;	// IMP=0x0020000000438c75
- (id)initWithChromeViewController:(id)arg1;	// IMP=0x0010000000438be5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

