//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AppCoordinator, FlyoverContainerViewController, FlyoverTrayContaineeViewController, NSString;

@interface FlyoverActionCoordinator : NSObject
{
    _Bool _flyoverRunning;	// 8 = 0x8
    AppCoordinator *_appCoordinator;	// 16 = 0x10
    FlyoverContainerViewController *_containerViewController;	// 24 = 0x18
    FlyoverTrayContaineeViewController *_trayContaineeViewController;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000bc5af4
@property(nonatomic, getter=isFlyoverRunning) _Bool flyoverRunning; // @synthesize flyoverRunning=_flyoverRunning;
@property(retain, nonatomic) FlyoverTrayContaineeViewController *trayContaineeViewController; // @synthesize trayContaineeViewController=_trayContaineeViewController;
@property(nonatomic) __weak FlyoverContainerViewController *containerViewController; // @synthesize containerViewController=_containerViewController;
@property(nonatomic) __weak AppCoordinator *appCoordinator; // @synthesize appCoordinator=_appCoordinator;
- (void)flyoverTourCompleted;	// IMP=0x0010000000bc57ff
- (void)flyoverTourResume;	// IMP=0x0010000000bc56ea
- (void)flyoverTourPause;	// IMP=0x0010000000bc55a0
- (void)flyoverTourPlay;	// IMP=0x0010000000bc5428
- (unsigned long long)originalLayoutForViewController:(id)arg1;	// IMP=0x0010000000bc541d
- (void)updateViewMode:(long long)arg1 animated:(_Bool)arg2;	// IMP=0x0010000000bc53a2
@property(readonly, nonatomic) long long displayedViewMode;
- (void)viewControllerPresentTray:(id)arg1;	// IMP=0x0010000000bc52cb
- (void)viewControllerEndFlyover:(id)arg1;	// IMP=0x0010000000bc524d
- (void)viewControllerDidEndFlyover:(id)arg1;	// IMP=0x0010000000bc5243
- (void)viewControllerDidStartFlyover:(id)arg1;	// IMP=0x0010000000bc5239
- (id)initWithContainerViewController:(id)arg1;	// IMP=0x0010000000bc51d5
- (id)init;	// IMP=0x0010000000bc51c7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

