//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CardPresentationController, ExpandableMacPopoverPresentationController, KeyboardProxyingView, MacMenuPresentationController, MacPopoverPresentationController, NSArray, NSString, UIViewController, _TtC4Maps18InfoCardHeaderView;
@protocol MUInfoCardAnalyticsDelegate, MUInfoCardContentProtocol;

@interface InfoCardViewController
{
    _Bool _dragging;	// 8 = 0x8
    struct CGPoint _beginOffset;	// 16 = 0x10
    _Bool _allowScroll;	// 32 = 0x20
    double _previousParentHeight;	// 40 = 0x28
    _Bool _isObservingUserDefaultsKVO;	// 48 = 0x30
    _Bool _useSmoothTransition;	// 49 = 0x31
    ExpandableMacPopoverPresentationController *_expandablePopoverPresentationController;	// 56 = 0x38
    NSArray *_currentHeaderConstraints;	// 64 = 0x40
    UIViewController<MUInfoCardContentProtocol> *_contentViewController;	// 72 = 0x48
    _TtC4Maps18InfoCardHeaderView *_titleHeaderView;	// 80 = 0x50
    KeyboardProxyingView *_keyboardProxyView;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x002000000018c123
@property(retain, nonatomic) KeyboardProxyingView *keyboardProxyView; // @synthesize keyboardProxyView=_keyboardProxyView;
@property(readonly, nonatomic) _TtC4Maps18InfoCardHeaderView *titleHeaderView; // @synthesize titleHeaderView=_titleHeaderView;
@property(retain, nonatomic) UIViewController<MUInfoCardContentProtocol> *contentViewController; // @synthesize contentViewController=_contentViewController;
- (double)macContaineeWidth;	// IMP=0x001000000018c0df
@property(readonly, nonatomic) MacPopoverPresentationController *macPopoverPresentationController;
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x001000000018bb66
- (void)didScrollPastTransition;	// IMP=0x001000000018baf8
@property(readonly, nonatomic) _Bool isShowingFullHeader;
@property(readonly, nonatomic) long long floatingControlsOptions;
- (void)shouldDismissForHorizontalSwipe_nonUIKitCardsOnly;	// IMP=0x001000000018ba86
- (void)applyLayoutToContent:(unsigned long long)arg1;	// IMP=0x001000000018ba23
- (void)applyAlphaToContent:(double)arg1;	// IMP=0x001000000018b988
- (void)willBecomeCurrent:(_Bool)arg1;	// IMP=0x001000000018b918
- (void)willChangeLayout:(unsigned long long)arg1;	// IMP=0x001000000018b7d5
@property(readonly, nonatomic) id <MUInfoCardAnalyticsDelegate> analyticsDelegate;
@property(readonly, nonatomic) _Bool supportsSharing;
- (void)handleShareWithPresentationOptions:(id)arg1;	// IMP=0x001000000018b74d
- (void)_handleDismissActionWithHeaderView:(id)arg1;	// IMP=0x001000000018b709
- (void)updateContentHeaderTrailingConstant;	// IMP=0x001000000018b6ec
- (void)headerViewDidUpdateButtonContainerContentSize:(id)arg1;	// IMP=0x001000000018b6da
- (id)headerView:(id)arg1 menuForButtonConfiguration:(id)arg2;	// IMP=0x001000000018b691
- (id)underlyingHeaderViewForHitTesting:(id)arg1;	// IMP=0x001000000018b63a
- (void)headerView:(id)arg1 selectedActionButton:(id)arg2 withPresentationOptions:(id)arg3;	// IMP=0x001000000018b5ad
- (void)headerViewTapped:(id)arg1;	// IMP=0x001000000018b52a
- (void)performAction:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000018b524
- (id)menuElementForActionItem:(id)arg1;	// IMP=0x001000000018b2fc
- (id)headerActionItems;	// IMP=0x001000000018b2ef
- (id)_createActionMenu;	// IMP=0x001000000018b109
- (id)headerMenuSortOrderByActionType;	// IMP=0x001000000018af42
- (void)rebuildHeaderMenu;	// IMP=0x001000000018aecd
- (void)updateHeaderWithConstraints:(id)arg1;	// IMP=0x001000000018ae28
- (id)headerView;	// IMP=0x001000000018ad40
- (void)setContaineeDelegate:(id)arg1;	// IMP=0x001000000018ac6a
- (void)instrumentDismissAction;	// IMP=0x001000000018ac0d
- (void)handleDismissAction:(id)arg1;	// IMP=0x001000000018aba9
- (void)_showHeader:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x001000000018a9c4
- (void)viewDidLayoutSubviews;	// IMP=0x001000000018a7cc
- (double)heightForLayout:(unsigned long long)arg1;	// IMP=0x001000000018a0d3
- (void)_contentSizeDidChange;	// IMP=0x001000000018a00c
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0010000000189de6
- (void)dealloc;	// IMP=0x0010000000189bdf
@property(readonly, nonatomic) double titleTrailingConstant;
- (id)preferredFocusEnvironments;	// IMP=0x0010000000189ac6
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0010000000189a7c
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000189a12
- (void)viewDidLoad;	// IMP=0x0010000000189157

// Remaining properties
@property(readonly, nonatomic) _Bool allowsLongPressToMarkLocation;
@property(readonly, nonatomic) _Bool allowsQuickActionMenuInMap;
@property(readonly, nonatomic) CardPresentationController *cardPresentationController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) double headerHeight;
@property(readonly, nonatomic) MacMenuPresentationController *macMenuPresentationController;
@property(nonatomic) unsigned long long preferredPresentationStyle;
@property(readonly, nonatomic) unsigned long long retainedLayout;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSArray *topBannerItems;

@end

