//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface IPCMuteSpokenGuidanceMessage
{
    _Bool _muteNavigation;	// 8 = 0x8
}

@property(nonatomic) _Bool muteNavigation; // @synthesize muteNavigation=_muteNavigation;
- (id)description;	// IMP=0x00100000009539c6
- (id)dictionaryValue;	// IMP=0x00100000009538ed
- (id)initWithDictionary:(id)arg1;	// IMP=0x0010000000953841

@end

