//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CollectionHandler, MacContainerViewController;
@protocol ContaineeContentInjection;

@interface MacBaseActionCoordinator
{
}

@property(readonly, nonatomic) CollectionHandler *injectedCollection;
@property(retain, nonatomic) id <ContaineeContentInjection> sidebarContentInjector;
- (void)deferPresentingMapPopoversInsideBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000d45f97
- (void)mapSelectionManagerClearSelection:(id)arg1;	// IMP=0x0010000000d45efe
- (void)viewController:(id)arg1 removeDroppedPin:(id)arg2;	// IMP=0x0010000000d45e4c
- (void)makeMapViewFirstResponder;	// IMP=0x0010000000d45de2
- (_Bool)shouldClearMapSelectionOnDismissOfViewController:(id)arg1;	// IMP=0x0010000000d45cb0
- (void)handleMapViewTapToDeselect;	// IMP=0x0010000000d45c34
- (void)viewControllerPresentUserProfile:(id)arg1;	// IMP=0x0010000000d45c2e
- (void)toggleRoutePlanning;	// IMP=0x0010000000d45b6c
- (void)viewControllerGoPreviousState:(id)arg1 withSender:(id)arg2;	// IMP=0x0010000000d45ad0
- (_Bool)shouldReusePlaceCardViewController:(id)arg1;	// IMP=0x0010000000d45ac8
- (void)viewController:(id)arg1 selectSearchResult:(id)arg2 addToHistory:(_Bool)arg3 source:(unsigned long long)arg4 saveSelectionState:(_Bool)arg5 replaceCurrentCard:(_Bool)arg6;	// IMP=0x0010000000d45961
- (void)viewController:(id)arg1 doSearchItem:(id)arg2 withUserInfo:(id)arg3;	// IMP=0x0010000000d45806
- (void)viewController:(id)arg1 selectPersonalizedItem:(id)arg2 source:(unsigned long long)arg3 saveSelectionState:(_Bool)arg4;	// IMP=0x0010000000d456c5
- (id)macChromeViewController;	// IMP=0x0010000000d45675
@property(readonly, nonatomic) MacContainerViewController *macContainerViewController;

@end

