//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GEOMapDataSubscriptionManager, NSString, OfflineMapsManagementSearchAutocompleteDataSource, UICollectionView, UINavigationBar, UISearchController;
@protocol OfflineMapsManagementActionCoordination;

@interface OfflineMapsManagementSearchAutocompleteViewController
{
    id <OfflineMapsManagementActionCoordination> _delegate;	// 8 = 0x8
    GEOMapDataSubscriptionManager *_subscriptionManager;	// 16 = 0x10
    UINavigationBar *_navBar;	// 24 = 0x18
    UISearchController *_searchController;	// 32 = 0x20
    UICollectionView *_collectionView;	// 40 = 0x28
    OfflineMapsManagementSearchAutocompleteDataSource *_searchDataSource;	// 48 = 0x30
}

+ (_Bool)wantsDefaultHeaderContentViews;	// IMP=0x0020000000cc371b
- (void).cxx_destruct;	// IMP=0x0020000000cc53b7
@property(retain, nonatomic) OfflineMapsManagementSearchAutocompleteDataSource *searchDataSource; // @synthesize searchDataSource=_searchDataSource;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UISearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) UINavigationBar *navBar; // @synthesize navBar=_navBar;
@property(retain, nonatomic) GEOMapDataSubscriptionManager *subscriptionManager; // @synthesize subscriptionManager=_subscriptionManager;
@property(nonatomic) __weak id <OfflineMapsManagementActionCoordination> delegate; // @synthesize delegate=_delegate;
- (void)updateSearchResultsForSearchController:(id)arg1;	// IMP=0x0010000000cc5223
- (void)dataSource:(id)arg1 itemTapped:(id)arg2;	// IMP=0x0010000000cc4dc5
- (void)dataSource:(id)arg1 itemFocused:(id)arg2;	// IMP=0x0010000000cc4dbf
- (void)dataSourceUpdated:(id)arg1;	// IMP=0x0010000000cc4db9
- (void)didDismissByGesture;	// IMP=0x0010000000cc4da7
- (void)_addSubscriptionForMapItem:(id)arg1;	// IMP=0x0000000000cc4a71
- (void)_dismiss;	// IMP=0x0010000000cc4a34
- (void)_setupConstraints;	// IMP=0x0010000000cc43cc
- (void)_setupViews;	// IMP=0x0010000000cc39e5
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0010000000cc3979
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000cc3880
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000cc3779
- (void)viewDidLoad;	// IMP=0x0010000000cc3723

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

