//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MKMapItem, RAPPlacecardImageryLayoutManager;
@protocol PhotoViewerToolbarControllerActionHandling;

@interface PhotoViewerToolbarController : NSObject
{
    MKMapItem *_mapItem;	// 8 = 0x8
    RAPPlacecardImageryLayoutManager *_rapLayoutManger;	// 16 = 0x10
    _Bool _suppressPhotoGrid;	// 24 = 0x18
    long long _context;	// 32 = 0x20
    id <PhotoViewerToolbarControllerActionHandling> _delegate;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000017ff40
@property(nonatomic, getter=shouldSuppressPhotoGrid) _Bool suppressPhotoGrid; // @synthesize suppressPhotoGrid=_suppressPhotoGrid;
@property(nonatomic) __weak id <PhotoViewerToolbarControllerActionHandling> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long context; // @synthesize context=_context;
@property(readonly, nonatomic) _Bool shouldShowPhotoThumbnailFeed;
@property(readonly, nonatomic) _Bool shouldShowAddPhotoButton;
@property(readonly, nonatomic) _Bool shouldShowReportAnIssue;
- (void)_morePhotosButtonTapped;	// IMP=0x001000000017fda9
- (void)_rightButtonTapped;	// IMP=0x001000000017fd5d
- (void)_leftButtonTapped;	// IMP=0x001000000017fd11
- (void)_addPhotoTapped;	// IMP=0x001000000017fcc5
- (id)initWithMapItem:(id)arg1;	// IMP=0x001000000017fc5a

@end

