//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MKMapView, NSString;

@interface POIShapeSearchResult
{
}

- (id)initWithMapView:(id)arg1 searchResult:(id)arg2;	// IMP=0x00200000003844b8

// Remaining properties
@property(readonly, nonatomic) struct CLLocationCoordinate2D centerCoordinate;
@property(readonly, nonatomic) struct CGRect currentFrameInMapView;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) struct CGSize estimatedSize;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) __weak MKMapView *mapView;
@property(readonly) Class superclass;

@end

