//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface RAPAddressLayoutOptions : NSObject
{
    _Bool _showUnit;	// 8 = 0x8
    _Bool _showBuilding;	// 9 = 0x9
    _Bool _showFloor;	// 10 = 0xa
}

+ (id)allFieldsDisabledOptions;	// IMP=0x0020000000565614
+ (id)allFieldsEnabledOptions;	// IMP=0x00100000005655b5
+ (id)clientOverrideOptions;	// IMP=0x0010000000565526
@property(nonatomic) _Bool showFloor; // @synthesize showFloor=_showFloor;
@property(nonatomic) _Bool showBuilding; // @synthesize showBuilding=_showBuilding;
@property(nonatomic) _Bool showUnit; // @synthesize showUnit=_showUnit;
@property(readonly, nonatomic) long long numberOfEnabledOptions;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000565749
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000005656a8
- (id)init;	// IMP=0x001000000056566a

@end

