//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface RAPCategoriesDownloader : NSObject
{
}

+ (id)preferredTranslationInTitles:(id)arg1 givenPreferredLanguagesList:(id)arg2;	// IMP=0x0040000000515019
+ (id)adjustedPreferredLanguages;	// IMP=0x0010000000514d2a
+ (void)fetchCategories:(CDUnknownBlockType)arg1;	// IMP=0x0010000000514760

@end

