//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UITableViewCell.h>

@class NSArray, NSAttributedString, NSLayoutConstraint, UILabel, UIView;

@interface RAPReportComposerTwoLineSnippetTableViewCell : UITableViewCell
{
    UILabel *_firstLineLabel;	// 8 = 0x8
    UILabel *_secondLineLabel;	// 16 = 0x10
    NSArray *_leftMarginConstraints;	// 24 = 0x18
    NSArray *_rightMarginConstraints;	// 32 = 0x20
    NSLayoutConstraint *_collapsibleFirstSecondLineMargin;	// 40 = 0x28
    NSArray *_allConstraints;	// 48 = 0x30
    UIView *_thirdLineAccessoryView;	// 56 = 0x38
}

+ (id)measuringCell;	// IMP=0x0040000000a61d16
- (void).cxx_destruct;	// IMP=0x0020000000a61e0e
@property(retain, nonatomic) UIView *thirdLineAccessoryView; // @synthesize thirdLineAccessoryView=_thirdLineAccessoryView;
- (double)preferredHeightInTableView:(id)arg1;	// IMP=0x0010000000a61c7f
- (void)updateTextWithReplacements:(id)arg1;	// IMP=0x0010000000a61a34
- (id)defaultReplacementAttributes;	// IMP=0x0010000000a61a27
@property(readonly, nonatomic) NSAttributedString *attributedStringFormat;
- (void)layoutMarginsDidChange;	// IMP=0x0010000000a619de
- (void)didMoveToSuperview;	// IMP=0x0010000000a6199d
- (void)_updateLeftRightConstraints;	// IMP=0x0010000000a61071
- (void)_recreateConstraints;	// IMP=0x0010000000a600dc
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0010000000a5fe78

@end

