//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface RidesharingAppSuggestionsProvider : NSObject
{
}

+ (id)sharedProvider;	// IMP=0x0040000000b1d236
- (id)partitionedApplicationSuggestionsFromSuggestions:(id)arg1;	// IMP=0x0040000000b1de57
- (id)_applicationsAfterFilteringOutInstalledApplicationsFromApplications:(id)arg1;	// IMP=0x0010000000b1dc84
- (id)_searchErrorWithUserInfo:(id)arg1;	// IMP=0x0010000000b1dc5c
- (void)_fetchAppDataForAppIDs:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000b1db10
- (void)_fetchAppIDsForSource:(struct CLLocationCoordinate2D)arg1 destination:(struct CLLocationCoordinate2D)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000b1d4e2
- (void)fetchSuggestedAppsForSource:(struct CLLocationCoordinate2D)arg1 destination:(struct CLLocationCoordinate2D)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000b1d2bb

@end

