//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SearchBarSearchResultSet : NSObject
{
    NSArray *_results;	// 8 = 0x8
    unsigned long long _count;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000002fbab4
@property(readonly, nonatomic) unsigned long long count; // @synthesize count=_count;
@property(readonly, nonatomic) NSArray *results; // @synthesize results=_results;
- (id)initWithResults:(id)arg1 maxCount:(unsigned long long)arg2;	// IMP=0x00100000002fba33

@end

