//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MKMapView, NSMutableArray;

@interface SearchResultsDebugOverlay : NSObject
{
    NSMutableArray *_polygons;	// 8 = 0x8
    MKMapView *_mapView;	// 16 = 0x10
}

+ (id)viewForAnnotation:(id)arg1;	// IMP=0x004000000020b76e
+ (id)rendererWithPolygon:(id)arg1;	// IMP=0x001000000020b69f
- (void).cxx_destruct;	// IMP=0x002000000020b7f8
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
@property(retain, nonatomic) NSMutableArray *polygons; // @synthesize polygons=_polygons;
- (id)annotationTitleWithMapRegion:(id)arg1 title:(id)arg2;	// IMP=0x001000000020b4d1
- (id)polygonForMapRegion:(id)arg1 title:(id)arg2;	// IMP=0x001000000020b292
- (void)removeDrawnDebugMapRegions;	// IMP=0x001000000020b1a2
- (void)drawDebugMapRegionsWithSearchResults:(id)arg1 suggestedMapRegion:(id)arg2;	// IMP=0x001000000020ad2e
- (id)initWithMapView:(id)arg1;	// IMP=0x001000000020acc3

@end

