//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString, UICollectionViewCellRegistration, UIImage;
@protocol SmallButtonOutlineCellDelegate;

@interface SmallButtonOutlineCellModel : NSObject
{
    long long _style;	// 8 = 0x8
    NSString *_title;	// 16 = 0x10
    UIImage *_image;	// 24 = 0x18
    UIImage *_hoverImage;	// 32 = 0x20
    id <SmallButtonOutlineCellDelegate> _delegate;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000a79965
@property(readonly, nonatomic) __weak id <SmallButtonOutlineCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIImage *hoverImage; // @synthesize hoverImage=_hoverImage;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) long long style; // @synthesize style=_style;
- (MISSING_TYPE *)needsReloadFromPreviousViewModel: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000a79912
@property(readonly, nonatomic) UICollectionViewCellRegistration *cellRegistration;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000a7974b
@property(readonly) unsigned long long hash;
- (id)initWithStyle:(long long)arg1 title:(id)arg2 image:(id)arg3 hoverImage:(id)arg4 delegate:(id)arg5;	// IMP=0x0010000000a79634

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

