//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CardButton, ContainerHeaderView, NSLayoutConstraint, NSNumber, NSString, RoutePlanningTransitionController, TransitDirectionsListViewController, UIScrollView, UIView;
@protocol TransitNavigationTrayDelegate;

@interface TransitNavigationTrayViewController
{
    ContainerHeaderView *_containerHeaderView;	// 8 = 0x8
    TransitDirectionsListViewController *_listViewController;	// 16 = 0x10
    RoutePlanningTransitionController *_transitionController;	// 24 = 0x18
    CardButton *_endButton;	// 32 = 0x20
    _Bool _hasForcedInitialContaineeHeight;	// 40 = 0x28
    unsigned long long _previousLayoutForTransition;	// 48 = 0x30
    unsigned long long _previousStyleForTransition;	// 56 = 0x38
    double _previousMediumTransitionHeight;	// 64 = 0x40
    double _preTransitionContentOffsetY;	// 72 = 0x48
    NSLayoutConstraint *_headerBottomConstraint;	// 80 = 0x50
    UIView *_lowLuminanceBackgroundView;	// 88 = 0x58
    id <TransitNavigationTrayDelegate> _trayDelegate;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x002000000033c52c
@property(nonatomic) __weak id <TransitNavigationTrayDelegate> trayDelegate; // @synthesize trayDelegate=_trayDelegate;
@property(readonly, nonatomic) NSNumber *displayedItemIndexForAnalytics;
- (void)_recordChangeToLayout:(unsigned long long)arg1;	// IMP=0x001000000033c38f
- (int)currentUITargetForAnalytics;	// IMP=0x001000000033c384
@property(readonly, nonatomic) UIScrollView *pptTestScrollView;
- (_Bool)pptTestMoveToBoardStep;	// IMP=0x001000000033c318
- (void)pptTestMoveToNextStep;	// IMP=0x001000000033c2d0
@property(readonly, nonatomic) _Bool pptTestHasNextStep;
@property(readonly, nonatomic) long long pptTestCurrentStepIndex;
@property(readonly, nonatomic) _Bool pptTestSupportStepping;
- (void)_endButtonPressed;	// IMP=0x001000000033c136
- (double)_maximumMediumCardHeight;	// IMP=0x001000000033c03a
- (struct CGRect)_rectOfRowToKeepVisible;	// IMP=0x001000000033bfcf
- (void)transitionControllerWillFinish:(id)arg1;	// IMP=0x001000000033bfc9
- (void)transitionControllerWillStart:(id)arg1;	// IMP=0x001000000033bfc3
- (id)transitionContextForTransitionController:(id)arg1;	// IMP=0x001000000033bd22
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x001000000033bb4e
- (void)headerViewTapped:(id)arg1;	// IMP=0x001000000033ba85
- (id)contentView;	// IMP=0x001000000033ba68
- (id)headerView;	// IMP=0x001000000033ba53
- (double)heightForLayout:(unsigned long long)arg1;	// IMP=0x001000000033b76c
- (void)didChangeContainerStyle:(unsigned long long)arg1;	// IMP=0x001000000033b66d
- (void)didChangeLayout:(unsigned long long)arg1;	// IMP=0x001000000033b569
- (void)willChangeLayout:(unsigned long long)arg1;	// IMP=0x001000000033b4ee
- (void)updateBacklightSceneEnvironment;	// IMP=0x001000000033b3ed
- (void)updateForCurrentDisplayedStepAnimated:(_Bool)arg1;	// IMP=0x001000000033b0c6
- (void)updateForCurrentDisplayedStep;	// IMP=0x001000000033b0af
- (void)updateForClusteredLegSelectedRideIndexChange;	// IMP=0x001000000033b067
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000033af83
- (void)_updateListBackgroundAlphaForCurrentCardHeight:(double)arg1;	// IMP=0x001000000033af66
- (void)_updateHeaderViewForCurrentCardHeight:(double)arg1;	// IMP=0x001000000033adf0
- (void)_updateTransitionControllerForTransitionProgressSmallToMedium:(double)arg1 mediumToFull:(double)arg2;	// IMP=0x001000000033a893
- (_Bool)_updateListContentInsetWithHeight:(double)arg1;	// IMP=0x001000000033a5f8
- (void)_updateTransitionProgressForCurrentCard;	// IMP=0x001000000033a3f4
- (void)viewDidLayoutSubviews;	// IMP=0x001000000033a30e
- (void)viewWillLayoutSubviews;	// IMP=0x001000000033a102
- (void)viewDidLoad;	// IMP=0x0010000000339386
- (void)setTitle:(id)arg1;	// IMP=0x0010000000339314
- (id)initWithRoute:(id)arg1 stepsListDelegate:(id)arg2;	// IMP=0x0010000000339152
- (_Bool)_canShowWhileLocked;	// IMP=0x001000000033914a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

