//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString;

@interface TransitDirectionsListItemWalking
{
    _Bool _expanded;	// 32 = 0x20
    NSArray *_walkingSubItems;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00100000003fb67c
@property(copy, nonatomic) NSArray *walkingSubItems; // @synthesize walkingSubItems=_walkingSubItems;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
- (_Bool)_shouldHideWalkingSubStep:(id)arg1;	// IMP=0x00100000003fb5ae
- (id)_generateWalkingSubSteps;	// IMP=0x00100000003fb0c5
- (id)_transitWalkingLegInstruction;	// IMP=0x00100000003fb04b
- (id)initWithWalkingSegment:(id)arg1 toBoardStep:(id)arg2;	// IMP=0x00100000003fab5d
- (unsigned long long)numberOfSubItemsWithForceExpand:(_Bool)arg1;	// IMP=0x0010000000bebc82
- (id)subItemsWithForceExpand:(_Bool)arg1;	// IMP=0x0010000000bebc03
- (void)_rebuildSubItems;	// IMP=0x0010000000bebbd7
@property(readonly, nonatomic) _Bool shouldDisplayExpandButton;
@property(readonly, nonatomic) _Bool shouldEnableExpandedButton;
- (id)expandingButtonTitleForExpandedState:(_Bool)arg1;	// IMP=0x0010000000bebb11
@property(copy, nonatomic) NSArray *expandedItems;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

