//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ContainerHeaderView, FilterCategoriesView, LoadingModeView, MISSING_TYPE, NSDictionary, NSString, UIImageView, UILabel, UITableView, VKVenueFeatureMarker, VenueCategoryContentDownloader, VenueCategoryDataSource;

@interface VenueCategoryViewController
{
    ContainerHeaderView *_containerHeaderView;	// 8 = 0x8
    _Bool _shouldDisplayFilterView;	// 16 = 0x10
    _Bool _showsLoading;	// 17 = 0x11
    _Bool _isAutoComplete;	// 18 = 0x12
    _Bool _didFinishAutoCompleteSearchRequest;	// 19 = 0x13
    short _currentSelectedFloorOrdinal;	// 20 = 0x14
    VenueCategoryContentDownloader *_contentDownloader;	// 24 = 0x18
    UIImageView *_headerImageView;	// 32 = 0x20
    UILabel *_headerLabel;	// 40 = 0x28
    UITableView *_tableView;	// 48 = 0x30
    FilterCategoriesView *_filterView;	// 56 = 0x38
    LoadingModeView *_loadingModeView;	// 64 = 0x40
    VenueCategoryDataSource *_dataSource;	// 72 = 0x48
    VKVenueFeatureMarker *_venueWithFocus;	// 80 = 0x50
    NSString *_headerTitle;	// 88 = 0x58
    id _lastItemTapped;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x0020000000d2b555
@property(retain, nonatomic) id lastItemTapped; // @synthesize lastItemTapped=_lastItemTapped;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(nonatomic) _Bool didFinishAutoCompleteSearchRequest; // @synthesize didFinishAutoCompleteSearchRequest=_didFinishAutoCompleteSearchRequest;
@property(nonatomic) _Bool isAutoComplete; // @synthesize isAutoComplete=_isAutoComplete;
@property(nonatomic) _Bool showsLoading; // @synthesize showsLoading=_showsLoading;
@property(nonatomic) __weak VKVenueFeatureMarker *venueWithFocus; // @synthesize venueWithFocus=_venueWithFocus;
@property(retain, nonatomic) VenueCategoryDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) LoadingModeView *loadingModeView; // @synthesize loadingModeView=_loadingModeView;
@property(retain, nonatomic) FilterCategoriesView *filterView; // @synthesize filterView=_filterView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool shouldDisplayFilterView; // @synthesize shouldDisplayFilterView=_shouldDisplayFilterView;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
@property(retain, nonatomic) UIImageView *headerImageView; // @synthesize headerImageView=_headerImageView;
@property(retain, nonatomic) VenueCategoryContentDownloader *contentDownloader; // @synthesize contentDownloader=_contentDownloader;
@property(nonatomic) short currentSelectedFloorOrdinal; // @synthesize currentSelectedFloorOrdinal=_currentSelectedFloorOrdinal;
- (void)selectSubcategory:(id)arg1;	// IMP=0x0010000000d2b25b
- (int)currentMapViewTargetForAnalytics;	// IMP=0x0010000000d2b250
- (int)currentUITargetForAnalytics;	// IMP=0x0010000000d2b245
- (id)_buildingAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000d2b1a5
- (id)_venueShortNameForMapItem:(id)arg1;	// IMP=0x0010000000d2b12d
- (void)headerViewTapped:(id)arg1;	// IMP=0x0010000000d2b0f0
- (id)_headerLabelTextFromMapItem:(id)arg1 searchCategory:(id)arg2;	// IMP=0x0010000000d2af70
- (void)dataSourceUpdated:(id)arg1;	// IMP=0x0010000000d2af6a
- (void)dataSource:(id)arg1 itemTapped:(id)arg2;	// IMP=0x0010000000d2aeb8
- (void)dataSource:(id)arg1 itemFocused:(id)arg2;	// IMP=0x0010000000d2adba
@property(readonly, nonatomic) int refineSearchSessionType;
@property(readonly, nonatomic) NSString *refineSearchText;
- (void)updateFooterVisibility;	// IMP=0x0010000000d2aabd
- (void)filterView:(id)arg1 didSelectBuildingWithIndex:(unsigned long long)arg2;	// IMP=0x0010000000d2a9ba
- (void)filterView:(id)arg1 didSelectSubcategoryWithIndex:(unsigned long long)arg2;	// IMP=0x0010000000d2a893
- (void)filterView:(id)arg1 indexSelected:(unsigned long long)arg2;	// IMP=0x0010000000d2a7cd
- (void)setFilterViewHidden:(_Bool)arg1;	// IMP=0x0010000000d2a6e7
- (void)headerViewButtonTapped:(id)arg1;	// IMP=0x0010000000d2a694
- (void)willChangeContainerStyle:(unsigned long long)arg1;	// IMP=0x0010000000d2a57e
- (void)handleDismissAction:(id)arg1;	// IMP=0x0010000000d2a4ce
- (void)configureTableView;	// IMP=0x0010000000d29716
- (void)notifyVenuesManagerAndSwitchToBestFloor:(_Bool)arg1;	// IMP=0x0010000000d2963a
- (void)didUpdateResults;	// IMP=0x0010000000d29538
@property(readonly, nonatomic) NSDictionary *searchResultCountInVenue;
- (void)updateHeaderImageView;	// IMP=0x0010000000d28f4f
- (void)configureHeader;	// IMP=0x0010000000d282b6
- (id)headerLabelFont;	// IMP=0x0010000000d2829d
- (void)applyAlphaToContent:(double)arg1;	// IMP=0x0010000000d2824a
- (void)contentSizeCategoryDidChange:(id)arg1;	// IMP=0x0010000000d281da
- (void)displayIndexListIfNecessary;	// IMP=0x0010000000d28046
- (void)viewDidLayoutSubviews;	// IMP=0x0010000000d27fc2
- (void)viewWillLayoutSubviews;	// IMP=0x0010000000d27f81
- (void)viewSafeAreaInsetsDidChange;	// IMP=0x0010000000d27dd9
- (void)updateFilterBar;	// IMP=0x0010000000d27cea
- (void)performInitialSearchIfNecessary;	// IMP=0x0010000000d27af8
- (void)setDelegate:(id)arg1;	// IMP=0x0010000000d27ab7
- (void)viewDidLoad;	// IMP=0x0010000000d27a07
- (MISSING_TYPE *)venueCategoryContentDownloader:didReceiveAutoCompleteSubcategories:subcategoriesType: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000d278c0
- (void)venueCategoryContentDownloader:(id)arg1 didReceiveSearchResults:(id)arg2 shouldSwitchToBestFloor:(_Bool)arg3;	// IMP=0x0010000000d276e2
- (void)venueCategoryContentDownloaderDidCancel:(id)arg1;	// IMP=0x0010000000d2765d
- (void)venueCategoryContentDownloaderDidFail:(id)arg1;	// IMP=0x0010000000d275d8
- (void)venueCategoryContentDownloader:(id)arg1 didFailToFetchMapItemWithError:(id)arg2;	// IMP=0x0010000000d2751c
- (void)venueCategoryContentDownloader:(id)arg1 didChangeMapItem:(id)arg2;	// IMP=0x0010000000d27330
- (void)venueCategoryContentDownloaderDidStart:(id)arg1;	// IMP=0x0010000000d272ca
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000d2725c
- (id)initWithAutoCompleteCategoryCardItem:(id)arg1;	// IMP=0x0010000000d270a2
- (id)initWithCategoryCardItem:(id)arg1;	// IMP=0x0010000000d26f7b
- (id)initWithSearchCategory:(id)arg1;	// IMP=0x0010000000d26e1e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

