//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SKGPhoneEdge
{
}

+ (id)edgeFromPhone:(id)arg1 toNode:(id)arg2;	// IMP=0x004000000002897d
+ (id)name;	// IMP=0x001000000002896c
+ (Class)nodeClass;	// IMP=0x001000000002895b

@end

