//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol MRUIClientProtocol;

@interface MRDUIClientBSMessageForwarder
{
    id <MRUIClientProtocol> _target;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000012f0f9
@property(nonatomic) __weak id <MRUIClientProtocol> target; // @synthesize target=_target;

@end

