//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <BridgePreferences/BPSListController.h>

@interface COSFollowUpDetailViewController : BPSListController
{
}

- (id)specifiers;	// IMP=0x004000000012c186

@end

