//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UITableViewCell.h>

@class BPSMultipleWatchMigrationView;

@interface COSMigrationChoiceDevicePickerViewCell : UITableViewCell
{
    BPSMultipleWatchMigrationView *_migrationPickerView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000cf57f
@property(retain, nonatomic) BPSMultipleWatchMigrationView *migrationPickerView; // @synthesize migrationPickerView=_migrationPickerView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00100000000cf53d
- (void)layoutSubviews;	// IMP=0x00100000000cf4c6
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00100000000cf3e2

@end

