//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface COSTinkerWiFiPickerOptinViewContoller
{
}

+ (_Bool)controllerNeedsToRun;	// IMP=0x00400000000d49e8
- (id)alternateButtonTitle;	// IMP=0x00400000000d50a2
- (id)okayButtonTitle;	// IMP=0x00100000000d5036
- (id)suggestedButtonTitle;	// IMP=0x00100000000d4ed5
- (void)okayButtonPressed:(id)arg1;	// IMP=0x00100000000d4e89
- (void)alternateButtonPressed:(id)arg1;	// IMP=0x00100000000d4e3d
- (void)suggestedButtonPressed:(id)arg1;	// IMP=0x00100000000d4d91
- (id)imageResource;	// IMP=0x00100000000d4d80
- (id)detailString;	// IMP=0x00100000000d4be0
- (id)titleString;	// IMP=0x00100000000d4aa7
- (id)init;	// IMP=0x00100000000d4a56

@end

