//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC11Preferences19VPNListItemProvider : _TtCs12_SwiftObject
{
    MISSING_TYPE *id;	// 16 = 0x10
    MISSING_TYPE *hasRelayConfigurations;	// 129 = 0x81
    MISSING_TYPE *visibilityStyle;	// 136 = 0x88
    MISSING_TYPE *connectivityState;	// 144 = 0x90
    MISSING_TYPE *invalidator;	// 152 = 0x98
    MISSING_TYPE *vpnConnectivityManager;	// 192 = 0xc0
}

- (void)connectivityManagerDidChange:(id)arg1;	// IMP=0x00400000000253d0

@end

