//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface SRTCCStorePassThrough : NSObject
{
}

+ (void)initialize;	// IMP=0x0020000000031800
- (_Bool)checkAccessForService:(id)arg1 auditToken:(CDStruct_6ad76789)arg2;	// IMP=0x0020000000031a20
- (void)requestAccessForService:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000031a00
- (long long)preflightAuthorizationStatusForService:(id)arg1;	// IMP=0x00100000000319d0
- (_Bool)setValue:(_Bool)arg1 forService:(id)arg2 bundleId:(id)arg3;	// IMP=0x00100000000319b0
- (_Bool)resetService:(id)arg1;	// IMP=0x0010000000031990
- (_Bool)resetService:(id)arg1 forBundleId:(id)arg2;	// IMP=0x0010000000031970
- (_Bool)setOverride:(_Bool)arg1 forService:(id)arg2;	// IMP=0x0010000000031950
- (id)informationForBundleId:(id)arg1;	// IMP=0x0010000000031930
- (_Bool)isOverriddenForService:(id)arg1;	// IMP=0x0010000000031890
- (id)bundleIdentifiersDisabledForService:(id)arg1;	// IMP=0x0010000000031870
- (id)bundleIdentifiersForService:(id)arg1;	// IMP=0x0010000000031850

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

