//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class DRDragSession, NSArray, NSObject, NSXPCConnection, UIDraggingSystemTouchRoutingPolicy, _DUIPotentialDrop;
@protocol OS_dispatch_queue, _DUIClientSessionCommon;

@protocol DRDragSessionDelegate <NSObject>
- (void)dragSession:(DRDragSession *)arg1 updateRoutingPolicy:(UIDraggingSystemTouchRoutingPolicy *)arg2;
- (void)dragSession:(DRDragSession *)arg1 moveToLocation:(struct CAPoint3D)arg2;
- (void)dragSession:(DRDragSession *)arg1 enableKeyboardIfNeeded:(_Bool)arg2;
- (void)dragSessionDidEnd:(DRDragSession *)arg1;
- (void)dragSessionWillEnd:(DRDragSession *)arg1;
- (void)dragSession:(DRDragSession *)arg1 animateOutVisibleItemsWithOperation:(unsigned long long)arg2;
- (void)dragSession:(DRDragSession *)arg1 removeVisibleDroppedItemsInSpaceOfContextID:(unsigned int)arg2 layerRenderID:(unsigned long long)arg3 replyingOnQueue:(NSObject<OS_dispatch_queue> *)arg4 with:(void (^)(NSArray *, BKSAnimationFenceHandle *))arg5;
- (void)dragSession:(DRDragSession *)arg1 findVisibleDroppedItemsReplyingOnQueue:(NSObject<OS_dispatch_queue> *)arg2 with:(void (^)(NSArray *))arg3;
- (_Bool)dragSession:(DRDragSession *)arg1 destinationIsSystemConnection:(NSXPCConnection *)arg2;
- (NSArray *)allWindowContextIdsForDragSession:(DRDragSession *)arg1;
- (void)resetDestinationClientForDragSession:(DRDragSession *)arg1;
- (void)dragSession:(DRDragSession *)arg1 updatedPotentialDrop:(_DUIPotentialDrop *)arg2 forDestinationClient:(id <_DUIClientSessionCommon>)arg3;
- (void)dragSession:(DRDragSession *)arg1 addedItemCount:(unsigned long long)arg2;
- (void)dragSession:(DRDragSession *)arg1 invalidateImageForClient:(id <_DUIClientSessionCommon>)arg2 itemIndex:(unsigned long long)arg3;
@end

