//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class DRFlockBadgeLayout, NSArray, UIView;

@interface DRFlockLayoutOutput : NSObject
{
    _Bool _reduceBadgeAnimationSpring;	// 8 = 0x8
    NSArray *_allViews;	// 16 = 0x10
    NSArray *_itemViews;	// 24 = 0x18
    NSArray *_itemLayouts;	// 32 = 0x20
    NSArray *_shownItemModels;	// 40 = 0x28
    DRFlockBadgeLayout *_badgeLayout;	// 48 = 0x30
    UIView *_badgeView;	// 56 = 0x38
    double _orientationRotation;	// 64 = 0x40
    unsigned long long _touchesCount;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000015b4c
@property(nonatomic) _Bool reduceBadgeAnimationSpring; // @synthesize reduceBadgeAnimationSpring=_reduceBadgeAnimationSpring;
@property(nonatomic) unsigned long long touchesCount; // @synthesize touchesCount=_touchesCount;
@property(nonatomic) double orientationRotation; // @synthesize orientationRotation=_orientationRotation;
@property(retain, nonatomic) UIView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) DRFlockBadgeLayout *badgeLayout; // @synthesize badgeLayout=_badgeLayout;
@property(retain, nonatomic) NSArray *shownItemModels; // @synthesize shownItemModels=_shownItemModels;
@property(retain, nonatomic) NSArray *itemLayouts; // @synthesize itemLayouts=_itemLayouts;
@property(retain, nonatomic) NSArray *itemViews; // @synthesize itemViews=_itemViews;
// Error: Property attributes should begin with the type ('T') attribute, property name: allViews
// Property attributes: (null)


@end

