//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIWindow.h>

@class NSMapTable;
@protocol DRTouchTrackingWindowDelegate;

@interface DRTouchTrackingWindow : UIWindow
{
    _Bool _tracksTouches;	// 8 = 0x8
    NSMapTable *_velocityIntegratorsByTouch;	// 16 = 0x10
    id <DRTouchTrackingWindowDelegate> _trackingDelegate;	// 24 = 0x18
}

+ (_Bool)_isSecure;	// IMP=0x004000000002a671
- (void).cxx_destruct;	// IMP=0x002000000002b42f
@property(nonatomic) __weak id <DRTouchTrackingWindowDelegate> trackingDelegate; // @synthesize trackingDelegate=_trackingDelegate;
@property(nonatomic) _Bool tracksTouches;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000002b03b
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000002acf5
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000002aae0
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x001000000002a88b
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x001000000002a750
- (id)initWithWindowScene:(id)arg1;	// IMP=0x001000000002a681
- (_Bool)canBecomeKeyWindow;	// IMP=0x001000000002a679

@end

