//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface VOTElementUtilities : NSObject
{
}

+ (long long)findLocationOfDifferenceInOldString:(id)arg1 withNewString:(id)arg2;	// IMP=0x004000000011b8a9
+ (id)handleValueChangeForPhoneDeletionWithOldString:(id)arg1 newString:(id)arg2;	// IMP=0x001000000011b781
+ (id)phoneNumberWithoutFormattingCharacters:(id)arg1;	// IMP=0x001000000011b6f6

@end

