//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface VOTImageExplorerCustomAction
{
}

- (unsigned long long)hash;	// IMP=0x0040000000063e3c
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000063df5
- (_Bool)performWithContext:(id)arg1;	// IMP=0x0010000000063daa
- (_Bool)isValidForContext:(id)arg1;	// IMP=0x0010000000063d95
- (_Bool)ignoreWhenVoiceOverTouches;	// IMP=0x0010000000063d8d
- (id)name;	// IMP=0x0010000000063d70
- (id)init;	// IMP=0x0010000000063d41

@end

