//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface VCPBackgroundAnalysisTask
{
}

- (unsigned long long)missingAnalysisForAsset:(id)arg1 existingAnalysis:(id *)arg2 forLocalResourcesOnly:(_Bool)arg3;	// IMP=0x0040000000073377
- (unsigned long long)possibleAnalysisForAsset:(id)arg1 withResources:(id)arg2 forLocalResourcesOnly:(_Bool)arg3;	// IMP=0x00100000000732a1
- (id)init;	// IMP=0x0010000000073293

@end

