//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface _CRLImageM
{
}

+ (id)initWithImageSourceRef:(struct CGImageSource *)arg1;	// IMP=0x00200000005186b6
+ (id)initWithContentsOfFile:(id)arg1;	// IMP=0x001000000051866d
+ (id)initWithCGImage:(struct CGImage *)arg1 scale:(double)arg2 orientation:(long long)arg3;	// IMP=0x0010000000518628
+ (id)initWithData:(id)arg1;	// IMP=0x00100000005185e1
+ (id)initWithCGImage:(struct CGImage *)arg1;	// IMP=0x00100000005185ae
+ (id)init;	// IMP=0x001000000051859d
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000518592
+ (id)initWithUIImage:(id)arg1;	// IMP=0x0010000000518988

@end

