//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC8Freeform26CRLiOSPopoverTransitioning : NSObject
{
    MISSING_TYPE *isPresenting;	// 8 = 0x8
    MISSING_TYPE *transitionImmediately;	// 9 = 0x9
    MISSING_TYPE *animationDuration;	// 16 = 0x10
    MISSING_TYPE *currentAnimator;	// 24 = 0x18
}

+ (id)transitionControllerForDismissing;	// IMP=0x0020000000b9bc90
+ (id)transitionControllerForPresenting;	// IMP=0x0010000000b9bbf0
- (void).cxx_destruct;	// IMP=0x0040000000b9c540
- (id)init;	// IMP=0x0010000000b9c4e0
- (id)interruptibleAnimatorForTransition:(id)arg1;	// IMP=0x0010000000b9c440
- (void)animateTransition:(id)arg1;	// IMP=0x0010000000b9c3e0
- (double)transitionDuration:(id)arg1;	// IMP=0x0010000000b9c2a0

@end

