//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC8Freeform28CRLRemoteURLMetadataProvider
{
    MISSING_TYPE *navigationDidFinishContinuation;	// 0 = 0x0
    MISSING_TYPE *imageProviderTask;	// 0 = 0x0
    MISSING_TYPE *_image;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x0040000000dd07a0

@end

