//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray;
@protocol CRLiOSInspectorPaneSectionTitle;

@interface _TtCO8Freeform26CRLiOSArrangeInspectorPane26RoundedRectSectionProvider : NSObject
{
    MISSING_TYPE *cellProvider;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0040000000e32460
- (id)init;	// IMP=0x0010000000e32400
- (void)updateCellsInPlaceWith:(id)arg1;	// IMP=0x0010000000e32340
@property(nonatomic, readonly) NSArray *cells;
@property(nonatomic, readonly) _Bool hasCustomShapeUI;
@property(nonatomic, readonly) id <CRLiOSInspectorPaneSectionTitle> sectionTitle;

@end

