//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtCC8Freeform20CRLiOSValueTextField23NumberFormatterDelegate : NSObject
{
    MISSING_TYPE *numberFormatter;	// 8 = 0x8
    MISSING_TYPE *genericNumberFormatter;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0040000000c1a410
- (id)init;	// IMP=0x0010000000c1a3e0
@property(nonatomic, readonly) _Bool valueTextFieldShouldEnforceRightToLeftTextDirection;
- (_Bool)valueTextField:(id)arg1 isValidNumericString:(id)arg2;	// IMP=0x0010000000c19fe0
- (void)valueTextField:(id)arg1 textDidChangeToString:(id)arg2;	// IMP=0x0010000000c19530
- (double)valueTextFieldParsedValueForString:(id)arg1;	// IMP=0x0010000000c194f0
- (id)valueTextFieldFormattedTextForValue:(double)arg1 numericRange:(struct _NSRange *)arg2;	// IMP=0x0010000000c194b0

@end

