//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC8Freeform31CRLUserBoardMetadataDatabaseRow : _TtCs12_SwiftObject
{
    MISSING_TYPE *boardIdentifier;	// 1094999903 = 0x41445f5f
    MISSING_TYPE *crdtData;	// 0 = 0x0
    MISSING_TYPE *isFavorite;	// 22008024 = 0x14fd0d8
    MISSING_TYPE *enableCollaboratorCursors;	// 2288 = 0x8f0
    MISSING_TYPE *lastOpenCrashedVersion;	// 22008024 = 0x14fd0d8
    MISSING_TYPE *viewStateData;	// 0 = 0x0
    MISSING_TYPE *unsyncedChanges;	// 0 = 0x0
    MISSING_TYPE *syncData;	// 0 = 0x0
    MISSING_TYPE *isCanvasDotGridEnabled;	// 1651466079 = 0x626f5f5f
    MISSING_TYPE *isConnectorModeEnabled;	// 1936941420 = 0x7373616c
}

@end

