//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC8Freeform34CRLiOSPopoverTransitioningDelegateP33_5E5F0C675ABFA9CF4D6D5FE95137F3B811PopoverInfo : _TtCs12_SwiftObject
{
    MISSING_TYPE *presentationController;	// 16 = 0x10
    MISSING_TYPE *presentAnimator;	// 24 = 0x18
    MISSING_TYPE *dismissAnimator;	// 32 = 0x20
    MISSING_TYPE *state;	// 40 = 0x28
}

@end

