//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC8Freeform15CRLBoardLibrary : NSObject
{
    MISSING_TYPE *store;	// 8 = 0x8
    MISSING_TYPE *storeHierarchySnapshot;	// 16 = 0x10
    MISSING_TYPE *storeBoardMetadata;	// 24 = 0x18
    MISSING_TYPE *storeFolderHierarchySnapshot;	// 32 = 0x20
    MISSING_TYPE *storeFolderBoardCount;	// 40 = 0x28
    MISSING_TYPE *sharedHighlightController;	// 48 = 0x30
    MISSING_TYPE *boardShareController;	// 56 = 0x38
    MISSING_TYPE *cloudKitObserver;	// 64 = 0x40
    MISSING_TYPE *cloudKitRecordObserver;	// 72 = 0x48
    MISSING_TYPE *userDataDeletionRequestObserver;	// 80 = 0x50
    MISSING_TYPE *databaseSyncObserver;	// 88 = 0x58
    MISSING_TYPE *networkReachabilityListener;	// 96 = 0x60
    MISSING_TYPE *networkReachabilityListenerSubscriptionSet;	// 136 = 0x88
    MISSING_TYPE *isNetworkReachable;	// 144 = 0x90
    MISSING_TYPE *pauseSnapshotUpdateCount;	// 152 = 0x98
    MISSING_TYPE *pendingUpdateOptions;	// 160 = 0xa0
    MISSING_TYPE *snapshotUpdateInterval;	// 0 = 0x0
    MISSING_TYPE *realTimeCollaborationDelegate;	// 14810881 = 0xe1ff01
    MISSING_TYPE *opportunisticGroupSessionManager;	// 1937330991 = 0x7379532f
    MISSING_TYPE *didStartUpdating;	// 0 = 0x0
    MISSING_TYPE *lastOpenCrashedIdentifiersToClear;	// 0 = 0x0
    MISSING_TYPE *snapshot;	// 0 = 0x0
    MISSING_TYPE *maxRecentlyDeleted;	// 0 = 0x0
    MISSING_TYPE *maxRecents;	// 0 = 0x0
    MISSING_TYPE *boardInfos;	// 0 = 0x0
    MISSING_TYPE *shareErrorObservers;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x0040000000e7c980
- (id)init;	// IMP=0x0010000000e8a900
- (void)dealloc;	// IMP=0x0010000000e7c930

@end

