//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC8Freeform26CRLiOSMiniFormatterBuilder : NSObject
{
    MISSING_TYPE *presenter;	// 8 = 0x8
    MISSING_TYPE *element;	// 32 = 0x20
    MISSING_TYPE *editorController;	// 40 = 0x28
    MISSING_TYPE *interactiveCanvasController;	// 48 = 0x30
    MISSING_TYPE *boardItemDataProvider;	// 56 = 0x38
    MISSING_TYPE *crlaxPopoverContainerViewController;	// 64 = 0x40
    MISSING_TYPE *crlaxAccessibilityFormatterLabel;	// 72 = 0x48
}

+ (id)makeSmallButtonWith:(id)arg1 title:(id)arg2 action:(id)arg3 backgroundColor:(id)arg4 pressedBackgroundColor:(id)arg5 foregroundColor:(id)arg6 pressedForegroundColor:(id)arg7 cornerRadius:(double)arg8 italicTitle:(_Bool)arg9;	// IMP=0x0020000000632160
+ (double)defaultRowHeight;	// IMP=0x001000000062e7c0
- (void).cxx_destruct;	// IMP=0x0040000000632ff0
- (id)init;	// IMP=0x0010000000632fa0
- (id)viewControllerForLargeContentViewerInteraction:(id)arg1;	// IMP=0x0010000000632c00

@end

