//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class MISSING_TYPE;

@interface _TtC8FreeformP33_22C834EA6031CC5FD96573982091823D21EncapsulatedImageView : UIView
{
    MISSING_TYPE *imageView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00400000007d12f0
- (void)updateConstraints;	// IMP=0x00100000007d10e0
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000007d1090
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000007d1060

@end

