//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UITextFieldDelegate-Protocol.h"

@class _TtC8Freeform20CRLiOSValueTextField;

@protocol _TtP8Freeform28CRLiOSValueTextFieldDelegate_ <UITextFieldDelegate>
- (_Bool)valueTextFieldMoveToNextResponder:(_TtC8Freeform20CRLiOSValueTextField *)arg1;
- (_Bool)valueTextFieldCanMoveToNextField:(_TtC8Freeform20CRLiOSValueTextField *)arg1;

@optional
- (void)valueTextFieldInfoDidChange:(_TtC8Freeform20CRLiOSValueTextField *)arg1;
@end

