//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLBoardItemImporterPlaceholder
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x0040000000439917
- (id)initWithData:(id)arg1 boardItemFactory:(id)arg2;	// IMP=0x0040000000439a6c
- (id)initWithURL:(id)arg1 boardItemFactory:(id)arg2;	// IMP=0x00100000004399d7

@end

