//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLCanvasLayoutGeometryAccessibility
{
}

+ (Class)crlaxBaseSafeCategoryClass;	// IMP=0x0020000000524a35
+ (id)crlaxTargetClassName;	// IMP=0x0010000000524a28
+ (id)crlaxCastFrom:(id)arg1;	// IMP=0x0010000000524a4f
@property(readonly, nonatomic) struct CGRect _crlaxFrame;
@property(readonly, nonatomic) struct CGSize crlaxSize;
@property(readonly, nonatomic) struct CGPoint crlaxOrigin;
@property(readonly, nonatomic) double crlaxAngleInRadians;
@property(readonly, nonatomic) double crlaxAngleInDegrees;
- (id)crlaxTarget;	// IMP=0x0010000000524a46

@end

