//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CRLCanvasEditor;

@interface CRLDrawableZOrderArranger : NSObject
{
    NSObject<CRLCanvasEditor> *mCanvasEditor;	// 8 = 0x8
    _Bool mCanCoalesceZOrderCommand;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000060e1d1
@property(readonly, nonatomic) __weak NSObject<CRLCanvasEditor> *canvasEditor; // @synthesize canvasEditor=mCanvasEditor;
- (id)p_selectedInfos;	// IMP=0x001000000060e14a
- (unsigned long long)p_zOrderIndex;	// IMP=0x001000000060decc
- (unsigned long long)p_relativeIndexOfChildrenInTopLevelContainer:(id)arg1;	// IMP=0x001000000060ddf2
- (unsigned long long)p_indexOfChildren:(id)arg1 inContainer:(id)arg2;	// IMP=0x001000000060dcf5
- (unsigned long long)p_maxRelativeZValueOfChildrenInTopLevelContainer:(id)arg1;	// IMP=0x001000000060dcaa
- (unsigned long long)p_maxZValueOfChildren:(id)arg1 inContainer:(id)arg2;	// IMP=0x001000000060dbbd
- (unsigned long long)p_maxIndex;	// IMP=0x001000000060d93f
- (unsigned long long)p_minZValueOfChildren:(id)arg1 inContainer:(id)arg2;	// IMP=0x001000000060d877
- (unsigned long long)p_minIndex;	// IMP=0x001000000060d626
- (id)p_zOrderedSelectedObjects;	// IMP=0x001000000060d5a6
- (id)p_zOrderSiblingsForRelativeOrder;	// IMP=0x001000000060c530
- (_Bool)p_usingRelativeZOrder;	// IMP=0x001000000060c496
- (id)p_zOrderSiblings;	// IMP=0x001000000060c1b1
- (unsigned long long)indexOfNextLowerCanvasObject;	// IMP=0x001000000060c08e
- (unsigned long long)indexOfNextHigherCanvasObject;	// IMP=0x001000000060bf66
- (_Bool)shouldShowTextFitOptionsForSelectedDrawables;	// IMP=0x001000000060bf5e
- (_Bool)shouldShowWrapOptionsForSelectedDrawables;	// IMP=0x001000000060bf56
- (_Bool)shouldShowZOrderOptionsForSelectedDrawables;	// IMP=0x001000000060bf4e
- (void)moveToFrontForArrangeInspector;	// IMP=0x001000000060bbf2
- (void)moveFrontForArrangeInspector;	// IMP=0x001000000060b85e
- (void)moveBackForArrangeInspector;	// IMP=0x001000000060b4ca
- (void)moveToBackForArrangeInspector;	// IMP=0x001000000060b16e
- (void)arrangeInspectorDidEndChangingZValue;	// IMP=0x001000000060b098
- (void)arrangeInspectorDidSetZValue:(unsigned long long)arg1 forContainer:(id)arg2;	// IMP=0x001000000060a813
- (void)arrangeInspectorWillBeginChangingZValue;	// IMP=0x001000000060a6c5
- (_Bool)canBringDrawablesForward;	// IMP=0x001000000060a386
- (_Bool)canSendDrawablesBackward;	// IMP=0x001000000060a047
- (unsigned long long)currentZValueForArrangeInspector;	// IMP=0x0010000000609dff
- (unsigned long long)maxZValueForArrangeInspector;	// IMP=0x0010000000609bd6
- (unsigned long long)minZValueForArrangeInspector;	// IMP=0x00100000006099ad
- (_Bool)isZOrderChangeRecord:(id)arg1;	// IMP=0x0010000000609895
- (void)unregisterTargetForChanges:(id)arg1;	// IMP=0x00100000006097d8
- (void)registerTargetForChanges:(id)arg1;	// IMP=0x001000000060971b
- (id)commandToSetZOrderOfInfos:(id)arg1 toIndexes:(id)arg2 coalesceable:(_Bool)arg3;	// IMP=0x0010000000609616
- (id)init;	// IMP=0x0010000000609331
- (id)initWithCanvasEditor:(id)arg1;	// IMP=0x00100000006092cd

@end

