//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLFractionFormat
{
}

- (id)stringFromDouble:(double)arg1 locale:(id)arg2;	// IMP=0x0040000000521b5a

@end

