//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CRLCanvasLayoutGeometry, CRLCanvasRenderable, CRLShapeLayout, NSArray, NSString;
@protocol CRLFreehandDrawingRepTrifurcationContainerDelegate;

@interface CRLFreehandDrawingRepTrifurcationContainer : NSObject
{
    NSObject<CRLFreehandDrawingRepTrifurcationContainerDelegate> *_delegate;	// 8 = 0x8
    struct CGPoint _freehandDrawingInitialUnscaledCanvasFrameOrigin;	// 16 = 0x10
    CRLShapeLayout *_anchorShapeLayoutForTransform;	// 32 = 0x20
    CRLCanvasLayoutGeometry *_anchorShapeLayoutGeometryInRootAtRenderTime;	// 40 = 0x28
    NSArray *_backReps;	// 48 = 0x30
    NSArray *_middleReps;	// 56 = 0x38
    NSArray *_frontReps;	// 64 = 0x40
    CRLCanvasRenderable *_backRenderable;	// 72 = 0x48
    CRLCanvasRenderable *_middleRenderable;	// 80 = 0x50
    CRLCanvasRenderable *_frontRenderable;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x00200000001f4df9
@property(readonly, nonatomic) CRLCanvasRenderable *frontRenderable; // @synthesize frontRenderable=_frontRenderable;
@property(readonly, nonatomic) CRLCanvasRenderable *middleRenderable; // @synthesize middleRenderable=_middleRenderable;
@property(readonly, nonatomic) CRLCanvasRenderable *backRenderable; // @synthesize backRenderable=_backRenderable;
@property(readonly, nonatomic) NSArray *frontReps; // @synthesize frontReps=_frontReps;
@property(readonly, nonatomic) NSArray *middleReps; // @synthesize middleReps=_middleReps;
@property(readonly, nonatomic) NSArray *backReps; // @synthesize backReps=_backReps;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;	// IMP=0x00100000001f4da4
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;	// IMP=0x00100000001f4900
- (struct CGAffineTransform)transformForMiddleRenderable:(_Bool)arg1;	// IMP=0x00100000001f412b
- (void)tearDown;	// IMP=0x00100000001f409f
- (void)p_captureInitialGeometry;	// IMP=0x00100000001f3dde
- (id)p_createRenderable;	// IMP=0x00100000001f3c28
- (id)initWithDelegate:(id)arg1 backReps:(id)arg2 middleReps:(id)arg3 frontReps:(id)arg4;	// IMP=0x00100000001f33ce

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

