//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CRLFeatureFlagsHelper : NSObject
{
}

+ (_Bool)isOSFeatureEnabled:(long long)arg1;	// IMP=0x0040000000279b9c

@end

