//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CRLEditorController, NSSet, NSString, _TtC8Freeform21CRLEditingCoordinator;
@protocol CRLSearchReference;

@interface CRLGroupEditor
{
}

- (void)duplicate:(id)arg1;	// IMP=0x00200000005cf806
- (id)pasteNativeInfosFromPasteboard:(id)arg1;	// IMP=0x00100000005ceee0
- (void)p_pasteBoardItems:(id)arg1 inGroup:(id)arg2 atIndex:(unsigned long long)arg3 forceMatchStyle:(_Bool)arg4 isCrossDocument:(_Bool)arg5;	// IMP=0x00100000005ceaba
- (void)pasteWithPasteboard:(id)arg1 atIndex:(unsigned long long)arg2 forceMatchStyle:(_Bool)arg3 bakeFormulas:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x00100000005cde88
- (void)pasteWithPasteboard:(id)arg1 atIndex:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000005cde63
- (void)pasteWithPasteboard:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00100000005cde34
- (void)pasteValues:(id)arg1;	// IMP=0x00100000005cddba
- (void)pasteAsPlainText:(id)arg1;	// IMP=0x00100000005cdd43
- (void)paste:(id)arg1;	// IMP=0x00100000005cdc95
- (_Bool)canPasteWithPasteboard:(id)arg1;	// IMP=0x00100000005cdbb0
- (_Bool)p_canDuplicateWithSender:(id)arg1;	// IMP=0x00100000005cdaf1
- (long long)editorResponseForCanPasteContentsOfItemSource:(id)arg1;	// IMP=0x00100000005cd998
@property(readonly, nonatomic) _Bool canPasteIntoCurrentlySelectedGroups;
- (_Bool)p_shouldAllowKeyCommands;	// IMP=0x00100000005cd94c
- (void)insertNewline:(id)arg1;	// IMP=0x00100000005cd755
- (_Bool)p_currentlyEditingInGroup;	// IMP=0x00100000005cd6d2
- (void)pasteWithPasteboard:(id)arg1 sender:(id)arg2;	// IMP=0x00100000005cd6b3
- (_Bool)canPasteWithPasteboard:(id)arg1 sender:(id)arg2;	// IMP=0x00100000005cd620
- (long long)canPerformEditorAction:(SEL)arg1 withSender:(id)arg2;	// IMP=0x00100000005cd270
@property(readonly, nonatomic) NSSet *groupItems;
- (void)selectionDidChangeFromSelection:(id)arg1 toSelection:(id)arg2 withFlags:(unsigned long long)arg3;	// IMP=0x00100000005cd0ac
- (id)nextEditorForSelection:(id)arg1 withNewEditorStack:(id)arg2 selectionPath:(id)arg3;	// IMP=0x00100000005cccb8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _TtC8Freeform21CRLEditingCoordinator *editingCoordinator;
@property(readonly, nonatomic) id <CRLSearchReference> editingSearchReference;
@property(retain, nonatomic) CRLEditorController *editorController;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) double liftDelayOverride;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingAccessibilityDescription;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingAttribution;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingCalloutAttributes;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingConnectionLineAttributes;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingEditRecording;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingEndpoints;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingFill;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingFreehandAnimations;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingOpacity;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingReflection;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingReplacement;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingResize;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingShadow;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingShrinkTextToFit;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingSmartShapeAttributes;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingStroke;
@property(readonly, nonatomic) NSSet *selectedObjectsSupportingTextInset;
@property(readonly, nonatomic) _Bool shouldPreventQuickSelect;
@property(readonly) Class superclass;

@end

