//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class UIVisualEffectView;

@interface CRLiOSInspectorAppearanceContainerViewControllerBackgroundView : UIView
{
    UIVisualEffectView *_blurView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000097835
@property(readonly, nonatomic) __weak UIVisualEffectView *blurView; // @synthesize blurView=_blurView;

@end

