//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface CRLiOSValueControlTextField
{
    MISSING_TYPE *parent;	// 400 = 0x190
    MISSING_TYPE *isUpdatingValue;	// 408 = 0x198
}

- (void).cxx_destruct;	// IMP=0x0040000000b794d0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000b79430
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000b793c0
- (void)sendActionsForControlEvents:(unsigned long long)arg1;	// IMP=0x0010000000b79360
@property(nonatomic) double value;

@end

