//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MISSING_TYPE, NSNotification, UIWindow;

@protocol CRLKeyboardObserver <NSObject>
@property(readonly, nonatomic) UIWindow *keyboardObserversWindow;

@optional
- (void)keyboardDidChangeFrame:(NSNotification *)arg1;
- (void)keyboardWillChangeFrame:(NSNotification *)arg1;
- (void)keyboardHideCanceled;
- (void)keyboardDidHideOrUndock:(NSNotification *)arg1;
- (void)keyboardWillHideOrUndock:(NSNotification *)arg1;
- (MISSING_TYPE *)keyboardShowCanceled;
- (void)keyboardDidShowOrDock:(NSNotification *)arg1;
- (void)keyboardWillShowOrDock:(NSNotification *)arg1;
@end

