//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class CRLCanvasRep;
@protocol CRLMaskEditing;

@protocol CRLMaskResizing <NSObject>
- (void)endResizingRepAtScale:(double)arg1;
- (void)updateResizeToScale:(double)arg1;
- (void)beginResizingRep:(CRLCanvasRep<CRLMaskEditing> *)arg1;
@end

