//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CRLPKStrokePathConverter : NSObject
{
}

+ (unsigned long long)countOfBSplineControlPointsForBezierPath:(id)arg1;	// IMP=0x0040000000143ae7
+ (id)pathFromPKStrokePath:(id)arg1 pencilKitStrokePathData:(id *)arg2;	// IMP=0x00100000001439d5
+ (id)strokePathsFromBezierPath:(id)arg1 baseWidth:(double)arg2 strokePathCompactData:(id)arg3 inkType:(id)arg4;	// IMP=0x0010000000143113
+ (id)strokePathDataFromPKStroke:(id)arg1 startingAtIndex:(unsigned long long)arg2 endingAtIndex:(unsigned long long)arg3;	// IMP=0x00100000001411c0

@end

