//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CRLLocale, NSCharacterSet, NSDictionary;

@interface CRLShapeSearchIndex : NSObject
{
    CRLLocale *_locale;	// 8 = 0x8
    NSDictionary *_searchIndex;	// 16 = 0x10
    NSCharacterSet *_whitespaceCharacterSet;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000013d802
@property(retain, nonatomic) NSCharacterSet *p_whitespaceCharacterSet; // @synthesize p_whitespaceCharacterSet=_whitespaceCharacterSet;
@property(copy, nonatomic) NSDictionary *p_searchIndex; // @synthesize p_searchIndex=_searchIndex;
@property(retain, nonatomic) CRLLocale *p_locale; // @synthesize p_locale=_locale;
- (id)p_resultsDictionaryForSearchTerm:(id)arg1 withFilteredKeywords:(id)arg2 shouldPerformDiacriticInsensitiveSearch:(_Bool)arg3;	// IMP=0x001000000013d241
- (id)p_sortedFilteredKeywordsForSearchTerm:(id)arg1 usingPredicate:(id)arg2;	// IMP=0x001000000013d184
- (id)p_predicateWithSearchTerm:(id)arg1 shouldPerformDiacriticInsensitiveSearch:(_Bool)arg2;	// IMP=0x001000000013d091
- (struct _NSRange)p_rangeOfSearchTerm:(id)arg1 inString:(id)arg2 shouldPerformDiacriticInsensitiveSearch:(_Bool)arg3;	// IMP=0x001000000013d064
- (id)p_resultsForSearchTermBasedOnAnchoredSearch:(id)arg1 shouldPerformDiacriticInsensitiveSearch:(_Bool)arg2;	// IMP=0x001000000013cdd4
- (void)p_removeSearchResultWithIdentifier:(id)arg1 forTokenizedKeyword:(id)arg2;	// IMP=0x001000000013cb5a
- (id)p_permuteStrings:(id)arg1;	// IMP=0x001000000013c9c2
- (void)p_tokenizeKeywordIfNeeded:(id)arg1 yieldingKeyword:(CDUnknownBlockType)arg2;	// IMP=0x001000000013c42a
- (id)p_resultsForKeyword:(id)arg1;	// IMP=0x001000000013c391
- (id)p_keywords;	// IMP=0x001000000013c341
- (void)removeSearchResultWithIdentifier:(id)arg1 forKeyword:(id)arg2;	// IMP=0x001000000013c285
- (void)addSearchResults:(id)arg1;	// IMP=0x001000000013b34e
- (void)addSearchResultWithIdentifier:(id)arg1 forKeyword:(id)arg2 priority:(unsigned long long)arg3;	// IMP=0x001000000013adfe
- (id)resultsForSearchTerm:(id)arg1;	// IMP=0x001000000013acaf
- (id)initWithLocale:(id)arg1;	// IMP=0x001000000013abe6

@end

