//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "CRLIOChannel-Protocol.h"

@class OS_dispatch_data;

@protocol CRLStreamWriteChannel <CRLIOChannel>
- (void)flushWithCompletion:(void (^)(NSError *))arg1;
- (void)writeData:(OS_dispatch_data *)arg1 handler:(void (^)(_Bool, unsigned long long, NSError *))arg2;
@end

