//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CRLShapeLayoutAccessibility
{
}

+ (Class)crlaxBaseSafeCategoryClass;	// IMP=0x00200000000fe371
+ (id)crlaxTargetClassName;	// IMP=0x00100000000fe364
+ (id)crlaxCastFrom:(id)arg1;	// IMP=0x00100000000fe38b
- (id)crlaxTarget;	// IMP=0x00100000000fe382

@end

