//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSMutableSet.h>

@interface NSMutableSet (CRLAdditions)
- (void)crl_removeObjectsPassingTest:(CDUnknownBlockType)arg1;	// IMP=0x00100000003c6369
- (void)crl_removeEqualObject:(id)arg1;	// IMP=0x00100000003c61d8
- (void)crl_addObjectsFromNonNilArray:(id)arg1;	// IMP=0x00100000003c61bf
- (void)crl_addNonNilObject:(id)arg1;	// IMP=0x00100000003c61a6
- (void)crl_xorSet:(id)arg1;	// IMP=0x00100000003c6021
@end

