//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CRLGestureTarget;

@interface TSDCachedGestureTargetHolder : NSObject
{
    id <CRLGestureTarget> mWeakCachedGestureTarget;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000003d43c6
@property(nonatomic) __weak id <CRLGestureTarget> weakCachedGestureTarget; // @synthesize weakCachedGestureTarget=mWeakCachedGestureTarget;
- (id)initWithTarget:(id)arg1;	// IMP=0x00100000003d433b

@end

