//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AXDispatchTimer, AXElement, AXElementFetcher, AXElementGroup, NSArray, NSDate, NSMutableArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface HNDAccessibilityManager : NSObject
{
    NSObject<OS_dispatch_queue> *_appTransitionQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_ignoredTouchRegionsQueue;	// 16 = 0x10
    NSMutableDictionary *_pauseCountsByPid;	// 24 = 0x18
    _Bool _initialized;	// 32 = 0x20
    _Bool _isSystemSleeping;	// 33 = 0x21
    _Bool _isPausingScanning;	// 34 = 0x22
    struct __AXObserver *_observer;	// 40 = 0x28
    AXDispatchTimer *_elementFetchQueueTimer;	// 48 = 0x30
    AXElementFetcher *_elementFetcher;	// 56 = 0x38
    NSString *_springboardActionIdentifier;	// 64 = 0x40
    NSMutableArray *_accessibilityObservers;	// 72 = 0x48
    NSDate *_lastAppTransitionTime;	// 80 = 0x50
    AXElementGroup *_rootScannerGroup;	// 88 = 0x58
    AXElement *_axOrbPreviewWindow;	// 96 = 0x60
    AXElementGroup *_elementCommunityGroup;	// 104 = 0x68
    NSArray *_currentApplications;	// 112 = 0x70
    NSArray *_ignoredTouchRegions;	// 120 = 0x78
    NSMutableDictionary *_currentDisplays;	// 128 = 0x80
    NSMutableArray *_currentlyObservingNotifications;	// 136 = 0x88
    NSObject<OS_dispatch_queue> *_notificationObserverQueue;	// 144 = 0x90
    NSArray *__testingElements;	// 152 = 0x98
}

+ (void)_clearExistingSharedManager;	// IMP=0x002000000006ccfa
+ (id)_existingSharedManager;	// IMP=0x001000000006cce9
+ (_Bool)accessibilityEnabled;	// IMP=0x00100000000678b1
+ (id)sharedManager;	// IMP=0x00100000000669fe
- (void).cxx_destruct;	// IMP=0x002000000006cef0
@property(retain, nonatomic, setter=_setTestingElements:) NSArray *_testingElements; // @synthesize _testingElements=__testingElements;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *notificationObserverQueue; // @synthesize notificationObserverQueue=_notificationObserverQueue;
@property(retain, nonatomic) NSMutableArray *currentlyObservingNotifications; // @synthesize currentlyObservingNotifications=_currentlyObservingNotifications;
@property(retain, nonatomic) NSMutableDictionary *currentDisplays; // @synthesize currentDisplays=_currentDisplays;
@property(retain, nonatomic) NSArray *ignoredTouchRegions; // @synthesize ignoredTouchRegions=_ignoredTouchRegions;
@property(retain, nonatomic) NSArray *currentApplications; // @synthesize currentApplications=_currentApplications;
@property(retain, nonatomic) AXElementGroup *elementCommunityGroup; // @synthesize elementCommunityGroup=_elementCommunityGroup;
@property(nonatomic) _Bool isPausingScanning; // @synthesize isPausingScanning=_isPausingScanning;
@property(nonatomic) _Bool isSystemSleeping; // @synthesize isSystemSleeping=_isSystemSleeping;
@property(retain, nonatomic) AXElement *axOrbPreviewWindow; // @synthesize axOrbPreviewWindow=_axOrbPreviewWindow;
@property(retain, nonatomic) AXElementGroup *rootScannerGroup; // @synthesize rootScannerGroup=_rootScannerGroup;
@property(retain, nonatomic) NSDate *lastAppTransitionTime; // @synthesize lastAppTransitionTime=_lastAppTransitionTime;
@property(retain, nonatomic) NSMutableArray *accessibilityObservers; // @synthesize accessibilityObservers=_accessibilityObservers;
@property(retain, nonatomic) NSString *springboardActionIdentifier; // @synthesize springboardActionIdentifier=_springboardActionIdentifier;
@property(retain, nonatomic) AXElementFetcher *elementFetcher; // @synthesize elementFetcher=_elementFetcher;
@property(retain, nonatomic) AXDispatchTimer *elementFetchQueueTimer; // @synthesize elementFetchQueueTimer=_elementFetchQueueTimer;
@property(nonatomic) struct __AXObserver *observer; // @synthesize observer=_observer;
@property(nonatomic) _Bool initialized; // @synthesize initialized=_initialized;
- (void)fetcher:(id)arg1 mediaDidBegin:(struct __CFData *)arg2;	// IMP=0x001000000006ccd4
- (void)fetcher:(id)arg1 screenWillChange:(struct __CFData *)arg2;	// IMP=0x001000000006ccbf
- (void)fetcher:(id)arg1 applicationWasActivated:(id)arg2;	// IMP=0x001000000006ccaa
- (void)fetcher:(id)arg1 updateElementVisuals:(id)arg2;	// IMP=0x001000000006cc95
- (void)fetcher:(id)arg1 nativeFocusElementDidChange:(id)arg2;	// IMP=0x001000000006cc80
- (void)fetcher:(id)arg1 didFetchElementsForEvent:(unsigned long long)arg2 foundNewElements:(_Bool)arg3;	// IMP=0x001000000006c494
- (void)fetcher:(id)arg1 willFetchElementsForEvent:(unsigned long long)arg2 fromApplications:(id)arg3;	// IMP=0x001000000006c379
- (void)fetcher:(id)arg1 didScheduleFetchEvent:(unsigned long long)arg2;	// IMP=0x001000000006c345
- (_Bool)isSystemSleeping:(id)arg1;	// IMP=0x001000000006c2ee
- (struct CGRect)screenFrame:(id)arg1;	// IMP=0x001000000006c2d0
- (void)userDidPerformSwitchAction;	// IMP=0x001000000006c14f
- (void)displaysDidChange:(id)arg1;	// IMP=0x001000000006bf16
- (void)speechEnabledDidChange;	// IMP=0x001000000006beab
- (void)groupingEnabledDidChange;	// IMP=0x001000000006be40
- (long long)_hndAccessibilityEventForFetchEvent:(unsigned long long)arg1;	// IMP=0x001000000006bdce
- (id)scannerElementMatchingElement:(id)arg1;	// IMP=0x001000000006bccb
- (id)firstElementInScene:(id)arg1;	// IMP=0x001000000006b93c
- (id)lastKeyboardElement;	// IMP=0x001000000006b762
- (id)firstKeyboardItem;	// IMP=0x001000000006b698
- (id)previousItemForScanningFromItem:(id)arg1 didWrap:(_Bool *)arg2;	// IMP=0x001000000006b681
- (id)nextItemForScanningFromItem:(id)arg1 didWrap:(_Bool *)arg2;	// IMP=0x001000000006b667
- (id)_itemForScanningFromItem:(id)arg1 inDirection:(_Bool)arg2 didWrap:(_Bool *)arg3;	// IMP=0x001000000006b2ef
- (id)lastItemForScanningWithElementCommunity:(id)arg1;	// IMP=0x001000000006b2db
- (id)firstItemForScanningWithElementCommunity:(id)arg1;	// IMP=0x001000000006b2c4
- (id)_itemForScanningWithElementCommunity:(id)arg1 useFirst:(_Bool)arg2;	// IMP=0x001000000006aff0
- (id)scrollViewsForAction:(int)arg1 elementsToScroll:(id *)arg2;	// IMP=0x001000000006ab1e
- (id)elementsForMatchingBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000006a86d
- (id)scrollViewsForAction:(int)arg1;	// IMP=0x001000000006a859
- (id)firstResponder;	// IMP=0x001000000006a708
- (id)findGroupableMatchingGroupable:(id)arg1;	// IMP=0x001000000006a68e
- (id)elementAtPoint:(struct CGPoint)arg1 displayID:(unsigned int)arg2;	// IMP=0x001000000006a5e2
- (id)elementAtPoint:(struct CGPoint)arg1;	// IMP=0x001000000006a5cb
- (id)rootKeyboardGroup;	// IMP=0x001000000006a57b
- (id)lastScannerGroupable;	// IMP=0x001000000006a4cf
- (id)firstScannerGroupable;	// IMP=0x001000000006a423
- (id)lastScannerElement;	// IMP=0x001000000006a3a9
- (id)firstScannerElement;	// IMP=0x001000000006a32f
- (id)nativeFocusElement;	// IMP=0x001000000006a2df
- (id)elements;	// IMP=0x001000000006a28f
- (void)_handleResumeForPid:(int)arg1;	// IMP=0x0010000000069e4a
- (void)_handlePauseForPid:(int)arg1;	// IMP=0x0010000000069831
- (id)_currentAppPids;	// IMP=0x00100000000695e8
- (id)_pauseReasonForPid:(int)arg1;	// IMP=0x00100000000695c4
- (void)_requestResumeScanning;	// IMP=0x0010000000069454
- (void)_requestPauseScanning;	// IMP=0x00100000000692e3
- (void)_handleRefreshEvent:(long long)arg1 data:(id)arg2;	// IMP=0x00100000000692d1
- (void)_handleValueChanged;	// IMP=0x00100000000692b8
- (void)_handleKeyboardFocusChanged;	// IMP=0x001000000006929f
- (void)_handlePidStatusChanged;	// IMP=0x0010000000069286
- (void)_handleElementScrolledByPage;	// IMP=0x001000000006926d
- (void)_handleElementVisualsUpdated;	// IMP=0x0010000000069254
- (void)_handleKeyboardPopupAppeared;	// IMP=0x001000000006923b
- (void)_handleScrolledByPage;	// IMP=0x0010000000069222
- (void)_handleScreenLocked;	// IMP=0x0010000000069209
- (void)_handleScreenChanged:(id)arg1;	// IMP=0x00100000000691ef
- (void)_handleAnnouncementNotification:(id)arg1;	// IMP=0x0010000000069065
- (void)_handleOrientationChanged;	// IMP=0x001000000006904c
- (void)_handleAlertAppeared;	// IMP=0x0010000000069033
- (void)_handleLayoutChanged:(id)arg1;	// IMP=0x0010000000069019
- (_Bool)willFetchElements;	// IMP=0x0010000000068fd5
- (_Bool)isFetchingElements;	// IMP=0x0010000000068f91
- (void)refreshElements;	// IMP=0x0010000000068f54
- (_Bool)hasZeroElements;	// IMP=0x0010000000068e90
- (_Bool)applicationIsRTL;	// IMP=0x0010000000068dff
- (_Bool)frontmostAppMayBeLoading;	// IMP=0x0010000000068d60
- (void)_handleSystemServerDied;	// IMP=0x0010000000068c98
- (void)_handleFirstResponderChanged;	// IMP=0x0010000000068c7f
- (void)_observeNotifications:(_Bool)arg1;	// IMP=0x001000000006890e
- (void)removeNotificationObserverAndDealloc;	// IMP=0x0010000000068821
- (void)stopObservingAXNotifications:(id)arg1;	// IMP=0x0010000000068497
- (void)observeAXNotifications:(id)arg1;	// IMP=0x0010000000068085
- (_Bool)_isElementInIgnoredTouchRegions:(id)arg1;	// IMP=0x0010000000067cc4
- (void)_initializeAccessibility;	// IMP=0x00100000000678c1
- (void)_enableApplicationAccessibility:(_Bool)arg1;	// IMP=0x0010000000067872
- (void)_notifyObserversMediaDidBegin:(struct __CFData *)arg1;	// IMP=0x001000000006770c
- (void)_notifyObserversScreenWillChange:(struct __CFData *)arg1;	// IMP=0x00100000000675a6
- (void)_notifyObserversApplicationWasActivated:(id)arg1;	// IMP=0x0010000000067425
- (void)_notifyObserversUpdateElementVisuals:(id)arg1;	// IMP=0x00100000000672a4
- (void)_notifyObserversNativeFocusElementDidChange:(id)arg1;	// IMP=0x0010000000067123
- (void)_notifyObserversDidFetchElementsForEvent:(long long)arg1 foundNewElements:(_Bool)arg2;	// IMP=0x0010000000066fa9
- (void)_notifyObserversWillFetchElementsForEvent:(long long)arg1;	// IMP=0x0010000000066e43
- (void)_notifyObserversDidScheduleFetchEvent:(long long)arg1;	// IMP=0x0010000000066cdd
- (void)_notifyObserversDidReceiveEvent:(long long)arg1 data:(id)arg2;	// IMP=0x0010000000066b4e
- (void)removeObserver:(id)arg1;	// IMP=0x0010000000066ae5
- (void)addObserver:(id)arg1;	// IMP=0x0000000000066a67
- (void)_removePostEventFilterFromFetcher:(id)arg1;	// IMP=0x00100000000669e2
- (void)_addPostEventFilterToFetcher:(id)arg1;	// IMP=0x0010000000066646
- (void)_resetPostEventFilterOnFetcher:(id)arg1;	// IMP=0x00100000000665f1
- (id)_setupElementFetcher;	// IMP=0x00100000000664ca
- (void)_initialize;	// IMP=0x0010000000066147
- (void)dealloc;	// IMP=0x0010000000066075
- (void)resetElementFetcher;	// IMP=0x0010000000066029
- (_Bool)isOKToSpeak;	// IMP=0x0010000000065f8e
- (_Bool)_hasCurrentApplicationMatchingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000065f5b
- (id)_currentApplicationMatchingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000065ede
- (id)_applicationMatchingBlock:(CDUnknownBlockType)arg1 inApplications:(id)arg2;	// IMP=0x0010000000065d79
- (_Bool)_elementFetchingRequired;	// IMP=0x0010000000065d21
@property(readonly, nonatomic) _Bool _isSpeechEnabled;
@property(readonly, nonatomic) _Bool _isScannerEnabled;
@property(readonly, nonatomic) _Bool _isGroupingEnabled;
- (id)orbPreviewWindow;	// IMP=0x0010000000065bc4
- (void)updateCachedOrbPreviewWindow:(id)arg1;	// IMP=0x0010000000065aac

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

