//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, NSString;
@protocol SCATHardwareInputSourceDelegate;

@interface SCATHardwareInputSource
{
    char *_hidReportBuffer;	// 8 = 0x8
    _Bool _available;	// 16 = 0x10
    _Bool __useOverrideDeviceCount;	// 17 = 0x11
    unsigned long long __overrideDeviceCount;	// 24 = 0x18
    struct __IOHIDManager *_hidManager;	// 32 = 0x20
    unsigned long long _availabilityDetail;	// 40 = 0x28
    NSDictionary *_persistentSwitchIdentifiers;	// 48 = 0x30
    NSDictionary *_switchDisplayNames;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000000838be
@property(retain, nonatomic) NSDictionary *switchDisplayNames; // @synthesize switchDisplayNames=_switchDisplayNames;
@property(retain, nonatomic) NSDictionary *persistentSwitchIdentifiers; // @synthesize persistentSwitchIdentifiers=_persistentSwitchIdentifiers;
@property(nonatomic) unsigned long long availabilityDetail; // @synthesize availabilityDetail=_availabilityDetail;
@property(nonatomic) struct __IOHIDManager *hidManager; // @synthesize hidManager=_hidManager;
@property(nonatomic) unsigned long long _overrideDeviceCount; // @synthesize _overrideDeviceCount=__overrideDeviceCount;
@property(nonatomic) _Bool _useOverrideDeviceCount; // @synthesize _useOverrideDeviceCount=__useOverrideDeviceCount;
@property(nonatomic, getter=isAvailable) _Bool available; // @synthesize available=_available;
- (void)_removeFakeKeyboardDevice;	// IMP=0x001000000008375d
- (void)_addFakeKeyboardDevice;	// IMP=0x001000000008372b
- (void)updateWithSwitches:(id)arg1 recipe:(id)arg2;	// IMP=0x00100000000831a5
- (void)stopRunning;	// IMP=0x001000000008313a
- (void)startRunning;	// IMP=0x00100000000830b1
- (void)setDelegate:(id)arg1 queue:(id)arg2;	// IMP=0x0010000000083082
- (void)dealloc;	// IMP=0x0010000000083044
- (void)_stopHandlingEvents;	// IMP=0x0010000000082f9f
- (void)_startHandlingEvents;	// IMP=0x0010000000082efa
- (unsigned long long)priority;	// IMP=0x0010000000082eef
- (void)_stopDetectingDevices;	// IMP=0x0010000000082e66
- (void)_startDetectingDevices;	// IMP=0x0010000000082aac
- (id)_matchingCriteria;	// IMP=0x001000000008299d
- (void)_didUpdateAvailability:(_Bool)arg1 withDetail:(unsigned long long)arg2;	// IMP=0x0010000000082836
- (void)_didReceiveActionWithIdentifier:(long long)arg1 start:(_Bool)arg2 ignoreInputHold:(_Bool)arg3;	// IMP=0x001000000008270e
- (_Bool)handledEvent:(id)arg1;	// IMP=0x0010000000082706
@property(readonly, nonatomic) unsigned long long numberOfDevicesConnected;
- (id)switchDisplayNameForButtonNumber:(long long)arg1;	// IMP=0x001000000008268b
- (id)persistentSwitchIdentifierForButtonNumber:(long long)arg1;	// IMP=0x0010000000082683
- (long long)actionIdentifierForButtonNumber:(long long)arg1 withType:(id)arg2;	// IMP=0x001000000008267b
- (long long)switchKeyForSwitch:(id)arg1;	// IMP=0x001000000008266e
@property(readonly, nonatomic) NSString *switchSource;
@property(readonly, nonatomic) _Bool isGamepadInputSource;
@property(readonly, nonatomic) _Bool isATVRemoteInputSource;
@property(readonly, nonatomic) _Bool isKeyboardInputSource;
@property(readonly, nonatomic) _Bool isMIDIInputSource;
@property(readonly, nonatomic) _Bool isMFIInputSource;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) id <SCATHardwareInputSourceDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

