//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AXDispatchTimer;
@protocol SCATActionHandlerDelegate, SCATActionHandlerUIDelegate;

@interface SCATActionHandler : NSObject
{
    long long _action;	// 8 = 0x8
    id <SCATActionHandlerDelegate> _delegate;	// 16 = 0x10
    id <SCATActionHandlerUIDelegate> _uiDelegate;	// 24 = 0x18
    AXDispatchTimer *_actionTimeoutTimer;	// 32 = 0x20
    unsigned long long _actionCount;	// 40 = 0x28
    double _timeoutDuration;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00200000000a859e
@property(nonatomic) double timeoutDuration; // @synthesize timeoutDuration=_timeoutDuration;
@property(nonatomic) unsigned long long actionCount; // @synthesize actionCount=_actionCount;
@property(retain, nonatomic) AXDispatchTimer *actionTimeoutTimer; // @synthesize actionTimeoutTimer=_actionTimeoutTimer;
@property(nonatomic) __weak id <SCATActionHandlerUIDelegate> uiDelegate; // @synthesize uiDelegate=_uiDelegate;
@property(nonatomic) __weak id <SCATActionHandlerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long action; // @synthesize action=_action;
- (void)_resetWithActionSource:(id)arg1;	// IMP=0x00100000000a84a3
- (void)_handleFireActionAndResumeAutoscanning:(_Bool)arg1;	// IMP=0x00100000000a8380
- (_Bool)isPending;	// IMP=0x00100000000a833c
- (void)cancelPendingAction;	// IMP=0x00100000000a81f6
- (void)notifyDidReceiveAction:(id)arg1;	// IMP=0x00100000000a7edd
- (_Bool)_shouldHandleSelectActionImmediately;	// IMP=0x00100000000a7e50
@property(readonly, nonatomic) _Bool shouldShowMenuOnFirstSelectAction;
- (id)initWithAction:(long long)arg1 timeoutDuration:(double)arg2;	// IMP=0x00100000000a7d4d

@end

