//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface SCATBluetoothDevice : NSObject
{
    NSString *_addressString;	// 8 = 0x8
    NSString *_name;	// 16 = 0x10
    _Bool _connected;	// 24 = 0x18
}

+ (id)scatBluetoothDeviceWithDevice:(struct BTDeviceImpl *)arg1 accessoryManager:(struct BTAccessoryManagerImpl *)arg2;	// IMP=0x0040000000090aa5
- (void).cxx_destruct;	// IMP=0x002000000009104e
- (void)customMessageReceived:(int)arg1 withData:(id)arg2;	// IMP=0x0010000000091048
- (void)deviceDisappeared;	// IMP=0x0010000000091042
- (unsigned long long)deviceType;	// IMP=0x001000000009103a
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) _Bool connected;
@property(readonly, nonatomic) NSString *addressString;
- (_Bool)updateWithDevice:(struct BTDeviceImpl *)arg1 error:(id *)arg2;	// IMP=0x0010000000091003
- (id)initWithDevice:(struct BTDeviceImpl *)arg1;	// IMP=0x0010000000090f8b
- (_Bool)_setPropertiesFromDevice:(struct BTDeviceImpl *)arg1 error:(id *)arg2;	// IMP=0x0010000000090db7
- (id)description;	// IMP=0x0010000000090d5a

@end

