//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCFeatureFlagsPayloadHandler
{
}

+ (_Bool)_reapplyConfigurationIncludingPayloads:(id)arg1 excludingPayloads:(id)arg2 error:(id *)arg3;	// IMP=0x0040000000083446
+ (_Bool)_reapplyPayloads:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000082ec2
+ (id)_fullyInstalledPayloads;	// IMP=0x0010000000082e5c
- (void)unsetAside;	// IMP=0x0040000000083e59
- (void)setAside;	// IMP=0x0010000000083cac
- (void)remove;	// IMP=0x0010000000083a49
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x001000000008385d

@end

