//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCNewAPNPayloadHandler
{
}

- (void)didRemoveOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x00400000000460c5
- (void)didInstallOldGlobalRestrictions:(id)arg1 newGlobalRestrictions:(id)arg2;	// IMP=0x00100000000460b3
- (void)_sendNotifications;	// IMP=0x0010000000045fab
- (void)unsetAside;	// IMP=0x0010000000045f3f
- (void)setAside;	// IMP=0x0010000000045ed3
- (void)remove;	// IMP=0x0010000000045e11
- (void)_remove;	// IMP=0x0010000000045d4d
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0010000000045a46
- (_Bool)_hasAPNManagedPreferences;	// IMP=0x00100000000459b6
- (_Bool)_install;	// IMP=0x0010000000045910
- (void)_notifyCoreTelephonyOfAPNChange;	// IMP=0x001000000004584e

@end

