//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MCPasscodeAnalytics : NSObject
{
}

+ (void)sendRecoveryPasscodeClearedEventWithReason:(long long)arg1;	// IMP=0x00400000000842f6
+ (void)sendPasscodeChangedEventWithChangeType:(long long)arg1 oldPasscodeExists:(_Bool)arg2 isClearingPasscode:(_Bool)arg3 newPasscodeUnlockScreenType:(int)arg4 newPasscodeSimpleType:(int)arg5 passcodeRecoverySupported:(_Bool)arg6 passcodeRecoveryRestricted:(_Bool)arg7 recoverySkipped:(_Bool)arg8;	// IMP=0x00100000000842f0

@end

