//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GTTransport_capture;
@protocol OS_dispatch_queue;

@interface GTTransportSource_capture : NSObject
{
    CDUnknownBlockType _messageHandler;	// 8 = 0x8
    CDUnknownBlockType _cancellationHandler;	// 16 = 0x10
    CDUnknownBlockType _registrationHandler;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_mqueue;	// 40 = 0x28
    GTTransport_capture *_transport;	// 48 = 0x30
    struct atomic<int> _state;	// 56 = 0x38
}

- (void)_dispatch:(id)arg1;	// IMP=0x0000000000006d6d
- (void)_cancel;	// IMP=0x0000000000006ce4
- (void)_callCancellationHandler;	// IMP=0x0000000000006ca4
- (void)_register;	// IMP=0x0000000000006c1d
- (void)_callRegistrationHandler;	// IMP=0x0000000000006be8
@property(copy, nonatomic) CDUnknownBlockType registrationHandler;
- (void)setCancellationHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000000006afc
- (CDUnknownBlockType)cancellationHandler;	// IMP=0x0000000000006af2
@property(copy, nonatomic) CDUnknownBlockType messageHandler;
- (_Bool)cancelled;	// IMP=0x0000000000006a6c
- (void)cancel;	// IMP=0x0000000000006a0e
- (void)suspend;	// IMP=0x0000000000006a00
- (void)resume;	// IMP=0x00000000000069f2
- (void)dealloc;	// IMP=0x000000000000696a
- (id)_initWithQueue:(id)arg1 transport:(id)arg2;	// IMP=0x0000000000006769
- (id)init;	// IMP=0x000000000000673e

@end

