//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CloudKit/CKAssetReference.h>

@interface CKAssetReference (CPLCloudKitImplementation)
- (id)cplFingerPrint;	// IMP=0x00100000000f45a4
@end

