//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CloudKit/CKAsset.h>

@interface CKAsset (CPLCloudKitImplementation)
+ (id)cplFingerPrintForSignature:(id)arg1;	// IMP=0x00100000000f450e
- (id)cplFingerPrint;	// IMP=0x00200000000f4541
@end

