//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CloudPhotoLibrary/CPLPlatformObject.h>

@class NSString;

@interface CPLBaseEngineLibrary : CPLPlatformObject
{
}

- (void)getStatusDictionaryWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0020000000047f08
- (void)getStatusWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000047ea2
- (id)componentName;	// IMP=0x0010000000047e95
- (void)closeAndDeactivate:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000047e85
- (void)openWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000047e0b
- (_Bool)createLibraryWithError:(id *)arg1;	// IMP=0x0010000000047d5b

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

