//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CloudPhotoLibrary/CPLMemoryChange.h>

@interface CPLMemoryChange (CPLCloudKitImplementation)
+ (id)ckValueForRelatedRecord:(id)arg1;	// IMP=0x002000000012550a
+ (id)ckPropertyForRelatedIdentifier;	// IMP=0x00100000001254fd
+ (id)ckAssetProperties;	// IMP=0x0010000000125307
- (void)fillMissingCKAssetProperties:(id)arg1 withCKRecord:(id)arg2;	// IMP=0x0010000000125373
- (void)fillWithCKRecord:(id)arg1;	// IMP=0x0010000000128b27
- (void)fillCKRecordBuilder:(id)arg1;	// IMP=0x001000000012c5dd
@end

