//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CPLPrequeliteRemappedRecords
{
}

- (id)remappedRecordEnumeratorInScope:(id)arg1;	// IMP=0x0020000000076f5f
- (_Bool)deleteRecordsForScopeIndex:(long long)arg1 maxCount:(long long)arg2 deletedCount:(long long *)arg3 error:(id *)arg4;	// IMP=0x0010000000076e53
- (_Bool)isRecordWithScopedIdentifierRemapped:(id)arg1;	// IMP=0x0010000000076d2a
- (id)scopedIdentifiersRemappedToScopedIdentifier:(id)arg1;	// IMP=0x0010000000076acf
- (id)realScopedIdentifierForRemappedScopedIdentifier:(id)arg1;	// IMP=0x001000000007695f
- (_Bool)removeRemappedRecordWithScopedIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000076721
- (_Bool)addRemappedRecordWithScopedIdentifier:(id)arg1 realScopedIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x001000000007653d
- (_Bool)fixStorageAfterAnyVersionChange;	// IMP=0x0010000000076394
- (_Bool)upgradeStorageToVersion:(long long)arg1;	// IMP=0x0010000000076252
- (_Bool)initializeStorage;	// IMP=0x0010000000076199

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) _Bool isAlive;
@property(readonly, nonatomic) _Bool isEmpty;
@property(readonly, nonatomic) _Bool shouldIncludeInStatus;
@property(readonly) Class superclass;

@end

