//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ACXDevice, ACXIDSMessaging, NSArray, NSMutableDictionary, NSString;
@protocol ACXDeviceManagerDelegate, OS_dispatch_queue;

@interface ACXDeviceManager : NSObject
{
    id <ACXDeviceManagerDelegate> _delegate;	// 8 = 0x8
    NSMutableDictionary *_devices;	// 16 = 0x10
    ACXDevice *_activePairedDevice;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_internalQueue;	// 32 = 0x20
    ACXIDSMessaging *_legacyMessagingService;	// 40 = 0x28
    ACXIDSMessaging *_currentMessagingService;	// 48 = 0x30
}

+ (id)sharedManager;	// IMP=0x00200000000442c2
- (void).cxx_destruct;	// IMP=0x0020000000045390
@property(readonly, nonatomic) ACXIDSMessaging *currentMessagingService; // @synthesize currentMessagingService=_currentMessagingService;
@property(readonly, nonatomic) ACXIDSMessaging *legacyMessagingService; // @synthesize legacyMessagingService=_legacyMessagingService;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *internalQueue; // @synthesize internalQueue=_internalQueue;
@property(retain, nonatomic) ACXDevice *activePairedDevice; // @synthesize activePairedDevice=_activePairedDevice;
@property(readonly, nonatomic) NSMutableDictionary *devices; // @synthesize devices=_devices;
@property(nonatomic) __weak id <ACXDeviceManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)setSimulatedDevices:(id)arg1 forMessager:(id)arg2;	// IMP=0x0010000000044d3c
@property(readonly, nonatomic) NSArray *allDevices;
- (id)deviceForNRDevice:(id)arg1;	// IMP=0x0010000000044b13
- (id)deviceForPairingID:(id)arg1;	// IMP=0x0010000000044851
- (id)deviceForIDSIdentifier:(id)arg1;	// IMP=0x001000000004465d
- (id)currentActivePairedDevice;	// IMP=0x00100000000444c0
- (void)setLegacyMessagingService:(id)arg1 currentMessagingService:(id)arg2;	// IMP=0x00100000000443b0
- (id)init;	// IMP=0x0010000000044317

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

