//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface PDURLSessionProxyCredential : PBCodable
{
    NSData *_archiveList;	// 8 = 0x8
    unsigned int;	// 16 = 0x10
    CDStruct_f20694ce _has;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x002000000005107e
@property(retain, nonatomic) NSData *archiveList; // @synthesize archiveList=_archiveList;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000050fe6
- (unsigned long long)hash;	// IMP=0x0010000000050f9a
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000050edf
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000050e4b
- (void)copyTo:(id)arg1;	// IMP=0x0010000000050de8
- (void)writeTo:(id)arg1;	// IMP=0x0010000000050d82
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000050d75
- (id)dictionaryRepresentation;	// IMP=0x0010000000050cb5
- (id)description;	// IMP=0x0010000000050c06
@property(readonly, nonatomic) _Bool hasArchiveList;
@property(nonatomic) _Bool hasVersion;
- (id)_actualCredential;	// IMP=0x00100000000466f4
- (id)_initWithActualCredential:(id)arg1;	// IMP=0x0010000000046631

@end

