//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEORouteHypothesisCache, NSMutableArray, NSMutableDictionary, NSMutableSet, NSOperationQueue, NSString, NavdProactiveLocalProxy;

@interface NavdTTLCache : NSObject
{
    GEORouteHypothesisCache *_cache;	// 8 = 0x8
    NSMutableDictionary *_pendingEntriesByKey;	// 16 = 0x10
    NSMutableArray *_entries;	// 24 = 0x18
    NSOperationQueue *_cacheOperationQueue;	// 32 = 0x20
    NavdProactiveLocalProxy *_localProxy;	// 40 = 0x28
    _Bool _shouldPostDarwinNotificationForNextUpdate;	// 48 = 0x30
    NSMutableSet *;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000006f1c
- (void)callHandlers:(id)arg1 withHypothesis:(id)arg2;	// IMP=0x0010000000006ce8
- (void)removeEntry:(id)arg1 withKey:(id)arg2 value:(id)arg3;	// IMP=0x0010000000006c7f
- (void)saveValue:(id)arg1 forKey:(id)arg2;	// IMP=0x0010000000006c69
- (id)loadEntryForRowId:(long long)arg1;	// IMP=0x0010000000006c53
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;	// IMP=0x0010000000006c3d
- (void)didPostUINotification:(unsigned long long)arg1 forDestination:(id)arg2 client:(id)arg3 osTransaction:(id)arg4;	// IMP=0x00100000000068f0
- (void)_resolvedMapItem:(id)arg1 toPostUINotification:(unsigned long long)arg2 forDestination:(id)arg3 client:(id)arg4 osTransaction:(id)arg5;	// IMP=0x00100000000066fd
- (void)stopMonitoringDestination:(id)arg1 forClient:(id)arg2 uuid:(id)arg3 osTransaction:(id)arg4;	// IMP=0x0010000000006345
- (void)_resolvedMapItem:(id)arg1 toStopMonitoringPlannedDestination:(id)arg2 clientInfo:(id)arg3 uuid:(id)arg4 osTransaction:(id)arg5;	// IMP=0x0010000000005bb9
- (void)onlyPerformLocalUpdatesForPlannedDestination:(id)arg1 client:(id)arg2 osTransaction:(id)arg3;	// IMP=0x00100000000058f7
- (void)_resolvedMapItem:(id)arg1 toOnlyPerformLocalUpdatesForPlannedDestination:(id)arg2 client:(id)arg3 osTransaction:(id)arg4;	// IMP=0x0010000000005730
- (void)requestRefreshForPlannedDestination:(id)arg1 client:(id)arg2 osTransaction:(id)arg3;	// IMP=0x001000000000546e
- (void)_resolvedMapItem:(id)arg1 toRefreshPlannedDestination:(id)arg2 client:(id)arg3 osTransaction:(id)arg4;	// IMP=0x001000000000522e
- (void)_resolvedOriginWaypoint:(id)arg1 originWaypointError:(id)arg2 destinationWaypoint:(id)arg3 destinationWaypointError:(id)arg4 forKey:(id)arg5 pendingCacheEntry:(id)arg6 osTransaction:(id)arg7 clientInfo:(id)arg8;	// IMP=0x0010000000004867
- (void)_resolvedMapItem:(id)arg1 error:(id)arg2 forPendingCacheEntry:(id)arg3 uuid:(id)arg4 osTransaction:(id)arg5 clientInfo:(id)arg6;	// IMP=0x0010000000004120
- (void)startMonitoringDestination:(id)arg1 forClient:(id)arg2 uuid:(id)arg3 osTransaction:(id)arg4 handler:(CDUnknownBlockType)arg5;	// IMP=0x0010000000003f11
- (double)nextRefreshTimeStamp;	// IMP=0x0010000000003efb
- (void)shouldPostDarwinNotificationForNextUpdate:(_Bool)arg1;	// IMP=0x0010000000003e38
- (id)findEntryForKey:(id)arg1;	// IMP=0x0010000000003bee
- (id)descriptionOfAllEntries;	// IMP=0x0010000000003bd8
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;	// IMP=0x0010000000003bc2
- (id)entryAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000003bac
@property(readonly, nonatomic) unsigned long long count;
- (id)init;	// IMP=0x0010000000003b6b
- (id)initWithCacheOperationQueue:(id)arg1 localProxy:(id)arg2;	// IMP=0x0010000000003987

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

