//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface NavdAnalytics : NSObject
{
}

- (void)recordHypothesisCountPerHypothesizer:(unsigned long long)arg1;	// IMP=0x00200000000323a2
- (void)recordInitialTravelTime:(double)arg1;	// IMP=0x0010000000032389
- (void)recordETAUpdatesAfterEventStart:(unsigned long long)arg1;	// IMP=0x001000000003236d
- (void)recordHypothesisReroutes:(unsigned long long)arg1;	// IMP=0x0010000000032351
- (void)recordUniqueHypothesis;	// IMP=0x0010000000032333
- (void);	// IMP=0x00100000000322b9
- (void)recordEarlyDepartureDelta:(double)arg1 lateDepartureDelta:(double)arg2 earlyArrivalDelta:(double)arg3 lateArrivalDelta:(double)arg4 rerouteCount:(unsigned long long)arg5 uiNotification:(unsigned long long)arg6;	// IMP=0x001000000003227f
- (void)addValueForKey:(const char *)arg1 value:(unsigned long long)arg2;	// IMP=0x0010000000032152

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

