//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol OS_os_transaction;

@interface NavdOsTransaction : NSObject
{
    NSObject<OS_os_transaction> *_osTransaction;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000329d6
- (void)dealloc;	// IMP=0x001000000003289d
- (void)endTransaction;	// IMP=0x001000000003270c
- (id)initWithTransactionName:(const char *)arg1;	// IMP=0x0010000000032612

@end

