//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC9appstored18SkannerCoordinator : NSObject
{
    MISSING_TYPE *storyMetrics;	// 8 = 0x8
    MISSING_TYPE *databaseStore;	// 48 = 0x30
}

+ (id)sharedInstance;	// IMP=0x0020000000016570
- (void).cxx_destruct;	// IMP=0x0040000000019b60
- (id)init;	// IMP=0x0010000000019b00
- (void)flushPendingEvents;	// IMP=0x0010000000019240
- (void)completeStoryForAdvertisedAppAdamID:(long long)arg1;	// IMP=0x0010000000017cd0
- (void)logEvents:(id)arg1 forAdvertisedAppAdamID:(long long)arg2;	// IMP=0x0010000000017860
- (void)logEvent:(id)arg1 forAdvertisedAppAdamID:(long long)arg2;	// IMP=0x0010000000017390
- (void)startStoryIfNeededWith:(id)arg1 forAdvertisedAppAdamID:(long long)arg2;	// IMP=0x0010000000017330

@end

