//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC9appstored13MetricsBridge : NSObject
{
}

+ (id)metricsFieldsFrom:(id)arg1 taskMetrics:(id)arg2 error:(id)arg3 session:(id)arg4;	// IMP=0x0020000000045450
+ (id)metricsFieldsFromResult:(id)arg1;	// IMP=0x00100000000453e0
+ (void)enqueueAppInstallationEventWithEvent:(id)arg1;	// IMP=0x0010000000045360
- (id)init;	// IMP=0x0040000000045520

@end

