//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class _TtC9appstored6LogKey;

@interface AppInstallEntity
{
    _TtC9appstored6LogKey *_logKey;	// 8 = 0x8
    _Bool _isAutomatic;	// 16 = 0x10
    _Bool _isUpdate;	// 17 = 0x11
    _Bool _isRestore;	// 18 = 0x12
    unsigned long long _coordinatorIntent;	// 24 = 0x18
}

+ (Class)memoryEntityClass;	// IMP=0x00400000001268b7
+ (id)disambiguatedSQLForProperty:(id)arg1;	// IMP=0x001000000012673e
+ (id)databaseTable;	// IMP=0x0010000000126731
+ (id)foreignKeyColumnForTable:(id)arg1;	// IMP=0x0010000000126337
+ (id)foreignDatabaseTablesToDelete;	// IMP=0x00100000001262c7
- (void).cxx_destruct;	// IMP=0x00200000001268c8
- (_Bool)deleteFromDatabase;	// IMP=0x0010000000125322

@end

