//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AKAuthorizationController, NSArray, NSString;

@interface AppPurgeCoordinator : NSObject
{
    AKAuthorizationController *_authorizationController;	// 8 = 0x8
    NSArray *_cachedBundleIDDenyList;	// 16 = 0x10
    NSArray *_managedBundleIDs;	// 24 = 0x18
    NSArray *_watchAppList;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000008c4a3
- (long long)purgeForVolume:(id)arg1 urgency:(long long)arg2 desiredPurge:(id)arg3 client:(id)arg4;	// IMP=0x001000000008b28f
- (long long)purgeableForVolume:(id)arg1 urgency:(long long)arg2 client:(id)arg3;	// IMP=0x001000000008b277
- (void)cacheInvalidated;	// IMP=0x001000000008b037
- (id)allPurgeablesForVolume:(id)arg1 reason:(id)arg2 client:(id)arg3;	// IMP=0x001000000008a8a1
- (id)init;	// IMP=0x0010000000085898

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

