//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSLock, NSNumber;
@protocol OS_dispatch_queue;

@interface FamilyManager : NSObject
{
    NSNumber *_currentAccountDSID;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatch;	// 16 = 0x10
    NSArray *_familyAccountIDs;	// 24 = 0x18
    NSArray *_familyMembers;	// 32 = 0x20
    double _lastFamilyCheck;	// 40 = 0x28
    NSLock *_lock;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_notificationQueue;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0020000000284f3d
- (void)_handleAccountChangedNotification;	// IMP=0x001000000028465a
- (id)init;	// IMP=0x00100000002835c7

@end

