//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface InstallAttributionWebParams : NSObject
{
    NSNumber *_appAdamId;	// 8 = 0x8
    NSString *_adNetworkRegistrableDomain;	// 16 = 0x10
    NSString *_impressionId;	// 24 = 0x18
    NSString *_sourceWebRegistrableDomain;	// 32 = 0x20
    NSString *_version;	// 40 = 0x28
    NSNumber *_timestamp;	// 48 = 0x30
    long long _attributionContext;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x002000000013ee70

@end

