//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MigratorArcadeTask
{
}

- (void)main;	// IMP=0x004000000023feff
- (id)migratorType;	// IMP=0x001000000023feee
- (id)copyConfiguration;	// IMP=0x001000000023fece
- (id)initWithConfiguration:(id)arg1;	// IMP=0x001000000023fe9f

@end

