//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class KeepAlive, NSNumber, URLBag, XPCRequestToken, _TtC9appstored6LogKey;

@interface PurchaseHistoryUpdateCommand : NSObject
{
    URLBag *_bag;	// 8 = 0x8
    _TtC9appstored6LogKey *_logKey;	// 16 = 0x10
    KeepAlive *_keepAlive;	// 24 = 0x18
    unsigned long long _context;	// 32 = 0x20
    NSNumber *_accountID;	// 40 = 0x28
    NSNumber *_expectedItemID;	// 48 = 0x30
    NSNumber *_serverRevision;	// 56 = 0x38
    XPCRequestToken *_requestToken;	// 64 = 0x40
    CDUnknownBlockType _replyHandler;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x002000000010eb9e

@end

