//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MapsSupport/MSPSyncManager.h>

@class CyclePreferences, DrivePreferences, MISSING_TYPE, NPSManager, NSLock, NSString, PSYSyncCoordinator, TransitPreferences;
@protocol NMCSyncManagerDelegate;

@interface NMCSyncManager : MSPSyncManager
{
    PSYSyncCoordinator *_coordinator;	// 8 = 0x8
    NPSManager *_preferencesSyncManager;	// 16 = 0x10
    DrivePreferences *_drivePreferences;	// 24 = 0x18
    CyclePreferences *_cyclePreferences;	// 32 = 0x20
    TransitPreferences *_transitPreferences;	// 40 = 0x28
    _Bool _waitingOnInternalInitialSync;	// 48 = 0x30
    _Bool _waitingOnDelegateInitialSync;	// 49 = 0x31
    NSLock *_waitingOnInitialSyncLock;	// 56 = 0x38
    id <NMCSyncManagerDelegate> _delegate;	// 64 = 0x40
}

+ (id)pinsPath;	// IMP=0x0020000000038e48
+ (id)nanoRegistryDirectory;	// IMP=0x0010000000038dc0
+ (id)mapsDirectory;	// IMP=0x0010000000038ce3
- (void).cxx_destruct;	// IMP=0x002000000003a10c
@property(nonatomic) __weak id <NMCSyncManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)syncCoordinator:(id)arg1 beginSyncSession:(id)arg2;	// IMP=0x0010000000039be8
- (void)synchronizePreferences;	// IMP=0x0010000000039b04
- (MISSING_TYPE *)requestSyncUpdateWithReply: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000039ac6
- (void)notifyObservers;	// IMP=0x0010000000039a7a
- (void)completedSync;	// IMP=0x00100000000398d8
- (void)_completedInitialSync;	// IMP=0x00100000000397bd
- (void)completedPreparingSync;	// IMP=0x00100000000396a2
- (void)preparingSync;	// IMP=0x00100000000395bd
- (void)writePins:(id)arg1;	// IMP=0x00100000000394ad
- (id)readPins;	// IMP=0x0010000000039207
- (id)_containerCompletionQueue;	// IMP=0x0010000000039181
- (id)initWithDelegate:(id)arg1;	// IMP=0x0010000000038f85
- (id)init;	// IMP=0x0010000000038f71
- (void)_createNanoRegistryDirectoryIfNeeded;	// IMP=0x0010000000038e9f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

