//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSConstantValueExpression.h>

@interface NSConstantValueExpression (PredicateBindings)
- (id)cr_sqlBindings;	// IMP=0x0010000000016043
- (id)cr_expressionValue;	// IMP=0x0010000000016031
@end

