//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NADEntityStore, NSFileManager, NSMutableDictionary, NSURL;
@protocol OS_dispatch_queue;

@interface NADApplicationStore : NSObject
{
    NSMutableDictionary *_storeMetadata;	// 8 = 0x8
    NSMutableDictionary *_parentBundleIDToWatchAppMap;	// 16 = 0x10
    NSMutableDictionary *_bundleIDToApplicationMap;	// 24 = 0x18
    unsigned long long _stateHandle;	// 32 = 0x20
    NSURL *_applicationDirectory;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_queue;	// 48 = 0x30
    NSFileManager *_fileManager;	// 56 = 0x38
    NADEntityStore *_applicationStore;	// 64 = 0x40
}

+ (id)defaultURL;	// IMP=0x0040000000001684
+ (id)legacyDefaultURL;	// IMP=0x00100000000015d3
+ (id)defaultStore;	// IMP=0x0010000000001558
- (void).cxx_destruct;	// IMP=0x00200000000030d9
@property(readonly, nonatomic) NADEntityStore *applicationStore; // @synthesize applicationStore=_applicationStore;
@property(readonly, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) NSURL *applicationDirectory; // @synthesize applicationDirectory=_applicationDirectory;
- (struct os_state_data_s *)stateDataWithHints:(struct os_state_hints_s *)arg1;	// IMP=0x0010000000002e5c
- (void)performTransactionWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000002de1
- (id)beginTransaction;	// IMP=0x0010000000002dab
- (void)_writeStoreMetadata;	// IMP=0x0010000000002c37
- (id)_storeMetadataURL;	// IMP=0x0010000000002bde
- (id)description;	// IMP=0x0010000000002b3c
- (id)sequenceNumber;	// IMP=0x0010000000002b1f
- (void)setSequenceNumber:(id)arg1 UUID:(id)arg2;	// IMP=0x0010000000002a5c
- (id)UUID;	// IMP=0x0010000000002a3f
- (id)_allApplicationsIncludingHidden:(_Bool)arg1;	// IMP=0x0010000000002880
- (void)_removeApplicationFromCache:(id)arg1;	// IMP=0x00100000000027b8
- (void)_removeApplicationWithBundleIdentifier:(id)arg1;	// IMP=0x001000000000274f
- (id)watchAppIDsForParentBundleID:(id)arg1;	// IMP=0x00100000000026bc
- (void)_insertApplicationIntoCache:(id)arg1;	// IMP=0x00100000000025f1
- (void)_insertApplication:(id)arg1;	// IMP=0x001000000000258f
- (void)_resetStores;	// IMP=0x0010000000002579
- (void)_loadEntitiesFromDisk;	// IMP=0x001000000000243e
- (void)getAllApplications:(out id *)arg1 UUID:(out id *)arg2 sequenceNumber:(out id *)arg3 includeHidden:(_Bool)arg4;	// IMP=0x00100000000022e2
- (id)allApplicationsIncludingHidden:(_Bool)arg1;	// IMP=0x0010000000002144
- (id)_applicationBundleIdentifiersForParentApplicationBundleIdentifier:(id)arg1;	// IMP=0x00100000000020f0
- (void)removeApplicationsWithParentApplicationBundleIdentifier:(id)arg1;	// IMP=0x0010000000001f6b
- (void)removeApplicationWithBundleIdentifier:(id)arg1;	// IMP=0x0010000000001ef1
- (void)insertApplication:(id)arg1;	// IMP=0x0010000000001e77
- (void)removeAllEntities;	// IMP=0x0010000000001db2
- (id)initWithURL:(id)arg1;	// IMP=0x0010000000001850
- (id)init;	// IMP=0x00100000000015bf

@end

