//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CMFSyncAgentDataStore;

@interface CommunicationsFilterBlockListStore : NSObject
{
    id <CMFSyncAgentDataStore> _dataStore;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x00400000000017f5
@property(readonly, nonatomic) id <CMFSyncAgentDataStore> dataStore; // @synthesize dataStore=_dataStore;
- (void)handleNSUbiquitousKeyValueStoreDidChangeExternallyNotification:(id)arg1;	// IMP=0x001000000000309b
- (void)_stopSharingFocusStatusWithFilterItem:(id)arg1;	// IMP=0x0010000000002ee8
- (void)_updateStore:(id)arg1 revision:(unsigned long long)arg2 updateKVS:(_Bool)arg3 updateLocal:(_Bool)arg4 itemsNeedConversion:(_Bool)arg5;	// IMP=0x0010000000002a08
- (_Bool)isItemInList:(id)arg1;	// IMP=0x0010000000002927
- (id)_isItemInList:(id)arg1 blockList:(id)arg2;	// IMP=0x00100000000027fe
- (id)_copyItems:(_Bool)arg1;	// IMP=0x0010000000002744
- (id)copyAllItems;	// IMP=0x0010000000002730
- (id)copyAllItemsAsDictionaries;	// IMP=0x0010000000002719
- (_Bool)removeItemForAllServices:(id)arg1;	// IMP=0x00100000000025f7
- (_Bool)addItemForAllServices:(id)arg1;	// IMP=0x0010000000001d4a
- (void)_storeDidChangeExternally;	// IMP=0x0010000000001ce0
- (void)updateDataStore;	// IMP=0x0010000000001b63
- (void)synchronizeDataStore;	// IMP=0x0010000000001ac8
- (void)migrateLegacyDataStoreIfNeeded;	// IMP=0x001000000000193e
- (void)dealloc;	// IMP=0x0010000000001903
- (id)init;	// IMP=0x001000000000183a

@end

