//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NBBackupiCloud, NSArray, NSMutableDictionary;

@interface NBBackupIndexManager : NSObject
{
    NSArray *_allBackups;	// 8 = 0x8
    NSMutableDictionary *_metadataIndex;	// 16 = 0x10
    NBBackupiCloud *_iCloudBackup;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000006f77
@property(retain, nonatomic) NBBackupiCloud *iCloudBackup; // @synthesize iCloudBackup=_iCloudBackup;
@property(retain, nonatomic) NSMutableDictionary *metadataIndex; // @synthesize metadataIndex=_metadataIndex;
@property(readonly, nonatomic) NSArray *allBackups; // @synthesize allBackups=_allBackups;
- (id)newBackupUUID;	// IMP=0x0010000000006e14
- (id)pathToBackupIndex;	// IMP=0x0010000000006d8a
- (id)persistMetadataIndex;	// IMP=0x0010000000006b13
- (id)_metadataIndexReadFromDiskIfNeeded;	// IMP=0x00100000000069bf
- (id)metadataIndexReadFromDiskIfNeeded;	// IMP=0x0010000000006966
- (void)removeICloudBackupsFromIndex;	// IMP=0x00100000000067a2
- (_Bool)shouldLoadiCloudBackups;	// IMP=0x00100000000065f6
- (void)loadiCloudBackups:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000006022
- (void)purgeCache;	// IMP=0x0010000000005fe5
- (void)deleteBackupWithID:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000005b05
- (void)createNewBackup:(CDUnknownBlockType)arg1;	// IMP=0x001000000000586c
- (id)pathToBackupID:(id)arg1;	// IMP=0x00100000000057d9
- (id)pathToBackup:(id)arg1;	// IMP=0x0010000000005777
- (void)backupForID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000055ea
- (void)localBackupsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000053fa
- (void)iCloudBackupsWithTimeout:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000005163
- (void)allBackupsWithTimeout:(long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000004e94
- (id)initWithiCloudBackup:(id)arg1;	// IMP=0x0010000000004e29

@end

