//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSString;

@interface CLClientManagerAdapter
{
}

+ (id)getSilo;	// IMP=0x0020000000475548
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000047552f
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x00100000004754d2
- (void)calculateCheeseCoverage:(id)arg1 interestInterval:(id)arg2 withOptions:(id)arg3 lookbackWindowStartDate:(id)arg4 withReply:(CDUnknownBlockType)arg5;	// IMP=0x002000000047eb96
- (void)handleLiveActivityUpdate:(id)arg1;	// IMP=0x001000000047eb90
- (void)triggerAnalyticsCollect;	// IMP=0x001000000047eb38
- (void)triggerClearAppClipAuthorizationIfNecessary;	// IMP=0x001000000047e19e
- (double)syncgetAndSetOrChangeAppClipAuthorizationTime:(double)arg1 forClient:(CDUnknownBlockType)arg2;	// IMP=0x001000000047dc71
- (id)syncgetTemporaryAuthorizationStatusForClient:(CDUnknownBlockType)arg1;	// IMP=0x001000000047d5f4
- (void)setTemporaryAuthorizationStatusInfoForClient:(CDUnknownBlockType)arg1 data:(id)arg2;	// IMP=0x001000000047c435
- (void)handleProvisionalIntermediationForService:(unsigned long long)arg1 forClientKey:(id)arg2 at:(id)arg3 withReply:(CDUnknownBlockType)arg4;	// IMP=0x001000000047c2a4
- (void)checkWeakPersistentClientWithIdentifier:(CDUnknownBlockType)arg1;	// IMP=0x001000000047c22f
- (id)syncgetArchivedAuthorizationDecisions;	// IMP=0x001000000047c215
- (id)syncgetApplyArchivedAuthorizationDecisionsAndDie:(id)arg1 unlessTokenMatches:(id)arg2;	// IMP=0x001000000047c1e9
- (_Bool)syncgetIsMapsANonSystemLocationClient;	// IMP=0x001000000047c0f2
- (_Bool)syncgetHasAuthorizedClients;	// IMP=0x001000000047bf12
- (void)setLocationButtonUseMode:(int)arg1 forClient:(CDUnknownBlockType)arg2;	// IMP=0x001000000047be0c
- (void)setIncidentalUseMode:(int)arg1 forClient:(CDUnknownBlockType)arg2;	// IMP=0x001000000047bd06
- (void)deleteInterestZoneWithId:(id)arg1 registeredForClientKey:(id)arg2 withReply:(CDUnknownBlockType)arg3;	// IMP=0x001000000047b77e
- (void)setRelevance:(_Bool)arg1 forInterestZoneWithId:(id)arg2 registeredForClientKey:(id)arg3;	// IMP=0x001000000047b6b0
- (void)setRelevance:(_Bool)arg1 forInterestZoneWithId:(id)arg2 registeredForClientKey:(id)arg3 withReply:(CDUnknownBlockType)arg4;	// IMP=0x001000000047b175
- (void)registerPhenolicInterestZoneForClientKey:(id)arg1 withId:(id)arg2 phenolicLocation:(int)arg3 serviceMaskOperator:(int)arg4 provenanceType:(int)arg5 withReply:(CDUnknownBlockType)arg6;	// IMP=0x001000000047b06c
- (void)registerCircularInterestZoneForClientKey:(id)arg1 withId:(id)arg2 latitude:(double)arg3 longitude:(double)arg4 serviceMaskOperator:(int)arg5 provenanceType:(int)arg6 radius:(double)arg7 withReply:(CDUnknownBlockType)arg8;	// IMP=0x001000000047a217
- (void)getIncidentalUseModeForClient:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x001000000047a10f
- (int)syncgetRegistrationResultToAuthorizationStatus:(int)arg1;	// IMP=0x0010000000479edc
- (int)syncgetClientEffectiveRegistrationResultWithTransientAwareness:(CDUnknownBlockType)arg1;	// IMP=0x0010000000479dde
- (int)syncgetClientStaticRegistrationResult:(CDUnknownBlockType)arg1;	// IMP=0x0010000000479ce0
- (id)syncgetNonSystemLocationClientKey;	// IMP=0x0010000000479a8b
- (id)syncgetNonSystemLocationClientKeys;	// IMP=0x0010000000479983
- (void)fetchLocationClientKeysWithReply:(CDUnknownBlockType)arg1;	// IMP=0x0010000000479953
- (id)syncgetLocationClientKeys;	// IMP=0x001000000047984c
- (id)syncgetCopyClients;	// IMP=0x0010000000478efa
- (void)setAllowableAuthorizationMask:(unsigned long long)arg1 forClientKey:(id)arg2;	// IMP=0x0010000000478927
- (void)appsWithClientKeysAreInstalledOnAPairedDevice:(id)arg1;	// IMP=0x00100000004787db
- (void)checkAppInstallationStatus;	// IMP=0x00100000004787c1
- (_Bool)syncgetSetLocationServicesEnabledStatically:(_Bool)arg1 withEventSource:(id)arg2;	// IMP=0x0010000000478736
- (void)setPurpose:(id)arg1 forClient:(CDUnknownBlockType)arg2;	// IMP=0x00100000004785d7
- (void)setClient:(CDUnknownBlockType)arg1;	// IMP=0x00100000004784cb
- (void)resetClients;	// IMP=0x00100000004784b1
- (void)resetClient:(id)arg1;	// IMP=0x0010000000478467
- (MISSING_TYPE *)reportLocationUtilityEvent:atDate: /* Error: Ran out of types for this method. */;	// IMP=0x001000000047843b
- (void)setLastLocationSettingsEventSource:(id)arg1;	// IMP=0x00100000004783b4
- (void)setClientAuthorization:(CDUnknownBlockType)arg1 zoneIdentifier:(id)arg2 subIdentityIdentifier:(id)arg3 status:(int)arg4 correctiveCompensation:(int)arg5 mayIncreaseAuth:(_Bool)arg6 entity:(id)arg7;	// IMP=0x0010000000478232
- (void)setClientBackgroundIndicator:(CDUnknownBlockType)arg1 enabled:(_Bool)arg2 entity:(id)arg3;	// IMP=0x0010000000477f3a
- (void)resetNotificationConsumedForIdentifier:(id)arg1;	// IMP=0x00100000004779c2
- (void)performMigrationWithReply:(CDUnknownBlockType)arg1;	// IMP=0x001000000047695c
- (void)appLaunchedByAppLifecycleManager:(id)arg1;	// IMP=0x0010000000476528
- (void)wakeUpLaunchdManagedClient:(id)arg1;	// IMP=0x001000000047648e
- (void)onCapabilityChange;	// IMP=0x0010000000476469
- (void)markReceivingLocationInformation:(CDUnknownBlockType)arg1;	// IMP=0x0010000000476364
- (void)reduceAccuracy:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000004762c3
- (void)inUseAssertionInvalidatedDueToWatchConnectivityForClientKey:(id)arg1;	// IMP=0x0010000000476279
- (void)takeInUseAssertionForClientKey:(id)arg1 reason:(id)arg2 assertionLevel:(int)arg3 withReply:(CDUnknownBlockType)arg4;	// IMP=0x00100000004760ca
- (void)markClientEmergencyEnablementTransition:(_Bool)arg1 shouldOverrideDeauthorization:(_Bool)arg2 forBeneficiary:(id)arg3;	// IMP=0x0010000000476050
- (void)markClientEmergencyEnablementTransition:(_Bool)arg1;	// IMP=0x0010000000476027
- (void)markClientTemporaryAuthorizationGranted:(_Bool)arg1 forClientKey:(id)arg2 andAuditToken:(CDStruct_6ad76789)arg3 byLocationButton:(_Bool)arg4 voiceInteractionEnabled:(_Bool)arg5;	// IMP=0x0010000000475fc0
- (void)updatePromptedLatitude:(double)arg1 longitude:(double)arg2;	// IMP=0x0010000000475f77
- (void)updatePillButtonChoiceForOutstandingPrompt:(int)arg1;	// IMP=0x0010000000475f55
- (void)considerPromptingForTranscriptSession:(id)arg1 dictionary:(id)arg2 requestType:(int)arg3 withReply:(CDUnknownBlockType)arg4;	// IMP=0x0010000000475ef1
- (void)setClients:(id)arg1 locationPushTo:(_Bool)arg2;	// IMP=0x0010000000475dbb
- (void)setClients:(id)arg1 significantLocationVisitTo:(_Bool)arg2;	// IMP=0x0010000000475c55
- (void)setClients:(id)arg1 transcriptSessionChangeTo:(_Bool)arg2;	// IMP=0x0010000000475b1f
- (void)setClients:(id)arg1 significantLocationChangeTo:(_Bool)arg2;	// IMP=0x00100000004759e8
- (void)setClients:(id)arg1 regionOfType:(int)arg2 to:(_Bool)arg3;	// IMP=0x0010000000475880
- (void)setProvisionalAuthorization:(id)arg1;	// IMP=0x001000000047571d
- (void)dingAllActiveTranscriptSubscriptions;	// IMP=0x00100000004756fd
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00100000004756d5
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00100000004756a8
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000475680
- (void *)adaptee;	// IMP=0x001000000047564d
- (void)endService;	// IMP=0x0010000000475632
- (void)beginService;	// IMP=0x00100000004755e1
- (id)init;	// IMP=0x00100000004755a4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

