//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString;
@protocol CLIntersiloUniverse, CLRoutineMonitorServiceProtocol;

@interface CLHLocationClassifier : NSObject
{
    id <CLIntersiloUniverse> _universe;	// 8 = 0x8
    id <CLRoutineMonitorServiceProtocol> _routineMonitor;	// 16 = 0x10
    NSDate *_lastLocationsOfInterestFetchDate;	// 24 = 0x18
    _Bool _locationsOfInterestFetchError;	// 32 = 0x20
    int _numConsecutiveFetchErrors;	// 36 = 0x24
    int _numFetchesOfLocationsOfInterest;	// 40 = 0x28
    _Bool valid;	// 44 = 0x2c
    NSArray *_homeLocations;	// 48 = 0x30
    NSArray *_workLocations;	// 56 = 0x38
    NSArray *_schoolLocations;	// 64 = 0x40
    NSArray *_gymLocations;	// 72 = 0x48
}

@property(retain, nonatomic) NSArray *gymLocations; // @synthesize gymLocations=_gymLocations;
@property(retain, nonatomic) NSArray *schoolLocations; // @synthesize schoolLocations=_schoolLocations;
@property(retain, nonatomic) NSArray *workLocations; // @synthesize workLocations=_workLocations;
@property(retain, nonatomic) NSArray *homeLocations; // @synthesize homeLocations=_homeLocations;
@property(nonatomic) _Bool valid; // @synthesize valid;
- (id)jsonObject;	// IMP=0x0010000000e1b903
- (void)dealloc;	// IMP=0x0010000000e1b886
- (long long)loiTypeForLocation:(id)arg1;	// IMP=0x0010000000e1b337
- (void)fetchLocationsOfInterestIfPossibleWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000e1a810
- (void)updateLocationsOfInterestFetchTimestamp;	// IMP=0x0010000000e1a7d9
- (_Bool)shouldFetchLocationsOfInterest;	// IMP=0x0010000000e1a748
- (double)getLocationsOfInterestFetchTimeInterval;	// IMP=0x0010000000e1a72d
- (id)initInUniverse:(id)arg1;	// IMP=0x0010000000e1a651
- (id)init;	// IMP=0x0010000000e1a621

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

