//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface CLPressureBiasAdapter
{
}

+ (id)getSilo;	// IMP=0x0020000000afd606
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000afd5ed
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000afd590
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x0020000000afd7da
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x0010000000afd7ad
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x0010000000afd785
- (void *)adaptee;	// IMP=0x0010000000afd752
- (void)endService;	// IMP=0x0010000000afd737
- (void)beginService;	// IMP=0x0010000000afd69f
- (id)init;	// IMP=0x0010000000afd662

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

