//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CLWaterStateInterface : NSObject
{
}

- (_Bool)isWaterStateON;	// IMP=0x0040000000865ccb
- (void)disconnect;	// IMP=0x0010000000865cc5
- (void)connect;	// IMP=0x0010000000865cbf
- (id)init;	// IMP=0x0010000000865c90

@end

