//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSDate;

@interface CMMotionTimeRange
{
    NSDate *fStartDate;	// 16 = 0x10
    NSDate *fEndDate;	// 24 = 0x18
}

+ (CDStruct_2c43369c)CLMotionTimeRangeFromCMMotionTimeRange:(id)arg1;	// IMP=0x0040000000d38480
+ (id)CMMotionTimeRangeFromCLMotionTimeRange:(CDStruct_2c43369c)arg1;	// IMP=0x0010000000d3843b
+ (_Bool)supportsSecureCoding;	// IMP=0x0010000000d38272
@property(readonly, nonatomic) NSDate *endDate;
@property(readonly, nonatomic) NSDate *startDate;
- (id)description;	// IMP=0x0010000000d3839d
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000d3833e
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000d3827a
- (MISSING_TYPE *)copyWithZone: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000d381ea
- (void)dealloc;	// IMP=0x0010000000d38192
- (id)initWithStartDate:(double)arg1 endDate:(double)arg2;	// IMP=0x0010000000d380ec

@end

