//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray;

@interface TRANSITPbLocationFingerprintsV1 : PBCodable
{
    NSMutableArray *_locationFingerprints;	// 8 = 0x8
}

@property(retain, nonatomic) NSMutableArray *locationFingerprints; // @synthesize locationFingerprints=_locationFingerprints;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000c2e0ef
- (unsigned long long)hash;	// IMP=0x0010000000c2e0d2
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000c2e078
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000c2ded5
- (void)copyTo:(id)arg1;	// IMP=0x0010000000c2de4b
- (void)writeTo:(id)arg1;	// IMP=0x0010000000c2dd45
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000c2dd38
- (id)dictionaryRepresentation;	// IMP=0x0010000000c2d997
- (id)description;	// IMP=0x0010000000c2d920
- (id)locationFingerprintAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000c2d903
- (unsigned long long)locationFingerprintsCount;	// IMP=0x0010000000c2d8e6
- (void)addLocationFingerprint:(id)arg1;	// IMP=0x0010000000c2d899
- (void)clearLocationFingerprints;	// IMP=0x0010000000c2d87c
- (void)dealloc;	// IMP=0x0010000000c2d83c

@end

