//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData;

@interface MockAKSRefKey : PBCodable
{
    NSData *_key;	// 8 = 0x8
    NSData *_optionalParams;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000000cf9d
@property(retain, nonatomic) NSData *optionalParams; // @synthesize optionalParams=_optionalParams;
@property(retain, nonatomic) NSData *key; // @synthesize key=_key;
- (void)mergeFrom:(id)arg1;	// IMP=0x001000000000cef0
- (unsigned long long)hash;	// IMP=0x001000000000cea3
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000cdeb
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000cd4d
- (void)copyTo:(id)arg1;	// IMP=0x001000000000ccea
- (void)writeTo:(id)arg1;	// IMP=0x001000000000cc8d
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000cb23
- (id)dictionaryRepresentation;	// IMP=0x001000000000caa0
- (id)description;	// IMP=0x001000000000c9f1
@property(readonly, nonatomic) _Bool hasOptionalParams;
@property(readonly, nonatomic) _Bool hasKey;

@end

