//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class PDFThumbnailView, PDFView, _SSSPDFPageMiniMapView;

@interface _SSSPDFThumbnailView : UIView
{
    PDFView *_pdfView;	// 8 = 0x8
    _SSSPDFPageMiniMapView *_miniMapView;	// 16 = 0x10
    PDFThumbnailView *_thumbnailView;	// 24 = 0x18
    struct CGRect _scrollViewVisibleRectInPDFView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000415af
@property(retain, nonatomic) PDFThumbnailView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
@property(retain, nonatomic) _SSSPDFPageMiniMapView *miniMapView; // @synthesize miniMapView=_miniMapView;
@property(nonatomic) struct CGRect scrollViewVisibleRectInPDFView; // @synthesize scrollViewVisibleRectInPDFView=_scrollViewVisibleRectInPDFView;
@property(retain, nonatomic) PDFView *pdfView; // @synthesize pdfView=_pdfView;
- (void)createMiniMapView;	// IMP=0x001000000004148f
- (void)createThumbnailView;	// IMP=0x001000000004137f
- (_Bool)shouldUseMiniMapView;	// IMP=0x001000000004132b
- (_Bool)shouldShowThumbnailOptionView;	// IMP=0x00100000000412ed
- (_Bool)isShowingThumbnailOptionView;	// IMP=0x00100000000412c8
@property(nonatomic) _Bool shouldUpdate;
- (void)layoutSubviews;	// IMP=0x001000000004102e

@end

