//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSLock, NSMutableDictionary;

@interface GTMutableShaderProfilerStreamData
{
    NSLock *_addLock;	// 232 = 0xe8
    NSMutableDictionary *_perRingBufferAPSData;	// 240 = 0xf0
    NSMutableDictionary *_perRingBufferAPSCounterData;	// 248 = 0xf8
    NSMutableDictionary *_perRingBufferAPSTimelineData;	// 256 = 0x100
}

+ (id)dataFromArchivedDataURL:(id)arg1;	// IMP=0x0040000000060a12
- (void).cxx_destruct;	// IMP=0x00200000000609bf
- (unsigned long long)addString:(id)arg1;	// IMP=0x00100000000608cd
- (void)optimizeStreamData;	// IMP=0x00100000000604b8
- (void)setBatchIdFilterableCounters:(id)arg1;	// IMP=0x0010000000060485
- (_Bool)addBatchIdFilteredCounterData:(id)arg1;	// IMP=0x00100000000603ab
- (void)removeAPSCounterData;	// IMP=0x001000000006035a
- (void)removeAPSTimelineData;	// IMP=0x0010000000060309
- (void)removeAPSData;	// IMP=0x00100000000602b8
- (_Bool)addAPSCounterData:(id)arg1;	// IMP=0x00100000000601cf
- (_Bool)addAPSTimelineData:(id)arg1;	// IMP=0x00100000000600e6
- (_Bool)addAPSData:(id)arg1;	// IMP=0x001000000005fffd
- (void)_archiveRingBufferAPSData;	// IMP=0x001000000005f89f
- (_Bool)_addIfAPSBufferData:(id)arg1 withData:(id)arg2;	// IMP=0x001000000005f6c3
- (_Bool)addGPUTimelineData:(id)arg1;	// IMP=0x001000000005f5e9
- (_Bool)addShaderProfilerData:(id)arg1;	// IMP=0x001000000005f50f
- (void)setDataSourceHasUnusedResources:(_Bool)arg1 captureRange:(struct _NSRange)arg2;	// IMP=0x001000000005f4f5
- (void)setNumBlitCalls:(unsigned long long)arg1;	// IMP=0x001000000005f4eb
- (void)addShaderFunctionInfo:(CDStruct_74271b70 *)arg1 count:(unsigned long long)arg2;	// IMP=0x001000000005f48f
- (void)addCommandBuffers:(CDStruct_0ef168c5 *)arg1 count:(unsigned long long)arg2;	// IMP=0x001000000005f437
- (void)addPipelineStates:(CDStruct_71113f05 *)arg1 count:(unsigned long long)arg2;	// IMP=0x001000000005f3db
- (void)addEncoders:(CDStruct_71113f05 *)arg1 count:(unsigned long long)arg2;	// IMP=0x001000000005f37f
- (void)addGPUCommands:(CDStruct_0b014dd4 *)arg1 count:(unsigned long long)arg2;	// IMP=0x001000000005f327
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000005f2f8
- (id)init;	// IMP=0x001000000005f0fe

@end

