//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSSet;
@protocol GTXPCConnection;

@interface GTURLAccessProviderXPCProxy : NSObject
{
    id <GTXPCConnection> _connection;	// 8 = 0x8
    NSSet *_ignoreMethods;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000000ded3
- (id)urlForPath:(id)arg1;	// IMP=0x001000000000dd81
- (void)copyIdentifier:(id)arg1 toDevice:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000000dba4
- (void)transferIdentifier:(id)arg1 toDevice:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000000d9eb
- (id)makeURL:(id)arg1;	// IMP=0x001000000000d856
- (void)securityScopedURLFromSandboxID:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000000d634
- (_Bool)respondsToSelector:(SEL)arg1;	// IMP=0x001000000000d5af
- (id)initWithConnection:(id)arg1 remoteProperties:(id)arg2;	// IMP=0x001000000000d3cf

@end

