//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class APSConnection, IDSService, NSArray, NSString;
@protocol MapsPushDelegate;

@interface MapsPushManager : NSObject
{
    IDSService *_service;	// 8 = 0x8
    NSArray *_devices;	// 16 = 0x10
    APSConnection *_apsConnection;	// 24 = 0x18
    CDUnknownBlockType _devicePushTokenCompletion;	// 32 = 0x20
    id <MapsPushDelegate> _delegate;	// 40 = 0x28
}

+ (id)fakeDevicesFromNames:(id)arg1;	// IMP=0x002000000000bc93
+ (id)defaultManager;	// IMP=0x0010000000008c60
- (void).cxx_destruct;	// IMP=0x002000000000c80c
@property(copy, nonatomic) CDUnknownBlockType devicePushTokenCompletion; // @synthesize devicePushTokenCompletion=_devicePushTokenCompletion;
@property(retain, nonatomic) APSConnection *apsConnection; // @synthesize apsConnection=_apsConnection;
@property(nonatomic) __weak id <MapsPushDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSArray *devices; // @synthesize devices=_devices;
- (void)mapsInstallStateDidChange:(_Bool)arg1;	// IMP=0x001000000000c6c6
- (void)service:(id)arg1 account:(id)arg2 incomingMessage:(id)arg3 fromID:(id)arg4;	// IMP=0x001000000000c005
- (void)service:(id)arg1 devicesChanged:(id)arg2;	// IMP=0x001000000000bf78
- (void)service:(id)arg1 activeAccountsChanged:(id)arg2;	// IMP=0x001000000000beeb
- (void)fetchProblemStatus:(id)arg1 problemReportIDs:(id)arg2 manifestToken:(id)arg3;	// IMP=0x001000000000b6ba
- (void)sendRAPStatusChangeNotification:(id)arg1;	// IMP=0x001000000000b61e
- (void)simulateUGCPhotoAttributionClearedNotification;	// IMP=0x001000000000b5da
- (void)simulateUGCPhotoSubmissionResolution;	// IMP=0x001000000000b31f
- (void)simulateRAPStatusChange;	// IMP=0x001000000000b126
- (void)simulateProblemResolution;	// IMP=0x001000000000b02a
- (id)_simulatedProblemResolutionResponse;	// IMP=0x001000000000afb5
- (id)_simulatedNotification;	// IMP=0x001000000000af64
- (id);	// IMP=0x001000000000ae29
- (id)_simulatedDetails;	// IMP=0x001000000000ac90
- (id)_simulatedPlace;	// IMP=0x001000000000ac2f
- (void)registerForMapsICloudPushTopic;	// IMP=0x001000000000ab28
- (id)devicePushToken;	// IMP=0x001000000000a84f
@property _Bool shouldUseDevAPNS;
- (void)setUpPushConnection;	// IMP=0x001000000000a60e
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;	// IMP=0x0010000000009f99
- (void)connection:(id)arg1 didFailToSendOutgoingMessage:(id)arg2 error:(id)arg3;	// IMP=0x0010000000009f82
- (void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4;	// IMP=0x0010000000009ef0
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;	// IMP=0x0010000000009eea
- (long long)_priorityForMessageOfType:(long long)arg1;	// IMP=0x0010000000009ecf
- (void)_handleGenericIDSMessage:(id)arg1;	// IMP=0x0010000000009d10
- (void)propagateIDSMessageOfType:(long long)arg1 message:(id)arg2;	// IMP=0x001000000000982d
- (void)pushItem:(id)arg1 toDevice:(id)arg2;	// IMP=0x0010000000009361
- (void)_updateDevices;	// IMP=0x0010000000008e48
- (void)dealloc;	// IMP=0x0010000000008dd3
- (id)init;	// IMP=0x0010000000008ce5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

