//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MDState, MapsPushManager, NSString, RAPSubmissionStatusSyncHandler;

@interface MDDevicePushManager : NSObject
{
    MDState *_state;	// 8 = 0x8
    MapsPushManager *_pushManager;	// 16 = 0x10
    RAPSubmissionStatusSyncHandler *_syncHandler;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000001044f
- (void)clearRAPStatusChangeNotificationWithManager:(id)arg1;	// IMP=0x0010000000010409
- (void)pushManager:(id)arg1 receivedClearedPhotoAttributionNotificationWithTitle:(id)arg2 message:(id)arg3;	// IMP=0x0010000000010381
- (void)pushManager:(id)arg1 receivedPhotoLivenessMUID:(id)arg2 title:(id)arg3 message:(id)arg4 actionURL:(id)arg5;	// IMP=0x00100000000102da
- (void)pushManager:(id)arg1 receivedRAPStatusChangeNotification:(id)arg2;	// IMP=0x001000000001026a
- (void)pushManager:(id)arg1 receivedFixedProblemNotification:(id)arg2 manifestToken:(id)arg3;	// IMP=0x001000000000fef9
- (void)pushManager:(id)arg1 gotPushData:(id)arg2;	// IMP=0x001000000000fbae
- (void)_cleanupRAPNotifications;	// IMP=0x001000000000f9eb
- (_Bool)_shouldDisplayNotificationForProblemStatus:(id)arg1;	// IMP=0x001000000000f944
- (void)simulateRAPStatusChangeNotification;	// IMP=0x001000000000f92e
- (void)simulateUGCPhotoAttributionClearedNotification;	// IMP=0x001000000000f918
- (void)simulateUGCPhotoSubmissionResolution;	// IMP=0x001000000000f902
- (void);	// IMP=0x001000000000f8ec
- (id)devicePushToken;	// IMP=0x001000000000f8d6
- (void)dealloc;	// IMP=0x001000000000f880
- (id)initWithState:(id)arg1;	// IMP=0x001000000000f7ad

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

