//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC9ShortcutsP33_8E1323D63AD4BC68B7B06E8F57FAAD4419ResourceBundleClass : _TtCs12_SwiftObject
{
}

@end

