//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionReusableView.h>

@class MISSING_TYPE;

@interface _TtCC9Shortcuts21LibraryViewController18SectionDividerView : UICollectionReusableView
{
    MISSING_TYPE *divider;	// 8 = 0x8
    MISSING_TYPE *leadingConstraint;	// 16 = 0x10
    MISSING_TYPE *trailingConstraint;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x004000000006bf40
- (void)layoutMarginsDidChange;	// IMP=0x001000000006bde0
- (void)layoutSubviews;	// IMP=0x001000000006bd30
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000006bcc0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000006bca0

@end

