//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface WFDebugUtilities : NSObject
{
}

+ (void)startLogStream;	// IMP=0x0020000000021660
+ (void)setupDebuggingForWindow:(id)arg1;	// IMP=0x0010000000021630
- (id)init;	// IMP=0x00400000000216c0

@end

