//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate;
@protocol _BDSNotificationConnectionListening;

@interface BDSNotificationConnection : NSObject
{
    struct os_unfair_lock_s _unfairLock;	// 8 = 0x8
    id <_BDSNotificationConnectionListening> _listener;	// 16 = 0x10
    NSDate *_lastConnectionDate;	// 24 = 0x18
}

+ (_Bool)isWithinConnectionDateRange;	// IMP=0x00200000000672e2
- (void).cxx_destruct;	// IMP=0x00200000000679dd
@property(retain, nonatomic) NSDate *lastConnectionDate; // @synthesize lastConnectionDate=_lastConnectionDate;
@property(nonatomic) struct os_unfair_lock_s unfairLock; // @synthesize unfairLock=_unfairLock;
@property(retain, nonatomic) id <_BDSNotificationConnectionListening> listener; // @synthesize listener=_listener;
- (void)handleNotification:(id)arg1;	// IMP=0x0010000000067812
- (void)didAcceptConnection:(id)arg1;	// IMP=0x0010000000067711
- (void)startListeningForNotifications;	// IMP=0x00100000000676d4
- (id)init;	// IMP=0x0010000000067463

@end

