//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSManagedObjectID, NSString, RMDebounceTimer, RMStatusQuerier;
@protocol RMStatusEngineDelegate;

@interface RMStatusEngine : NSObject
{
    id <RMStatusEngineDelegate> _delegate;	// 8 = 0x8
    NSManagedObjectContext *_context;	// 16 = 0x10
    NSManagedObjectID *_managementSourceObjectID;	// 24 = 0x18
    RMStatusQuerier *_statusQuerier;	// 32 = 0x20
    RMDebounceTimer *_debouncer;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0010000000077f58
@property(retain, nonatomic) RMDebounceTimer *debouncer; // @synthesize debouncer=_debouncer;
@property(retain, nonatomic) RMStatusQuerier *statusQuerier; // @synthesize statusQuerier=_statusQuerier;
@property(retain, nonatomic) NSManagedObjectID *managementSourceObjectID; // @synthesize managementSourceObjectID=_managementSourceObjectID;
@property(retain, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
@property(nonatomic) __weak id <RMStatusEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (void)acknowledgeStatusSubscriptions:(id)arg1;	// IMP=0x00100000000774e4
- (id)_queryForStatusWithLastReceivedDateByKeyPath:(id)arg1 lastAcknowledgedDateByKeyPath:(id)arg2;	// IMP=0x001000000007719e
- (id)_queryForStatusSubscriptionsReturningOnlyUnacknowledgedOnes:(_Bool)arg1;	// IMP=0x00100000000765e4
- (void)clearAllLastAcknowledgedDate;	// IMP=0x001000000007617f
- (id)queryForStatusSubscriptionsWithKeyPaths:(id)arg1;	// IMP=0x0010000000075ba3
- (id)queryForStatusWithKeyPaths:(id)arg1;	// IMP=0x00100000000753dc
- (id)queryForStatusSubscriptionsWithIdentifiers:(id)arg1;	// IMP=0x0010000000074ddb
- (id)queryForStatusSubscriptions;	// IMP=0x0010000000074dc7
- (id)queryForUnacknowledgedStatusSubscriptions;	// IMP=0x0010000000074db0
- (void)_notifyDelegateOfUnacknowledgedStatusSubscriptionsIfNeeded;	// IMP=0x0010000000074b13
- (void)_statusDidChange:(id)arg1;	// IMP=0x0010000000074a26
- (void)triggerAggregatingTimerAction;	// IMP=0x0010000000074a14
- (void)start;	// IMP=0x00100000000748ec
- (id)initWithManagementSourceObjectID:(id)arg1 statusQuerier:(id)arg2 inContext:(id)arg3;	// IMP=0x00100000000747ec
- (void)_subscribeToStatusKeyPaths:(id)arg1 sourceType:(short)arg2;	// IMP=0x0010000000077fcd
- (void)subscribeToStatusKeyPathsThenStopAfterAcknowledged:(id)arg1;	// IMP=0x0010000000077fb6
- (void)implicitlySubscribeToStatusKeyPaths:(id)arg1;	// IMP=0x0010000000077f9f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

