//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIWindow.h>

@class NSString;

@interface UIWindow (DebugHierarchyAdditionsFallback)
+ (id)fallback_debugHierarchyValueForPropertyWithName:(id)arg1 onObject:(id)arg2 outOptions:(id *)arg3 outError:(id *)arg4;	// IMP=0x001000000001ca09
+ (id)fallback_debugHierarchyPropertyDescriptions;	// IMP=0x001000000001c686
+ (id)fallback_debugHierarchyObjectsInGroupWithID:(id)arg1 onObject:(id)arg2 outOptions:(id *)arg3;	// IMP=0x001000000001c4d4
+ (id)fallback_debugHierarchyAdditionalGroupingIDs;	// IMP=0x001000000001c457
+ (id)fallback_debugHierarchyObjectsInGroupWithID:(id)arg1 outOptions:(id *)arg2;	// IMP=0x001000000001c408
+ (id)fallback_debugHierarchyGroupingIDs;	// IMP=0x001000000001c3a1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

