//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC7remindd41RDSuggestedAttributesAutoTrainingActivity : NSObject
{
    MISSING_TYPE *identifier;	// 8 = 0x8
    MISSING_TYPE *executionDateStorage;	// 24 = 0x18
    MISSING_TYPE *$__lazy_storage_$_throttlingPolicy;	// 64 = 0x40
    MISSING_TYPE *babysitter;	// 104 = 0x68
    MISSING_TYPE *states;	// 144 = 0x90
    MISSING_TYPE *configs;	// 160 = 0xa0
    MISSING_TYPE *executable;	// 200 = 0xc8
}

- (void).cxx_destruct;	// IMP=0x00400000006be7d0
- (id)init;	// IMP=0x00100000006be770
- (id)waiterID;	// IMP=0x00100000006be170

@end

