//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, NSOrderedSet, NSSet, NSString, REMAccountTypeHost;

@interface REMCDAccount
{
    REMAccountTypeHost *_accountTypeHost;	// 32 = 0x20
}

+ (id)cdEntityName;	// IMP=0x002000000006cc52
+ (id)predicateForCloudKitAccountsWithKeyPathPrefix:(id)arg1;	// IMP=0x001000000006ca09
+ (_Bool)isAbstract;	// IMP=0x001000000006ca01
+ (id)keyPathsForValuesAffectingEffectiveMinimumSupportedVersion;	// IMP=0x001000000006d5dd
+ (id)fetchRequest;	// IMP=0x001000000008895e
+ (id)accountByCKIdentifierFrom:(id)arg1;	// IMP=0x00100000000af426
+ (id)accountsMatchingPredicate:(id)arg1 context:(id)arg2;	// IMP=0x00100000000af414
+ (id)_unitTest_randomPersonIDSalt;	// IMP=0x00100000000af3fb
+ (_Bool)clearAppleCloudKitTable;	// IMP=0x00100000000aef6a
+ (id)cloudKitAccountWithCKIdentifier:(id)arg1 context:(id)arg2;	// IMP=0x00100000000ae945
+ (id)accountWithCKIdentifier:(id)arg1 context:(id)arg2;	// IMP=0x00100000000ae7d3
+ (id)unsafeUntilSystemReady_primaryCloudKitAccountInContext:(id)arg1 appleAccountUtilities:(id)arg2;	// IMP=0x00100000000ade7f
+ (id)_groundTruth_primaryActiveCloudKitAccountInContext:(id)arg1;	// IMP=0x00100000000adb15
+ (unsigned long long)countCloudBasedAccountsInContext:(id)arg1;	// IMP=0x00100000000ad8f9
+ (id)allCloudKitAccountsInContext:(id)arg1;	// IMP=0x00100000000ad467
+ (id)_fetchCloudKitAccountsInContext:(id)arg1;	// IMP=0x00100000000acfb5
+ (void)initialize;	// IMP=0x00100000000acf5e
+ (_Bool)shouldAttemptLocalObjectMerge;	// IMP=0x00100000006f6b50
+ (void)writeMigrationStateTo:(id)arg1 didChooseToMigrate:(_Bool)arg2 didFinishMigration:(_Bool)arg3;	// IMP=0x00100000006f6a70
+ (void)clearUserRecord:(id)arg1;	// IMP=0x00100000006f6a40
+ (id)newCloudObjectForRecord:(id)arg1 accountID:(id)arg2 context:(id)arg3;	// IMP=0x00100000006f2640
+ (id)allCloudObjectIDsInContext:(id)arg1;	// IMP=0x00100000006f2200
+ (id)allCloudObjectsInContext:(id)arg1;	// IMP=0x00100000006f20f0
+ (id)existingCloudObjectForRecordID:(id)arg1 accountID:(id)arg2 context:(id)arg3;	// IMP=0x00100000006f1f60
+ (id)recordTypes;	// IMP=0x00100000006f1850
- (void).cxx_destruct;	// IMP=0x001000000006d159
- (_Bool)postAccountPropertyChangeNotificationWithKey:(id)arg1 changedValue:(id)arg2;	// IMP=0x001000000006cecb
@property(retain, nonatomic) NSData *listIDsMergeableOrdering; // @dynamic listIDsMergeableOrdering;
@property(retain, nonatomic) NSData *personIDSalt;
- (long long)compare:(id)arg1;	// IMP=0x001000000006cb5d
- (id)accountTypeHost;	// IMP=0x001000000006cab1
- (void)debug_lowLevelRemoveFromParent;	// IMP=0x001000000006d606
- (long long)parentEffectiveMinimumSupportedVersion;	// IMP=0x001000000006d5f6
- (_Bool)shouldCascadeMarkAsDeleteInto:(id)arg1 forRelationship:(id)arg2;	// IMP=0x001000000006d4c7
- (_Bool)isConnectedToAccountObject:(id)arg1;	// IMP=0x001000000006d4bf
- (_Bool)generateAndSavePersonIDSaltIfNeededWithContext:(id)arg1;	// IMP=0x00100000000aefc9
- (_Bool)shouldUseResolutionTokenMapForMergingData;	// IMP=0x00100000006f1720
- (void)cleanUpAfterLocalObjectMerge;	// IMP=0x00100000006f8470
- (_Bool)mergeWithLocalObject:(id)arg1;	// IMP=0x00100000006f6b90
- (id)existingLocalObjectToMergeWithPredicate:(id)arg1;	// IMP=0x00100000006f6b70
- (_Bool)shouldBeDeletedFromLocalDatabase;	// IMP=0x00100000006f6a30
- (_Bool)needsToBePushedToCloud;	// IMP=0x00100000006f69e0
- (_Bool)needsToBeDeletedFromCloud;	// IMP=0x00100000006f68f0
- (id)newlyCreatedRecord;	// IMP=0x00100000006f68a0
- (void)mergeDataFromRecord:(id)arg1 accountID:(id)arg2;	// IMP=0x00100000006f57d0
- (_Bool)mergeMigrationStateFromRecord:(id)arg1;	// IMP=0x00100000006f4780
- (void)sortChildrenObjects;	// IMP=0x00100000006f2e70
- (id)recordType;	// IMP=0x00100000006f1c60
- (id)recordZoneName;	// IMP=0x00100000006f1c00
- (id)recordName;	// IMP=0x00100000006f1b80

// Remaining properties
@property(retain, nonatomic) NSSet *ckServerChangeTokens; // @dynamic ckServerChangeTokens;
@property(retain, nonatomic) NSSet *ckSharedObjectOwnerNames; // @dynamic ckSharedObjectOwnerNames;
@property(copy, nonatomic) NSString *ckUserRecordName; // @dynamic ckUserRecordName;
@property(nonatomic) _Bool daAllowsCalendarAddDeleteModify; // @dynamic daAllowsCalendarAddDeleteModify;
@property(copy, nonatomic) NSString *daConstraintsDescriptionPath; // @dynamic daConstraintsDescriptionPath;
@property(nonatomic) _Bool daSupportsSharedCalendars; // @dynamic daSupportsSharedCalendars;
@property(nonatomic) _Bool daWasMigrated; // @dynamic daWasMigrated;
@property(nonatomic) _Bool debugSyncDisabled; // @dynamic debugSyncDisabled;
@property(nonatomic) _Bool didChooseToMigrate; // @dynamic didChooseToMigrate;
@property(nonatomic) _Bool didChooseToMigrateLocally; // @dynamic didChooseToMigrateLocally;
@property(nonatomic) _Bool didFinishMigration; // @dynamic didFinishMigration;
@property(nonatomic) _Bool inactive; // @dynamic inactive;
@property(retain, nonatomic) NSData *listIDsMergeableOrdering_v2; // @dynamic listIDsMergeableOrdering_v2;
@property(retain, nonatomic) NSOrderedSet *lists; // @dynamic lists;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) long long persistenceCloudSchemaVersion; // @dynamic persistenceCloudSchemaVersion;
@property(copy, nonatomic) NSString *personID; // @dynamic personID;
@property(retain, nonatomic) NSData *personIDSalt_v1; // @dynamic personIDSalt_v1;
@property(retain, nonatomic) NSSet *reminders; // @dynamic reminders;
@property(retain, nonatomic) NSOrderedSet *smartLists; // @dynamic smartLists;
@property(retain, nonatomic) NSSet *templates; // @dynamic templates;
@property(nonatomic) short type; // @dynamic type;

@end

