//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, NSURL;

@interface REMCDURLAttachment
{
}

+ (id)cdEntityName;	// IMP=0x0010000000088986
+ (_Bool)isAbstract;	// IMP=0x001000000008897e
+ (id)fetchRequest;	// IMP=0x00100000000a73e1

// Remaining properties
@property(retain, nonatomic) NSData *metadata; // @dynamic metadata;
@property(copy, nonatomic) NSURL *url; // @dynamic url;

@end

