//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, NSDate, NSOrderedSet, NSSet, NSString, NSUUID, REMCDAccount, REMCDSharee, REMColor;

@interface REMCDList
{
}

+ (id)propertiesThatShouldTriggerReindexing;	// IMP=0x002000000005620c
+ (id)cdEntityName;	// IMP=0x001000000005611f
+ (_Bool)isAbstract;	// IMP=0x0010000000056117
+ (id)keyPathsForValuesAffectingEffectiveMinimumSupportedVersion;	// IMP=0x001000000005fc36
+ (id)fetchRequest;	// IMP=0x00100000000a7401
+ (_Bool)shouldAttemptLocalObjectMerge;	// IMP=0x00100000003cb5d0
+ (id)newPlaceholderObjectForRecordID:(id)arg1 account:(id)arg2 context:(id)arg3;	// IMP=0x00100000003c07d0
+ (id)newCloudObjectForRecord:(id)arg1 account:(id)arg2 context:(id)arg3;	// IMP=0x00100000003c0680
+ (id)existingCloudObjectForRecordID:(id)arg1 accountID:(id)arg2 context:(id)arg3;	// IMP=0x00100000003bfd60
+ (id)recordTypes;	// IMP=0x00100000003bfc40
- (id)spotlightObjectToReindex;	// IMP=0x001000000005622c
- (void)incrementSpotlightIndexCount;	// IMP=0x00100000000561b9
- (_Bool)isShared;	// IMP=0x0010000000056138
- (id)_parentZoneMismatchErrorDebugDescription;	// IMP=0x001000000005607f
- (_Bool)validateForDelete:(id *)arg1;	// IMP=0x0010000000055fba
- (_Bool)validateForInsert:(id *)arg1;	// IMP=0x0010000000055eee
- (long long)compare:(id)arg1;	// IMP=0x0010000000055df9
@property(retain, nonatomic) NSData *reminderIDsMergeableOrdering; // @dynamic reminderIDsMergeableOrdering;
- (void)debug_lowLevelRemoveFromParent;	// IMP=0x001000000005fd3e
- (long long)parentEffectiveMinimumSupportedVersion;	// IMP=0x001000000005fc62
- (_Bool)shouldCascadeMarkAsDeleteInto:(id)arg1 forRelationship:(id)arg2;	// IMP=0x001000000005fb20
- (_Bool)isConnectedToAccountObject:(id)arg1;	// IMP=0x001000000005f9bf
@property(readonly) NSString *displayName;
- (_Bool)shouldUseResolutionTokenMapForMergingData;	// IMP=0x00100000003bf4a0
- (void)restoreParentReferenceAfterUnmarkingForDeletion;	// IMP=0x00100000003d0270
- (id)objectsToBeDeletedBeforeThisObject;	// IMP=0x00100000003d01c0
- (void)cleanUpAfterLocalObjectMerge;	// IMP=0x00100000003d0110
- (_Bool)mergeWithLocalObject:(id)arg1;	// IMP=0x00100000003d00a0
- (id)existingLocalObjectToMergeWithPredicate:(id)arg1;	// IMP=0x00100000003cc300
- (void)updateObjectWithShare:(id)arg1;	// IMP=0x00100000003cb570
- (id)shareType;	// IMP=0x00100000003c8730
- (id)shareTitle;	// IMP=0x00100000003c8650
- (_Bool)shouldMarkAsDeletedInsteadOfDeletingImmediately;	// IMP=0x00100000003c85c0
- (_Bool)supportsDeletionByTTL;	// IMP=0x00100000003c85a0
- (id)newlyCreatedRecord;	// IMP=0x00100000003c8550
- (void)mergeDataFromRecord:(id)arg1 accountID:(id)arg2;	// IMP=0x00100000003c7420
- (void)sortChildrenObjects;	// IMP=0x00100000003c1f00
- (id)recordType;	// IMP=0x00100000003c09c0
- (id)recordZoneName;	// IMP=0x00100000003c0960
- (void)objectWasDeletedFromCloudByAnotherDevice;	// IMP=0x00100000003c08c0

// Remaining properties
@property(copy, nonatomic) NSString *badgeEmblem; // @dynamic badgeEmblem;
@property(retain, nonatomic) NSSet *calDAVNotifications; // @dynamic calDAVNotifications;
@property(retain, nonatomic) NSOrderedSet *childLists; // @dynamic childLists;
@property(retain, nonatomic) NSOrderedSet *childSmartLists; // @dynamic childSmartLists;
@property(retain, nonatomic) REMColor *color; // @dynamic color;
@property(retain, nonatomic) NSData *daBulkRequests; // @dynamic daBulkRequests;
@property(nonatomic) long long daDisplayOrder; // @dynamic daDisplayOrder;
@property(copy, nonatomic) NSString *daExternalIdentificationTag; // @dynamic daExternalIdentificationTag;
@property(nonatomic) _Bool daIsEventOnlyContainer; // @dynamic daIsEventOnlyContainer;
@property(nonatomic) _Bool daIsImmutable; // @dynamic daIsImmutable;
@property(nonatomic) _Bool daIsNotificationsCollection; // @dynamic daIsNotificationsCollection;
@property(nonatomic) _Bool daIsReadOnly; // @dynamic daIsReadOnly;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSData *groceryLocalCorrectionsAsData; // @dynamic groceryLocalCorrectionsAsData;
@property(retain, nonatomic) NSString *groceryLocalCorrectionsChecksum; // @dynamic groceryLocalCorrectionsChecksum;
@property(copy, nonatomic) NSString *groceryLocaleID; // @dynamic groceryLocaleID;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isGroup; // @dynamic isGroup;
@property(nonatomic) _Bool isPinnedByCurrentUser; // @dynamic isPinnedByCurrentUser;
@property(copy, nonatomic) NSDate *lastUserAccessDate; // @dynamic lastUserAccessDate;
@property(retain, nonatomic) NSData *membershipsOfRemindersInSectionsAsData; // @dynamic membershipsOfRemindersInSectionsAsData;
@property(retain, nonatomic) NSString *membershipsOfRemindersInSectionsChecksum; // @dynamic membershipsOfRemindersInSectionsChecksum;
@property(retain, nonatomic) NSUUID *mostRecentTargetTemplateIdentifier; // @dynamic mostRecentTargetTemplateIdentifier;
@property(retain, nonatomic) NSUUID *mostRecentTargetTemplateIdentifierByCurrentUser; // @dynamic mostRecentTargetTemplateIdentifierByCurrentUser;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) REMCDAccount *parentAccount; // @dynamic parentAccount;
@property(retain, nonatomic) REMCDList *parentList; // @dynamic parentList;
@property(copy, nonatomic) NSDate *pinnedDate; // @dynamic pinnedDate;
@property(retain, nonatomic) NSData *reminderIDsMergeableOrdering_v2_JSON; // @dynamic reminderIDsMergeableOrdering_v2_JSON;
@property(retain, nonatomic) NSOrderedSet *reminders; // @dynamic reminders;
@property(retain, nonatomic) NSData *sectionIDsOrderingAsData; // @dynamic sectionIDsOrderingAsData;
@property(retain, nonatomic) NSOrderedSet *sections; // @dynamic sections;
@property(retain, nonatomic) REMCDSharee *sharedOwner; // @dynamic sharedOwner;
@property(copy, nonatomic) NSString *sharedOwnerAddress; // @dynamic sharedOwnerAddress;
@property(copy, nonatomic) NSString *sharedOwnerName; // @dynamic sharedOwnerName;
@property(retain, nonatomic) NSSet *sharees; // @dynamic sharees;
@property(nonatomic) short sharingStatus; // @dynamic sharingStatus;
@property(nonatomic) _Bool shouldCategorizeGroceryItems; // @dynamic shouldCategorizeGroceryItems;
@property(nonatomic) _Bool shouldSuggestConversionToGroceryList; // @dynamic shouldSuggestConversionToGroceryList;
@property(nonatomic) _Bool showingLargeAttachments; // @dynamic showingLargeAttachments;
@property(copy, nonatomic) NSString *sortingStyle; // @dynamic sortingStyle;
@property(nonatomic) long long spotlightIndexCount; // @dynamic spotlightIndexCount;
@property(readonly) Class superclass;

@end

