//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSArray, NSString, PRSRankingConfiguration, SDSearchQuery, SFStartLocalSearchFeedback, SITracingObjcLifetimeSpan, SPCoreSpotlightDatastore, SPCoreSpotlightTask;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SPCoreSpotlightQueryTask : NSObject
{
    SFStartLocalSearchFeedback *_feedback;	// 8 = 0x8
    SITracingObjcLifetimeSpan *_lifetimeSpan;	// 16 = 0x10
    _Bool _done;	// 24 = 0x18
    _Bool _live;	// 25 = 0x19
    _Bool _canceled;	// 26 = 0x1a
    _Bool _priorityIndexEnabled;	// 27 = 0x1b
    MISSING_TYPE *_priorityIndexFinished;	// 28 = 0x1c
    SPCoreSpotlightTask *_job;	// 32 = 0x20
    SPCoreSpotlightDatastore *_store;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_queue;	// 48 = 0x30
    SDSearchQuery *_resultPipe;	// 56 = 0x38
    unsigned long long _type;	// 64 = 0x40
    PRSRankingConfiguration *_rankingInfo;	// 72 = 0x48
    NSArray *_suggestionResults;	// 80 = 0x50
    double _startTime;	// 88 = 0x58
    NSObject<OS_dispatch_source> *_timeoutTimer;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x002000000004ae10
@property _Bool priorityIndexFinished; // @synthesize priorityIndexFinished=_priorityIndexFinished;
@property _Bool priorityIndexEnabled; // @synthesize priorityIndexEnabled=_priorityIndexEnabled;
@property(retain) NSObject<OS_dispatch_source> *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property double startTime; // @synthesize startTime=_startTime;
@property _Bool canceled; // @synthesize canceled=_canceled;
@property _Bool live; // @synthesize live=_live;
@property _Bool done; // @synthesize done=_done;
@property(retain, nonatomic) NSArray *suggestionResults; // @synthesize suggestionResults=_suggestionResults;
@property(retain) PRSRankingConfiguration *rankingInfo; // @synthesize rankingInfo=_rankingInfo;
@property unsigned long long type; // @synthesize type=_type;
@property(nonatomic) __weak SDSearchQuery *resultPipe; // @synthesize resultPipe=_resultPipe;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly) SPCoreSpotlightDatastore *store; // @synthesize store=_store;
@property(retain, nonatomic) SPCoreSpotlightTask *job; // @synthesize job=_job;
- (void)finish;	// IMP=0x001000000004acab
- (void)finishWithSections:(id)arg1 suggestionResults:(id)arg2;	// IMP=0x001000000004a539
- (void)progressWithSections:(id)arg1 suggestionResults:(id)arg2;	// IMP=0x001000000004a239
- (void)sendCompletions:(id)arg1;	// IMP=0x0010000000049e38
- (void)beginQuery:(id)arg1;	// IMP=0x0010000000049868
- (void)cancel;	// IMP=0x0010000000049318
- (void)reset;	// IMP=0x001000000004919a
- (id)initWithStore:(id)arg1 resultPipe:(id)arg2;	// IMP=0x0010000000049048

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

