//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol SFFeedbackListener;

@interface SPFeedbackListenerWrapper : NSObject
{
    id <SFFeedbackListener> _feedbackListener;	// 8 = 0x8
    unsigned long long _supportedTypes;	// 16 = 0x10
}

+ (id)wrapperWithFeedbackListener:(id)arg1;	// IMP=0x004000000008158a
+ (void)initialize;	// IMP=0x001000000008154d
- (void).cxx_destruct;	// IMP=0x00200000000816ae
@property(nonatomic) unsigned long long supportedTypes; // @synthesize supportedTypes=_supportedTypes;
@property(retain, nonatomic) id <SFFeedbackListener> feedbackListener; // @synthesize feedbackListener=_feedbackListener;
- (id)initWithFeedbackListener:(id)arg1;	// IMP=0x00100000000815d7
- (_Bool)supportsFeedbackType:(long long)arg1;	// IMP=0x0010000000081571

@end

