//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDLockDeviceOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x004000000005ce8b
+ (id)whitelistedClassesForRequest;	// IMP=0x001000000005ce59
- (void)runWithRequest:(id)arg1;	// IMP=0x001000000005ce98

@end

