//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDate;

@interface DMDManageAppPromptPolicy : NSObject
{
    NSArray *_promptTimestamps;	// 8 = 0x8
    long long _promptsAllowed;	// 16 = 0x10
    double _promptResetTimeInterval;	// 24 = 0x18
    NSDate *_overrideDate;	// 32 = 0x20
}

+ (double)promptWindowInterval;	// IMP=0x004000000005d1e3
+ (long long)promptsAllowedBeforeAutomaticDenial;	// IMP=0x001000000005d13b
+ (id)timestampsKey;	// IMP=0x001000000005d12e
- (void).cxx_destruct;	// IMP=0x002000000005dac0
@property(copy, nonatomic) NSDate *overrideDate; // @synthesize overrideDate=_overrideDate;
@property(readonly, nonatomic) double promptResetTimeInterval; // @synthesize promptResetTimeInterval=_promptResetTimeInterval;
@property(readonly, nonatomic) long long promptsAllowed; // @synthesize promptsAllowed=_promptsAllowed;
@property(copy, nonatomic) NSArray *promptTimestamps; // @synthesize promptTimestamps=_promptTimestamps;
- (id)_timestampDictionaryForWritingToFile;	// IMP=0x001000000005d9c8
- (id)_timestampDataForWritingToFile;	// IMP=0x001000000005d8f9
- (void)writeTimestampsToFile;	// IMP=0x001000000005d810
- (void)readTimestampsFromFile;	// IMP=0x001000000005d727
- (void)_removePromptTimestampsOutsideIntervalEnding:(id)arg1;	// IMP=0x001000000005d4f5
- (id)_now;	// IMP=0x001000000005d492
- (void)recordNewPrompt;	// IMP=0x001000000005d3e6
- (_Bool)isPromptAllowedRightNow;	// IMP=0x001000000005d348
- (id)init;	// IMP=0x001000000005d2aa

@end

