//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface GKContactsCacheUpdateBatchEndCommand : NSObject
{
}

- (void)addSyncedHandlesToIDSCache:(id)arg1 withContext:(id)arg2;	// IMP=0x004000000010addf
- (void)executeWithHandles:(id)arg1 context:(id)arg2;	// IMP=0x001000000010adcd

@end

