//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;
@protocol OS_dispatch_queue;

@interface SYDStoreBundleMap : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSDictionary *_cachedStoreBundleMap;	// 16 = 0x10
}

+ (id)disabledStoreIdentifiers;	// IMP=0x0040000000002e6a
+ (id)sharedInstance;	// IMP=0x001000000000258e
- (void).cxx_destruct;	// IMP=0x002000000000405f
@property(retain, nonatomic) NSDictionary *cachedStoreBundleMap; // @synthesize cachedStoreBundleMap=_cachedStoreBundleMap;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)installedAppsDidChange:(id)arg1;	// IMP=0x0010000000003f18
- (id)generateStoreBundleMap;	// IMP=0x00100000000035d0
- (id)storeIdentifiersForInstalledBundles;	// IMP=0x001000000000342b
- (void)clearCachedStoreBundleMap;	// IMP=0x001000000000332b
- (void)generateStoreBundleMapIfNecessary;	// IMP=0x0010000000003261
- (id)bundleIdentifiersForStoreIdentifier:(id)arg1;	// IMP=0x0010000000002ff9
- (_Bool)isStoreIdentifierUsedOnThisDevice:(id)arg1;	// IMP=0x0010000000002ee4
- (void)setCloudSyncUserDefaultEnabled:(_Bool)arg1 storeIdentifier:(id)arg2;	// IMP=0x0010000000002b7d
- (_Bool)isCloudSyncUserDefaultEnabledForStoreIdentifier:(id)arg1;	// IMP=0x00100000000028ac
- (_Bool)shouldSyncStoreWithIdentifier:(id)arg1;	// IMP=0x0010000000002772
- (void)dealloc;	// IMP=0x00100000000026fd
- (id)init;	// IMP=0x00100000000025e3

@end

