//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PAMediaConversionServiceSharedUtilitiesServiceSide : NSObject
{
}

+ (id)temporaryFilesDirectoryURLForConversionTaskIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000016afa
+ (id)temporaryDestinationURLCollectionForFinalDestinationURLCollection:(id)arg1 inParentDirectoryURL:(id)arg2;	// IMP=0x001000000001691f
+ (struct CGSize)imageSizeForImageData:(id)arg1;	// IMP=0x0010000000016694
+ (struct CGImage *)newScaledImageForImageRef:(struct CGImage *)arg1 scaleFactor:(double)arg2 orientation:(long long)arg3 colorspace:(struct CGColorSpace *)arg4;	// IMP=0x001000000001651b
+ (struct CGImage *)newScaledImageForImageRef:(struct CGImage *)arg1 inputSize:(struct PFIntSize_st)arg2 outputSize:(struct PFIntSize_st)arg3 sx:(double)arg4 sy:(double)arg5 orientation:(long long)arg6 colorspace:(struct CGColorSpace *)arg7;	// IMP=0x0010000000016314
+ (id)imageDataForPhotosAdjustmentsComposition:(id)arg1 source:(id)arg2 exporterImageOptions:(id)arg3 outOutputSize:(struct CGSize *)arg4 job:(id)arg5;	// IMP=0x0010000000015f5a
+ (id)exporterVideoOptionsForScaleFactor:(double)arg1 maximumPixelCount:(long long)arg2;	// IMP=0x0010000000015e8e
+ (id)scalePolicyForScaleFactor:(double)arg1 maximumPixelCount:(long long)arg2;	// IMP=0x0010000000015e0d
+ (id)exporterImageOptionsForScaleFactor:(double)arg1 maximumPixelCount:(long long)arg2 metadataPolicy:(id)arg3 shouldApplyOrientationTransform:(_Bool)arg4 outputFileType:(id)arg5;	// IMP=0x0010000000015af0
+ (void)renderPhotosAdjustmentsComposition:(id)arg1 forConversionJob:(id)arg2;	// IMP=0x0010000000014a54
+ (id)finalizedPhotosAdjustmentsCompositionForComposition:(id)arg1 withCandidacy:(id)arg2 finalizationDisposition:(long long *)arg3;	// IMP=0x0010000000014a47
+ (id)finalizedPhotosAdjustmentsCompositionForComposition:(id)arg1 byUpdatingConversionJob:(id)arg2;	// IMP=0x00100000000148f0
+ (void)configureSourcesForComposition:(id)arg1 fromPhotosAdjustmentsJob:(id)arg2;	// IMP=0x0010000000014299
+ (id)loadCompositionFrom:(id)arg1 formatIdentifier:(id)arg2 formatVersion:(id)arg3 error:(id *)arg4;	// IMP=0x00100000000138d5
+ (id)compositionForPhotosAdjustmentInformation:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000135d6
+ (id)adjustmentInformationForComposition:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000134b5
+ (id)generatePortraitAdjustmentForURL:(id)arg1 contentType:(id)arg2 orientation:(unsigned int)arg3 error:(id *)arg4;	// IMP=0x0010000000012ba2
+ (id)emptyGenericCompositionWithAdjustmentForOrientation:(long long)arg1;	// IMP=0x00100000000129fe
+ (void)registerPhotosAdjustmentsSubsystems;	// IMP=0x00100000000129dc
+ (_Bool)isOutputCorruptionLikelyUsingSSIMOfInputURL:(id)arg1 toOutputURL:(id)arg2;	// IMP=0x001000000001279a
+ (_Bool)isOutputCorruptionLikelyComparingFileSizeOfInputURL:(id)arg1 toOutputURL:(id)arg2;	// IMP=0x00100000000120a6
+ (void)checkConversionResultForOutputCorruptionAndMarkJobAsFailed:(id)arg1;	// IMP=0x0010000000011d5c
+ (void)executeConversionJob:(id)arg1;	// IMP=0x0010000000010a0c

@end

