//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FCCloudContext, FCKeyedOperationQueue, FRArticleContentPool, NSMutableDictionary, NSString;

@interface FRArticlePrefetchManager : NSObject
{
    FCCloudContext *_context;	// 8 = 0x8
    FRArticleContentPool *_articleContentPool;	// 16 = 0x10
    FCKeyedOperationQueue *_prefetchQueue;	// 24 = 0x18
    long long _suspendedDepth;	// 32 = 0x20
    NSMutableDictionary *_prefetchRequestsByID;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000b2201
@property(retain, nonatomic) NSMutableDictionary *prefetchRequestsByID; // @synthesize prefetchRequestsByID=_prefetchRequestsByID;
@property(nonatomic) long long suspendedDepth; // @synthesize suspendedDepth=_suspendedDepth;
@property(retain, nonatomic) FCKeyedOperationQueue *prefetchQueue; // @synthesize prefetchQueue=_prefetchQueue;
@property(retain, nonatomic) FRArticleContentPool *articleContentPool; // @synthesize articleContentPool=_articleContentPool;
@property(retain, nonatomic) FCCloudContext *context; // @synthesize context=_context;
- (void)_revisitSuspendedState;	// IMP=0x00100000000b2140
- (void)_prefetchRequestsChanged;	// IMP=0x00100000000b1e76
- (void)networkReachabilityDidChange:(id)arg1;	// IMP=0x00100000000b1e64
- (id)keyedOperationQueue:(id)arg1 performAsyncOperationForKey:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000b1a51
- (void)popPrefetchSuspended;	// IMP=0x00100000000b19c9
- (void)pushPrefetchSuspended;	// IMP=0x00100000000b1976
- (void)resetPrefetchStateForArticleID:(id)arg1 withHeadline:(id)arg2;	// IMP=0x00100000000b178b
- (void)removePrefetchInterestInHeadline:(id)arg1;	// IMP=0x00100000000b14c6
- (void)addPrefetchInterestInHeadline:(id)arg1 priority:(unsigned long long)arg2 options:(unsigned long long)arg3;	// IMP=0x00100000000b119a
- (void)dealloc;	// IMP=0x00100000000b1125
- (id)initWithCloudContext:(id)arg1 articleContentPool:(id)arg2;	// IMP=0x00100000000b0f90

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

