//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface FRMacros : NSObject
{
}

+ (_Bool)isHardwareKeyboardAttached;	// IMP=0x004000000006f2c3
+ (double)deviceScreenScaleFromPotentialBackgroundThread;	// IMP=0x001000000006f1df
+ (_Bool)isUIAutomationRunning;	// IMP=0x001000000006f158
+ (_Bool)isOrbDevice;	// IMP=0x001000000006f0e3
+ (_Bool)isSpectreDevice;	// IMP=0x001000000006f0d9
+ (_Bool)iPhoneFancyAF;	// IMP=0x001000000006f027
+ (_Bool)iPhone6POrLess;	// IMP=0x001000000006ef77
+ (_Bool)iPhone6P;	// IMP=0x001000000006ee31
+ (_Bool)iPhone6OrLess;	// IMP=0x001000000006ed81
+ (_Bool)iPhone6;	// IMP=0x001000000006ec3b
+ (_Bool)iPhone5Landscape;	// IMP=0x001000000006eb99
+ (_Bool)iPhone5;	// IMP=0x001000000006ea53
+ (_Bool)iPhone5OrLess;	// IMP=0x001000000006e913
+ (_Bool)iPhone4OrLess;	// IMP=0x001000000006e7d3
+ (_Bool)retina;	// IMP=0x001000000006e755
+ (_Bool)iPhone;	// IMP=0x001000000006e6dc
+ (_Bool)iPad;	// IMP=0x001000000006e662
+ (_Bool)iPadPro;	// IMP=0x001000000006e51c
+ (_Bool)portrait;	// IMP=0x001000000006e46d
+ (_Bool)splitScreenTwoThirds;	// IMP=0x001000000006e30b
+ (_Bool)splitScreenThreeQuarters;	// IMP=0x001000000006e1a6
+ (_Bool)splitScreenOneThird;	// IMP=0x001000000006e045
+ (_Bool)splitScreenEqual;	// IMP=0x001000000006dee6
+ (_Bool)splitScreen;	// IMP=0x001000000006ddb3
+ (double)minScreenSide;	// IMP=0x001000000006dc95
+ (double)maxScreenSide;	// IMP=0x001000000006db7b
+ (_Bool)disableAllAds;	// IMP=0x001000000006db19
+ (_Bool)windowIsLandscape;	// IMP=0x001000000006da43
+ (_Bool)viewIsCompact:(id)arg1;	// IMP=0x001000000006d9c6
+ (id)imageFromNewGraphicsContextWithSize:(struct CGSize)arg1 opaque:(_Bool)arg2 forceSRGB:(_Bool)arg3 scale:(double)arg4 contextBlock:(CDUnknownBlockType)arg5;	// IMP=0x001000000006d822
+ (id)imageFromNewGraphicsContextWithSize:(struct CGSize)arg1 opaque:(_Bool)arg2 scale:(double)arg3 contextBlock:(CDUnknownBlockType)arg4;	// IMP=0x001000000006d808
+ (void)useManagedContextWithSize:(struct CGSize)arg1 opaque:(_Bool)arg2 forceSRGB:(_Bool)arg3 scale:(double)arg4 contextBlock:(CDUnknownBlockType)arg5;	// IMP=0x001000000006d64e
+ (void)useManagedContextWithSize:(struct CGSize)arg1 opaque:(_Bool)arg2 scale:(double)arg3 contextBlock:(CDUnknownBlockType)arg4;	// IMP=0x001000000006d634

@end

