//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSString;

@interface ServiceProductActivityViewController : UIViewController
{
    NSString *_logKey;	// 8 = 0x8
    struct CGRect _popoverSourceRect;	// 16 = 0x10
}

+ (id)_remoteViewControllerInterface;	// IMP=0x004000000002996f
+ (id)_exportedInterface;	// IMP=0x001000000002994f
- (void).cxx_destruct;	// IMP=0x002000000002c23c
@property(nonatomic) struct CGRect popoverSourceRect; // @synthesize popoverSourceRect=_popoverSourceRect;
- (id)_clientViewControllerProxy;	// IMP=0x001000000002c1ec
- (void)_lookupItemWithIdentifier:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;	// IMP=0x001000000002b64e
- (id)_productIDFromParameters:(id)arg1;	// IMP=0x001000000002b4ed
- (void)_loadDidFailWithError:(id)arg1;	// IMP=0x001000000002b0da
- (void)_presentActivityViewControllerWithItem:(id)arg1;	// IMP=0x001000000002aa60
- (void)_loadClientContextWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000002a86a
- (void)finishImmediately:(id)arg1;	// IMP=0x001000000002a5c5
- (void)setupProductWithParameters:(id)arg1;	// IMP=0x0010000000029e73
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0010000000029dbf
- (void)dealloc;	// IMP=0x0010000000029c01
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x001000000002998f

@end

