//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7parsecdP33_8CB648D6D3AEBC962B83344466C6EBB925SessionEndEventController : _TtCs12_SwiftObject
{
    MISSING_TYPE *connectionIDs;	// 16 = 0x10
    MISSING_TYPE *transaction;	// 24 = 0x18
    MISSING_TYPE *lock;	// 32 = 0x20
}

@end

