//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC11Schematizer18ProtoMessageSchema
{
    MISSING_TYPE *options;	// 32 = 0x20
    MISSING_TYPE *allPropertyNames;	// 40 = 0x28
    MISSING_TYPE *allOneOfNames;	// 48 = 0x30
    MISSING_TYPE *store;	// 56 = 0x38
    MISSING_TYPE *properties;	// 72 = 0x48
    MISSING_TYPE *oneOfs;	// 80 = 0x50
    MISSING_TYPE *propertyModels;	// 88 = 0x58
    MISSING_TYPE *oneOfModels;	// 96 = 0x60
}

@end

