//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSError.h>

@interface NSError (XCTDaemonErrors)
+ (id)_xctd_error:(long long)arg1 description:(id)arg2 userInfo:(id)arg3;	// IMP=0x001000000001bf20
+ (id)_xctd_error:(long long)arg1 description:(id)arg2;	// IMP=0x001000000001bd6d
+ (id)_xctd_error_Swift:(long long)arg1 description:(id)arg2 userInfo:(id)arg3;	// IMP=0x001000000001bd37
+ (id)_xctd_error_Swift:(long long)arg1 description:(id)arg2;	// IMP=0x001000000001bd12
@end

