//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSBlockOperation.h>

@class CKKSCondition, NSDate, NSError, NSMutableArray, NSObject;
@protocol OS_dispatch_queue;

@interface CKKSResultOperation : NSBlockOperation
{
    _Bool _timeoutCanOccur;	// 8 = 0x8
    NSError *_error;	// 16 = 0x10
    NSDate *_finishDate;	// 24 = 0x18
    CKKSCondition *_completionHandlerDidRunCondition;	// 32 = 0x20
    long long _descriptionErrorCode;	// 40 = 0x28
    NSMutableArray *_successDependencies;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_timeoutQueue;	// 56 = 0x38
    CDUnknownBlockType _finishingBlock;	// 64 = 0x40
}

+ (id)named:(id)arg1 withBlockTakingSelf:(CDUnknownBlockType)arg2;	// IMP=0x0040000000143b02
+ (id)named:(id)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000143a8e
+ (id)operationWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000143a45
- (void).cxx_destruct;	// IMP=0x002000000014364b
@property(copy) CDUnknownBlockType finishingBlock; // @synthesize finishingBlock=_finishingBlock;
@property(retain) NSObject<OS_dispatch_queue> *timeoutQueue; // @synthesize timeoutQueue=_timeoutQueue;
@property _Bool timeoutCanOccur; // @synthesize timeoutCanOccur=_timeoutCanOccur;
@property(retain) NSMutableArray *successDependencies; // @synthesize successDependencies=_successDependencies;
@property long long descriptionErrorCode; // @synthesize descriptionErrorCode=_descriptionErrorCode;
@property(retain) CKKSCondition *completionHandlerDidRunCondition; // @synthesize completionHandlerDidRunCondition=_completionHandlerDidRunCondition;
@property(retain) NSDate *finishDate; // @synthesize finishDate=_finishDate;
@property(retain) NSError *error; // @synthesize error=_error;
- (_Bool)allSuccessful:(id)arg1;	// IMP=0x0010000000142efe
- (_Bool)allDependentsSuccessful;	// IMP=0x0010000000142ead
- (void)addNullableSuccessDependency:(id)arg1;	// IMP=0x0010000000142dfa
- (void)addSuccessDependency:(id)arg1;	// IMP=0x0010000000142de8
- (id)timeout:(unsigned long long)arg1;	// IMP=0x0010000000142d01
- (id)_onqueueTimeoutError;	// IMP=0x0010000000142bdb
- (id)descriptionError;	// IMP=0x0010000000142b01
- (id)dependenciesDescriptionError;	// IMP=0x00100000001428ae
- (void)invalidateTimeout;	// IMP=0x001000000014283d
- (void)start;	// IMP=0x00100000001427da
- (void)setCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000001426e1
- (id)debugDescription;	// IMP=0x00100000001426cf
- (id)description;	// IMP=0x0010000000142534
- (id)operationStateString;	// IMP=0x0010000000142449
- (id)init;	// IMP=0x00100000001422a5

@end

