//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;
@protocol SecCKKSKeyClass;

@interface CKKSCurrentKeyPointer
{
    NSString<SecCKKSKeyClass> *_keyclass;	// 8 = 0x8
    NSString *_currentKeyUUID;	// 16 = 0x10
}

+ (_Bool)intransactionRecordDeleted:(id)arg1 contextID:(id)arg2 error:(id *)arg3;	// IMP=0x00400000000a67df
+ (_Bool)intransactionRecordChanged:(id)arg1 contextID:(id)arg2 resync:(_Bool)arg3 flagHandler:(id)arg4 error:(id *)arg5;	// IMP=0x00100000000a5ff8
+ (id)fromDatabaseRow:(id)arg1;	// IMP=0x00100000000a5df0
+ (id)sqlColumns;	// IMP=0x00100000000a5de3
+ (id)sqlTable;	// IMP=0x00100000000a5dd6
+ (_Bool)deleteAll:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000a5cc6
+ (id)all:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000a5beb
+ (id)forKeyClass:(id)arg1 contextID:(id)arg2 withKeyUUID:(id)arg3 zoneID:(id)arg4 error:(id *)arg5;	// IMP=0x00100000000a5a8e
+ (id)tryFromDatabase:(id)arg1 contextID:(id)arg2 zoneID:(id)arg3 error:(id *)arg4;	// IMP=0x00100000000a5962
+ (id)fromDatabase:(id)arg1 contextID:(id)arg2 zoneID:(id)arg3 error:(id *)arg4;	// IMP=0x00100000000a5836
- (void).cxx_destruct;	// IMP=0x00200000000a5805
@property(retain) NSString *currentKeyUUID; // @synthesize currentKeyUUID=_currentKeyUUID;
@property(retain) NSString<SecCKKSKeyClass> *keyclass; // @synthesize keyclass=_keyclass;
- (id)sqlValues;	// IMP=0x00100000000a5559
- (id)whereClauseToFindSelf;	// IMP=0x00100000000a5425
- (void)setFromCKRecord:(id)arg1;	// IMP=0x00100000000a516b
- (_Bool)matchesCKRecord:(id)arg1;	// IMP=0x00100000000a4fc8
- (id)updateCKRecord:(id)arg1 zoneID:(id)arg2;	// IMP=0x00100000000a4c93
- (id)CKRecordName;	// IMP=0x00100000000a4c81
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000a49d3
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000a48dd
- (id)description;	// IMP=0x00100000000a47d7
- (id)initForClass:(id)arg1 contextID:(id)arg2 currentKeyUUID:(id)arg3 zoneID:(id)arg4 encodedCKRecord:(id)arg5;	// IMP=0x00100000000a4686

@end

