//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CKRecordID, NSString;

@interface KCSharingOutgoingDeletion
{
    CKRecordID *_recordID;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x002000000001bd84
@property(readonly, nonatomic) CKRecordID *recordID; // @synthesize recordID=_recordID;
- (id)attributesWithAccessGroups:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001bb04
- (id)initWithAttributes:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001b36a
- (id)initWithDeletedRecordID:(id)arg1;	// IMP=0x001000000001b2fc
- (id)initWithDeletedLocalItemForMirrorEntry:(id)arg1;	// IMP=0x001000000001b285

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

