//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface IXPlaceholderAttributes : NSObject
{
    _Bool _launchProhibited;	// 8 = 0x8
    _Bool _watchOnlyApp;	// 9 = 0x9
    _Bool _runsIndependentlyOfCompanionApp;	// 10 = 0xa
    _Bool _arcadeApp;	// 11 = 0xb
    _Bool _lsRequiresPostProcessing;	// 12 = 0xc
    NSString *_bundleVersion;	// 16 = 0x10
    NSDictionary *_extensionDictionary;	// 24 = 0x18
    NSDictionary *_exAppExtensionAttributes;	// 32 = 0x20
    NSString *_minimumOSVersion;	// 40 = 0x28
    NSDictionary *_requiredDeviceCapabilities;	// 48 = 0x30
    NSArray *_sbAppTags;	// 56 = 0x38
    NSArray *_lsCounterpartIdentifiers;	// 64 = 0x40
    NSString *;	// 72 = 0x48
    NSString *_companionBundleIdentifierForWatchApp;	// 80 = 0x50
    NSDictionary *_webKitPushBundleMetadata;	// 88 = 0x58
    NSArray *_uiDeviceFamily;	// 96 = 0x60
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000012ac9
- (void).cxx_destruct;	// IMP=0x002000000001493b
@property(copy, nonatomic) NSArray *uiDeviceFamily; // @synthesize uiDeviceFamily=_uiDeviceFamily;
@property(nonatomic) _Bool lsRequiresPostProcessing; // @synthesize lsRequiresPostProcessing=_lsRequiresPostProcessing;
@property(copy, nonatomic) NSDictionary *webKitPushBundleMetadata; // @synthesize webKitPushBundleMetadata=_webKitPushBundleMetadata;
@property(nonatomic) _Bool arcadeApp; // @synthesize arcadeApp=_arcadeApp;
@property(nonatomic) _Bool runsIndependentlyOfCompanionApp; // @synthesize runsIndependentlyOfCompanionApp=_runsIndependentlyOfCompanionApp;
@property(nonatomic) _Bool watchOnlyApp; // @synthesize watchOnlyApp=_watchOnlyApp;
@property(copy, nonatomic) NSString *companionBundleIdentifierForWatchApp; // @synthesize companionBundleIdentifierForWatchApp=_companionBundleIdentifierForWatchApp;
@property(copy, nonatomic) NSString *sbIconMasqueradeIdentifier; // @synthesize sbIconMasqueradeIdentifier=_sbIconMasqueradeIdentifier;
@property(copy, nonatomic) NSArray *lsCounterpartIdentifiers; // @synthesize lsCounterpartIdentifiers=_lsCounterpartIdentifiers;
@property(copy, nonatomic) NSArray *sbAppTags; // @synthesize sbAppTags=_sbAppTags;
@property(copy, nonatomic) NSDictionary *requiredDeviceCapabilities; // @synthesize requiredDeviceCapabilities=_requiredDeviceCapabilities;
@property(copy, nonatomic) NSString *minimumOSVersion; // @synthesize minimumOSVersion=_minimumOSVersion;
@property(copy, nonatomic) NSDictionary *exAppExtensionAttributes; // @synthesize exAppExtensionAttributes=_exAppExtensionAttributes;
@property(copy, nonatomic) NSDictionary *extensionDictionary; // @synthesize extensionDictionary=_extensionDictionary;
@property(copy, nonatomic) NSString *bundleVersion; // @synthesize bundleVersion=_bundleVersion;
@property(nonatomic) _Bool launchProhibited; // @synthesize launchProhibited=_launchProhibited;
- (id)description;	// IMP=0x001000000001472c
- (id)infoPlistContent;	// IMP=0x0010000000014395
- (void)setRequiredDeviceCapabilitiesWithArray:(id)arg1;	// IMP=0x0010000000014158
- (id)initWithInfoPlistDictionary:(id)arg1;	// IMP=0x001000000001396d
- (id)initWithInfoPlistFromBundle:(struct __CFBundle *)arg1 error:(id *)arg2;	// IMP=0x00100000000138d4
- (id)initWithInfoPlistFromBundleURL:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000013820
- (id)_plistKeys;	// IMP=0x001000000001375d
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000134a7
- (unsigned long long)hash;	// IMP=0x00100000000131a7
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000012ad1
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000001278f
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000000123c1
- (id)init;	// IMP=0x0010000000012392

@end

