//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Messages/MSMessage.h>

@interface MSMessage (NonModularSPI)
- (id)ppl_pluginPayloadWithAppIconData:(id)arg1 appName:(id)arg2 allowDataPayloads:(_Bool)arg3;	// IMP=0x0010000000002007
@end

