//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIControl.h>

@class MISSING_TYPE;

@interface _TtC5Files22DOCAttributionPillView : UIControl
{
    MISSING_TYPE *senderName;	// 8 = 0x8
    MISSING_TYPE *menu;	// 24 = 0x18
    MISSING_TYPE *backgroundView;	// 32 = 0x20
    MISSING_TYPE *containerView;	// 40 = 0x28
    MISSING_TYPE *imageView;	// 48 = 0x30
    MISSING_TYPE *textLabel;	// 56 = 0x38
    MISSING_TYPE *chevronView;	// 64 = 0x40
    MISSING_TYPE *$__lazy_storage_$_baseFont;	// 72 = 0x48
    MISSING_TYPE *$__lazy_storage_$_senderFont;	// 80 = 0x50
    MISSING_TYPE *$__lazy_storage_$_chevronFont;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x0040000000228d50
- (id)contextMenuInteraction:(id)arg1 configurationForMenuAtLocation:(struct CGPoint)arg2;	// IMP=0x0010000000228ca0
- (void)layoutSubviews;	// IMP=0x0010000000228b90
- (void)handleTap:(id)arg1;	// IMP=0x0010000000228b20
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;	// IMP=0x0010000000227940
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000227920
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000002278f0

@end

