//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionViewListCell.h>

@class MISSING_TYPE, NSString, _TtC5Files28DOCItemCollectionCellContent;

@interface _TtC5Files21DOCItemCollectionCell : UICollectionViewListCell
{
    MISSING_TYPE *delegate;	// 8 = 0x8
    MISSING_TYPE *thumbnailView;	// 24 = 0x18
    MISSING_TYPE *itemStatusBadgeConstraintX;	// 32 = 0x20
    MISSING_TYPE *itemStatusBadgeConstraintY;	// 40 = 0x28
    MISSING_TYPE *itemAccessStatusBadgeConstraintX;	// 48 = 0x30
    MISSING_TYPE *itemAccessStatusBadgeConstraintY;	// 56 = 0x38
    MISSING_TYPE *isItemStatusBadgeLoaded;	// 64 = 0x40
    MISSING_TYPE *$__lazy_storage_$_itemStatusBadge;	// 72 = 0x48
    MISSING_TYPE *isItemAccessStatusBadgeLoaded;	// 80 = 0x50
    MISSING_TYPE *$__lazy_storage_$_itemAccessStatusBadge;	// 88 = 0x58
    MISSING_TYPE *$__lazy_storage_$_renameGestureRecognizer;	// 96 = 0x60
    MISSING_TYPE *cellContent;	// 104 = 0x68
    MISSING_TYPE *isDummyCell;	// 112 = 0x70
    MISSING_TYPE *fileEntityInteraction;	// 120 = 0x78
    MISSING_TYPE *actions;	// 128 = 0x80
    MISSING_TYPE *canShowBackgroundView;	// 136 = 0x88
    MISSING_TYPE *horizontalStopButton;	// 144 = 0x90
    MISSING_TYPE *renameController;	// 152 = 0x98
    MISSING_TYPE *renameTextView;	// 160 = 0xa0
    MISSING_TYPE *isRenaming;	// 168 = 0xa8
}

- (void).cxx_destruct;	// IMP=0x004000000020ca70
@property(nonatomic, readonly) _Bool accessibilityIsRenaming;
- (id)accessibilityThumbnailView;	// IMP=0x001000000020c9e0
- (id)accessibilityCellManager;	// IMP=0x001000000020c9c0
- (id)accessibilityTitleString;	// IMP=0x001000000020c980
- (id)accessibilityTitleLabel;	// IMP=0x001000000020c950
- (void)_bridgedUpdateConfigurationUsingState:(id)arg1;	// IMP=0x001000000020c790
- (void)didMoveToSuperview;	// IMP=0x001000000020c450
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x001000000020c3a0
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;	// IMP=0x001000000020c2a0
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x001000000020c240
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x001000000020bfb0
- (void)renameGesture:(id)arg1;	// IMP=0x001000000020bf60
- (void)dragStateDidChange:(long long)arg1;	// IMP=0x001000000020bdc0
@property(nonatomic, readonly) _Bool _allowsHorizontalFocusMovement;
- (id)initWithCoder:(id)arg1;	// IMP=0x001000000020ba80
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000020b9f0
- (void)prepareForReuse;	// IMP=0x001000000020b920
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, retain) _TtC5Files28DOCItemCollectionCellContent *cellContent; // @synthesize cellContent;

@end

