//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UICollectionViewListCell.h>

@class MISSING_TYPE;

@interface _TtC5Files34DOCItemCollectionViewSectionHeader : UICollectionViewListCell
{
    MISSING_TYPE *seeLessString;	// 8 = 0x8
    MISSING_TYPE *$__lazy_storage_$_sectionTitleControl;	// 24 = 0x18
    MISSING_TYPE *expandToggleButtonTitle;	// 40 = 0x28
    MISSING_TYPE *$__lazy_storage_$_expandToggleButton;	// 56 = 0x38
    MISSING_TYPE *$__lazy_storage_$_expandToggleButtonVisibleConstraint;	// 64 = 0x40
    MISSING_TYPE *$__lazy_storage_$_topSeparator;	// 72 = 0x48
    MISSING_TYPE *$__lazy_storage_$_bottomSeparator;	// 80 = 0x50
    MISSING_TYPE *metrics;	// 88 = 0x58
    MISSING_TYPE *regularConstraints;	// 112 = 0x70
    MISSING_TYPE *largeTextConstraints;	// 120 = 0x78
    MISSING_TYPE *traitsSpecificSeparatorConstraints;	// 128 = 0x80
    MISSING_TYPE *itemTags;	// 136 = 0x88
    MISSING_TYPE *title;	// 144 = 0x90
    MISSING_TYPE *itemCount;	// 160 = 0xa0
    MISSING_TYPE *layoutTraits;	// 168 = 0xa8
    MISSING_TYPE *stackMetrics;	// 176 = 0xb0
    MISSING_TYPE *sortButtonsStackView;	// 216 = 0xd8
    MISSING_TYPE *sortButtons;	// 224 = 0xe0
    MISSING_TYPE *sortButtonsConstraints;	// 232 = 0xe8
    MISSING_TYPE *sortingDescriptor;	// 240 = 0xf0
    MISSING_TYPE *displaySortButtons;	// 257 = 0x101
    MISSING_TYPE *groupByMenu;	// 264 = 0x108
    MISSING_TYPE *showToggleExpandedSectionButtonOverride;	// 272 = 0x110
    MISSING_TYPE *isPinned;	// 273 = 0x111
    MISSING_TYPE *hideTopSeparator;	// 274 = 0x112
    MISSING_TYPE *hideSeparators;	// 275 = 0x113
    MISSING_TYPE *style;	// 280 = 0x118
    MISSING_TYPE *representedCollectionSection;	// 288 = 0x120
    MISSING_TYPE *toggleExpandedHandler;	// 328 = 0x148
    MISSING_TYPE *sortButtonTapHandler;	// 344 = 0x158
    MISSING_TYPE *backgroundAlpha;	// 360 = 0x168
    MISSING_TYPE *customBackgroundView;	// 368 = 0x170
    MISSING_TYPE *_labelForAX;	// 376 = 0x178
}

- (void).cxx_destruct;	// IMP=0x00400000003a6d00
- (id);	// IMP=0x00100000003a6ca0
- (void)_bridgedUpdateConfigurationUsingState:(id)arg1;	// IMP=0x00100000003a6b20
- (void)prepareForReuse;	// IMP=0x00100000003a58f0
- (void)didMoveToWindow;	// IMP=0x00100000003a5840
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000003a4a70
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000003a4a40

@end

