//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC5Files22DOCLevelOfDetailButton
{
    MISSING_TYPE *metadataView;	// 16 = 0x10
    MISSING_TYPE *observationContext;	// 24 = 0x18
    MISSING_TYPE *metrics;	// 0 = 0x0
    MISSING_TYPE *levelOfDetailTitle;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x004000000034ef40
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000034eeb0
- (void)tintColorDidChange;	// IMP=0x001000000034ee50

@end

