//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIStackView.h>

@interface _TtC5Files12DOCStackView : UIStackView
{
}

- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00400000004296f0
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000004296a0

@end

