//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

@class MISSING_TYPE;

@interface _TtCC5Files36DOCModalBlurViewControllerTransitionP33_4C4C64B830FA27D5F7277025BBE0D4FD14BackgroundView : UIView
{
    MISSING_TYPE *presented;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00400000003470c0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000347050
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000346fe0
- (void)dismissPresentedViewController:(id)arg1;	// IMP=0x0010000000346f40

@end

