//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIDocumentProperties.h>

@class MISSING_TYPE;

@interface _TtCC5Files31DOCItemCollectionViewController16FolderMenuHeader : UIDocumentProperties
{
    MISSING_TYPE *node;	// 8 = 0x8
    MISSING_TYPE *iconDelivery;	// 16 = 0x10
    MISSING_TYPE *needsFolderSizeMetadataLoad;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x004000000017da50
- (id)initWithMetadata:(id)arg1;	// IMP=0x001000000017d9f0
- (id)initWithURL:(id)arg1;	// IMP=0x001000000017d990

@end

