//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSData, NSDictionary, NSString, NSURL;

@protocol _TtP15icloudmailagent26CertificateRequestProtocol_
- (_Bool)generatePayloadAndRevokeFor:(struct __SecCertificate *)arg1 signingIdentity:(struct __SecIdentity *)arg2 endpoint:(NSURL *)arg3 error:(id *)arg4 errCompletion:(void (^)(NSError *))arg5;
- (_Bool)revokeResultFromServerFor:(NSData *)arg1 endpoint:(NSURL *)arg2 error:(id *)arg3 completion:(void (^)(NSError *))arg4;
- (struct __SecCertificate *)certificateFor:(NSString *)arg1 error:(id *)arg2;
- (NSString *)generateCertificateRequestStringWith:(NSArray *)arg1 subjectAltName:(NSDictionary *)arg2 privateKey:(struct __SecKey *)arg3 encrypt:(_Bool)arg4;
- (NSArray *)resultFromServerFor:(NSString *)arg1 endpoint:(NSURL *)arg2 email:(NSString *)arg3 error:(id *)arg4;
@end

