//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSUnitDuration.h"

__attribute__((visibility("hidden")))
@interface _NSStatic_NSUnitDuration : NSUnitDuration
{
}

- (Class)_effectiveUnitClass;	// IMP=0x0000000000667244
- (Class)classForCoder;	// IMP=0x0000000000667233
- (void)dealloc;	// IMP=0x000000000066722d
- (unsigned long long)retainCount;	// IMP=0x0000000000667220
- (oneway void)release;	// IMP=0x000000000066721a
- (id)retain;	// IMP=0x0000000000667211

@end

