//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSKeyValueGetter.h"

__attribute__((visibility("hidden")))
@interface NSKeyValueUndefinedGetter : NSKeyValueGetter
{
}

- (id)initWithContainerClassID:(id)arg1 key:(id)arg2 containerIsa:(Class)arg3;	// IMP=0x000000000067dbf4

@end

