//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppleMediaServices/AMSBag.h>

@interface AMSBag (ASDAdditions)
- (_Bool)asd_iTunesStoreMetricsIsEnabled;	// IMP=0x00100000001dbfc7
@end

