//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSError;

@interface DownloadGenericError
{
    NSError *_error;	// 40 = 0x28
}

@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000011a1ff
- (id)_notificationTitle;	// IMP=0x0010000000119f79
- (id)_notificationBody;	// IMP=0x0010000000119bbf
- (_Bool)_isInstallError:(id)arg1;	// IMP=0x0010000000119b64
- (void)performActionForResponseFlags:(unsigned long long)arg1;	// IMP=0x0010000000119986
- (id)copyUserNotification;	// IMP=0x00100000001197c4
- (_Bool)canCoalesceWithError:(id)arg1;	// IMP=0x00100000001196f3
- (void)dealloc;	// IMP=0x00100000001196b1
- (id)initWithError:(id)arg1;	// IMP=0x001000000011965a

@end

