//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class NSNumber;

@interface SendInstallAttributionPingbackOperation : ISOperation
{
    NSNumber *_appAdamId;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x00200000001af9fb
- (void)run;	// IMP=0x00100000001af97d
- (id)initWithAdamId:(id)arg1;	// IMP=0x00100000001af903

@end

