//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ICConnectionConfiguration, ICUserIdentity, ICUserIdentityStore, ML3MusicLibrary;
@protocol ICDBackgroundTaskScheduling;

@interface BaseRequestHandler : NSObject
{
    _Bool _active;	// 8 = 0x8
    ICUserIdentity *_userIdentity;	// 16 = 0x10
    ICUserIdentityStore *_userIdentityStore;	// 24 = 0x18
    ICConnectionConfiguration *_configuration;	// 32 = 0x20
    ML3MusicLibrary *_musicLibrary;	// 40 = 0x28
    id <ICDBackgroundTaskScheduling> _taskScheduler;	// 48 = 0x30
}

+ (id)accountlessHandler;	// IMP=0x00200000000243b1
+ (_Bool)supportsAccountlessHandling;	// IMP=0x00100000000243a9
+ (id)managedConfigurations;	// IMP=0x00100000000242a6
+ (id)deleteHandlerForConfiguration:(id)arg1;	// IMP=0x0010000000024154
+ (id)handlerForConfiguration:(id)arg1;	// IMP=0x0010000000024010
+ (id)handlers;	// IMP=0x0010000000023fe1
+ (id)globalSerialQueue;	// IMP=0x0010000000023f7e
- (void).cxx_destruct;	// IMP=0x0020000000023f29
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(retain, nonatomic) id <ICDBackgroundTaskScheduling> taskScheduler; // @synthesize taskScheduler=_taskScheduler;
@property(readonly, nonatomic) ML3MusicLibrary *musicLibrary; // @synthesize musicLibrary=_musicLibrary;
@property(readonly, nonatomic) ICConnectionConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) ICUserIdentityStore *userIdentityStore; // @synthesize userIdentityStore=_userIdentityStore;
@property(readonly, nonatomic) ICUserIdentity *userIdentity; // @synthesize userIdentity=_userIdentity;
- (void)updateLibraryWithReason:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000023ece
- (id)description;	// IMP=0x0010000000023de6
- (void)cancelOperationsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000023de0
- (void)increasePriorityForAllOperations;	// IMP=0x0010000000023dda
- (void)decreasePriorityForAllOperations;	// IMP=0x0010000000023dd4
- (void)onCalloutQueue:(CDUnknownBlockType)arg1;	// IMP=0x0010000000023d31
- (void)cancellAllOperations;	// IMP=0x0010000000023d2b
- (void)performInitialLibraryUpdate;	// IMP=0x0010000000023d25
- (void)becomeInactiveWithDeauthentication:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000023d1f
- (void)becomeActive;	// IMP=0x0010000000023d19
- (id)initWithConfiguration:(id)arg1;	// IMP=0x0010000000023c30
- (id)init;	// IMP=0x0010000000023bee

@end

