//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ICCollaborationBeginRequest
{
    unsigned int _currentContainerDAAPCode;	// 8 = 0x8
}

- (id)_requestBodyWithPlaylistCloudLibraryID:(unsigned long long)arg1 sharingMode:(unsigned long long)arg2;	// IMP=0x002000000012b225
- (id)canonicalResponseForResponse:(id)arg1;	// IMP=0x001000000012b10f
- (id)initWithDatabaseID:(unsigned int)arg1 playlistSagaID:(unsigned long long)arg2 sharingMode:(unsigned long long)arg3;	// IMP=0x001000000012b03b

@end

