//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ICCollaborationRespondToPendingCollaboratorResponse
{
    _Bool _updateRequired;	// 8 = 0x8
    unsigned int _collaborationCloudLibraryID;	// 12 = 0xc
}

@property(nonatomic) unsigned int collaborationCloudLibraryID; // @synthesize collaborationCloudLibraryID=_collaborationCloudLibraryID;
@property(nonatomic) _Bool updateRequired; // @synthesize updateRequired=_updateRequired;

@end

