//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesCloud/ICRequestOperation.h>

@class AMPMusicArtistNewContentResponse, ICStoreRequestContext;

@interface ICMusicLibraryRecommendationsRequest : ICRequestOperation
{
    ICStoreRequestContext *_storeRequestContext;	// 8 = 0x8
    AMPMusicArtistNewContentResponse *_response;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000ab3d8
- (void)execute;	// IMP=0x00100000000ab348
- (void)performRequestWithResponseHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000000ab234
- (id)initWithStoreRequestContext:(id)arg1 params:(id)arg2;	// IMP=0x00100000000ab1c6

@end

