//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class HSProxCardCoordinator, HSSetupStateMachineConfiguration, NSString, UIViewController;

@interface HSPCDoneViewController
{
    HSSetupStateMachineConfiguration *_config;	// 8 = 0x8
    HSProxCardCoordinator *_coordinator;	// 16 = 0x10
}

+ (id)viewControllerForCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x002000000001f841
- (void).cxx_destruct;	// IMP=0x002000000002048a
@property(retain) HSProxCardCoordinator *coordinator; // @synthesize coordinator=_coordinator;
@property(retain) HSSetupStateMachineConfiguration *config; // @synthesize config=_config;
- (_Bool)shouldShowButtonLinkToHomeApp;	// IMP=0x0010000000020315
- (id)launchAdditionalSettings;	// IMP=0x001000000002011e
- (id)commitConfiguration;	// IMP=0x001000000002007e
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x001000000001f8e0

// Remaining properties
@property(retain, nonatomic) UIViewController *contentVC;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

